const _raw_data = {
  "items": [{
    "title": "Avatar (2009)",
    "link": "https://www.imdb.com/title/tt0499549/",
    "score": 5,
    "description": "It's impressive how mediocre this was.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Mary & Max",
    "link": "https://www.imdb.com/title/tt0978762/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Scrubs",
    "link": "https://www.imdb.com/title/tt0285403/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Psych",
    "link": "https://www.imdb.com/title/tt0491738/",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Alita: Battle Angel",
    "link": "https://www.imdb.com/title/tt0437086/",
    "score": 5.5,
    "description": "I haven't seen the anime, but even just watching this I feel like I'm missing out on a lot.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Big Hero 6",
    "link": "https://www.imdb.com/title/tt2245084/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Atlantis: The Lost Empire",
    "link": "https://www.imdb.com/title/tt0230011/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Bruce Almighty",
    "link": "https://www.imdb.com/title/tt0315327/",
    "score": 6.5,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Pokémon: Detective Pikachu",
    "link": "https://www.imdb.com/title/tt5884052/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Dr. Horrible's Sing-Along Blog",
    "link": "https://www.imdb.com/title/tt1227926/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "musical"],
  }, {
    "title": "Good Morning Vietnam",
    "link": "https://www.imdb.com/title/tt0093105/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Jojo Rabbit",
    "link": "https://www.imdb.com/title/tt2584384/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Joker",
    "link": "https://www.imdb.com/title/tt7286456/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Megamind",
    "link": "https://www.imdb.com/title/tt1001526/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "The Princess Bride",
    "link": "https://www.imdb.com/title/tt0093779/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Scott Pilgrim vs. the World",
    "link": "https://www.imdb.com/title/tt0446029/",
    "score": 7.5,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Sonic the Hedgehog",
    "link": "https://www.imdb.com/title/tt3794354/",
    "score": 5.5,
    "description": "Would probably have enjoyed it a lot more if I was around 10 when I watched it.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Spider-Man: Into the Spider-Verse",
    "link": "https://www.imdb.com/title/tt4633694/",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Spider-Man (2002)",
    "link": "https://www.imdb.com/title/tt0145487/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Spider-Man 2 (2004)",
    "link": "https://www.imdb.com/title/tt0316654/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Spider-Man 3 (2007)",
    "link": "https://www.imdb.com/title/tt0413300/",
    "score": 6,
    "description": "A golden star in the corner for the memes.",
    "tags": ["movie"],
  }, {
    "title": "Summer Wars",
    "link": "https://myanimelist.net/anime/5681/Summer_Wars",
    "score": 5,
    "description": "It would have been a 6.5-7 if the deus ex machina at the end didn't happen.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie", "anime"],
  }, {
    "title": "The Iron Giant",
    "link": "https://www.imdb.com/title/tt0129167/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "The Road to El Dorado",
    "link": "https://www.imdb.com/title/tt0138749/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie", "musical"],
  }, {
    "title": "We're Back! A Dinosaur's Story",
    "link": "https://www.imdb.com/title/tt0108526/",
    "score": 6,
    "description": "I liked it a lot as a kid, but as an adult it's not as great as I remember. The animation is fantastic though.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "The Colour of Magic",
    "link": "https://www.imdb.com/title/tt1079959/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Soul Music",
    "link": "https://www.imdb.com/title/tt0159914/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Hogfather",
    "link": "https://www.imdb.com/title/tt0765458/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Going Postal",
    "link": "https://www.imdb.com/title/tt1219817/",
    "score": 6.5,
    "tags": ["movie"],
  }, {
    "title": "Chicken Run",
    "link": "https://www.imdb.com/title/tt0120630/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Sorcerer's Stone",
    "link": "https://www.imdb.com/title/tt0241527/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Chamber of Secrets",
    "link": "https://www.imdb.com/title/tt0295297/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Prisoner of Azkaban",
    "link": "https://www.imdb.com/title/tt0304141/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Goblet of Fire",
    "link": "https://www.imdb.com/title/tt0330373/",
    "score": 5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Order of the Phoenix",
    "link": "https://www.imdb.com/title/tt0373889/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Half-Blood Prince",
    "link": "https://www.imdb.com/title/tt0417741/",
    "score": 6.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Deathly Hallows: Part 1",
    "link": "https://www.imdb.com/title/tt0926084/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Deathly Hallows: Part 2",
    "link": "https://www.imdb.com/title/tt1201607/",
    "score": 6.5,
    "tags": ["movie"],
  }, {
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "link": "https://www.imdb.com/title/tt0120737/",
    "score": 9.5,
    "tags": ["movie"],
  }, {
    "title": "The Lord of the Rings: The Two Towers",
    "link": "https://www.imdb.com/title/tt0167261/",
    "score": 9,
    "tags": ["movie"],
  }, {
    "title": "The Lord of the Rings: The Return of the King",
    "link": "https://www.imdb.com/title/tt0167260/",
    "score": 9.5,
    "tags": ["movie"],
  }, {
    "title": "My Neighbor Totoro",
    "link": "https://myanimelist.net/anime/523/Tonari_no_Totoro",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["movie", "anime"],
  }, {
    "title": "Carole & Tuesday",
    "link": "https://myanimelist.net/anime/37435/Carole___Tuesday",
    "score": 6.5,
    "description": `Music is great, and is used great. Writing is awkward at times, such as in the Not-American-Idol when they:
1) Play a pop song
2) Say 'We want to show you a different side of us'
3) Play a different kind of pop song`,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Attack on Titan",
    "link": "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin",
    "score": 7.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Death Note",
    "link": "https://myanimelist.net/anime/1535/Death_Note",
    "score": 8,
    "tags": ["show", "anime"],
  }, {
    "title": "Death Note (2017)",
    "link": "https://www.imdb.com/title/tt1241317/",
    "score": 3,
    "description": "It would be a 1.5 if it weren't for Willem Dafoe.",
    "tags": ["movie"],
  }, {
    "title": "Fullmetal Alchemist: Brotherhood",
    "link": "https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "JoJo's Bizarre Adventure",
    "link": "https://myanimelist.net/anime/14719/JoJo_no_Kimyou_na_Bouken_TV",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "description": "4 = 6 > 7 > 5 > 2 > 1 > 3. Haven't finished reading 8. 7 would be on top if it weren't for Love Train and after.",
    "tags": ["show", "anime"],
  }, {
    "title": "Hands off the Eizouken!",
    "link": "https://myanimelist.net/anime/39792/Eizouken_ni_wa_Te_wo_Dasu_na",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Neon Genesis Evangelion",
    "link": "https://myanimelist.net/anime/30/Neon_Genesis_Evangelion",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Devilman: Crybaby",
    "link": "https://myanimelist.net/anime/35120/Devilman__Crybaby",
    "score": 7.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Mob Psycho 100",
    "link": "https://myanimelist.net/anime/32182/Mob_Psycho_100",
    "score": 8.75,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "One Punch Man",
    "link": "https://myanimelist.net/anime/30276/One_Punch_Man",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Game of Thrones",
    "link": "https://www.imdb.com/title/tt0944947/",
    "score": 7,
    "description": "Starts out as a 9.5, slowly declines to a 5.5, then drops to a 3.5. About averages out to a 7.",
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Tengen Toppa Gurren Lagann",
    "link": "https://myanimelist.net/anime/2001/Tengen_Toppa_Gurren_Lagann",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Aqua Teen Hunger Force",
    "link": "https://www.imdb.com/title/tt0297494/",
    "score": 8.25,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Avatar: The Last Airbender",
    "link": "https://www.imdb.com/title/tt0417299/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "The Legend of Korra",
    "link": "https://www.imdb.com/title/tt0417299/",
    "score": 8,
    "description": "Book 1 > Book 3 > Book 4 > Book 2",
    "reviewed_at": "2020-07-25",
    "tags": ["show", "avatar"],
  }, {
    "title": "Firefly",
    "link": "https://www.imdb.com/title/tt0303461/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Futurama",
    "link": "https://www.imdb.com/title/tt0149460/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Star Wars: Episode I - The Phantom Menace",
    "link": "https://www.imdb.com/title/tt0120915/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode II - Attack of the Clones",
    "link": "https://www.imdb.com/title/tt0121765/",
    "score": 5,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode III - Revenge of the Sith",
    "link": "https://www.imdb.com/title/tt0121766/",
    "score": 6,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode IV - A New Hope",
    "link": "https://www.imdb.com/title/tt0076759/",
    "score": 8.5,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode V - The Empire Strikes Back",
    "link": "https://www.imdb.com/title/tt0080684/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode VI - Return of the Jedi",
    "link": "https://www.imdb.com/title/tt0086190/",
    "score": 9,
    "tags": ["movie"],
  }, {
    "title": "The Whitest Kids U'Know",
    "link": "https://www.imdb.com/title/tt0840979/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Ugly Americans",
    "link": "https://www.imdb.com/title/tt1621748/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "What We Do in the Shadows",
    "link": "https://www.imdb.com/title/tt3416742/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "What We Do in the Shadows",
    "link": "https://www.imdb.com/title/tt7908628/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Xavier: Renegade Angel",
    "link": "https://www.imdb.com/title/tt1132124/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "BoJack Horseman",
    "link": "https://www.imdb.com/title/tt3398228/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Breaking Bad",
    "link": "https://www.imdb.com/title/tt0903747/",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Mr. Robot",
    "link": "https://www.imdb.com/title/tt4158110/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Red Dwarf",
    "link": "https://www.imdb.com/title/tt0094535/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Silicon Valley",
    "link": "https://www.imdb.com/title/tt2575988/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "The Office (US)",
    "link": "https://www.imdb.com/title/tt0386676/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "The Office (UK)",
    "link": "https://www.imdb.com/title/tt0290978/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "How I Met Your Mother",
    "link": "https://www.imdb.com/title/tt0460649/",
    "score": 6.75,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Coco",
    "link": "https://www.imdb.com/title/tt2380307/",
    "score": 7,
    "reviewed_at": "2020-07-30",
    "tags": ["movie"],
  }, {
    "title": "Quest for Camelot",
    "link": "https://www.imdb.com/title/tt0120800/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Mrs. Doubtfire",
    "link": "https://www.imdb.com/title/tt0107614/",
    "score": 8,
    "reviewed_at": "2020-07-30",
    "tags": ["movie"],
  }, {
    "title": "Psych: The Movie",
    "link": "https://www.imdb.com/title/tt6868216/",
    "score": 8,
    "reviewed_at": "2020-08-01",
    "tags": ["movie"],
  }, {
    "title": "Psych 2: Lassie Come Home",
    "link": "https://www.imdb.com/title/tt9792884/",
    "score": 8,
    "reviewed_at": "2020-08-02",
    "tags": ["movie"],
  }, {
    "title": "Community",
    "link": "https://www.imdb.com/title/tt1439629/",
    "score": 8,
    "reviewed_at": "2020-08-24",
    "tags": ["show"],
  }, {
    "title": "Sweeney Todd: The Demon Barber of Fleet Street",
    "link": "https://www.imdb.com/title/tt0408236/",
    "score": 8,
    "reviewed_at": "2020-08-24",
    "tags": ["movie", "musical"],
  }, {
    "title": "Les Misérables",
    "link": "https://www.imdb.com/title/tt1707386/",
    "score": 9,
    "reviewed_at": "2020-08-24",
    "tags": ["movie", "musical"],
  }, {
    "title": "Mamma Mia!",
    "link": "https://www.imdb.com/title/tt0795421/",
    "score": 7,
    "reviewed_at": "2020-08-31",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Hunchback of Notre Dame",
    "link": "https://www.imdb.com/title/tt0116583/",
    "score": 8.75,
    "reviewed_at": "2020-09-01",
    "tags": ["movie", "musical"],
  }, {
    "title": "Grease",
    "link": "https://www.imdb.com/title/tt0077631/",
    "score": 7.5,
    "reviewed_at": "2020-09-02",
    "tags": ["movie", "musical"],
  }, {
    "title": "Annie (1982)",
    "link": "https://www.imdb.com/title/tt0083564/",
    "score": 8.5,
    "reviewed_at": "2020-09-02",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Rocky Horror Picture Show",
    "link": "https://www.imdb.com/title/tt0073629/",
    "score": 8,
    "reviewed_at": "2020-09-03",
    "tags": ["movie", "musical"],
  }, {
    "title": "Little Shop of Horrors",
    "link": "https://www.imdb.com/title/tt0091419/",
    "score": 8,
    "reviewed_at": "2020-09-04",
    "tags": ["movie", "musical"],
  }, {
    "title": "Rick and Morty",
    "link": "https://www.imdb.com/title/tt2861424/",
    "score": 7.5,
    "reviewed_at": "2020-09-10",
    "tags": ["show"],
  }, {
    "title": "Friends",
    "link": "https://www.imdb.com/title/tt0108778/",
    "score": 6,
    "reviewed_at": "2020-09-10",
    "tags": ["show"],
  }, {
    "title": "Arrested Development",
    "link": "https://www.imdb.com/title/tt0367279/",
    "score": 7.5,
    "reviewed_at": "2020-09-10",
    "tags": ["show"],
  }, {
    "title": "Hercules",
    "link": "https://www.imdb.com/title/tt0119282/",
    "score": 7,
    "reviewed_at": "2020-09-14",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Princess and the Frog",
    "link": "https://www.imdb.com/title/tt0780521/",
    "score": 7.5,
    "reviewed_at": "2020-09-14",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Lion King",
    "link": "https://www.imdb.com/title/tt0110357/",
    "score": 9,
    "reviewed_at": "2020-09-21",
    "tags": ["movie", "musical"],
  }, {
    "title": "Flyktingkrisen - en musikal",
    "link": "https://www.imdb.com/title/tt7593480/",
    "score": 8.5,
    "reviewed_at": "2020-09-21",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Greatest Showman",
    "link": "https://www.imdb.com/title/tt1485796/",
    "score": 9,
    "reviewed_at": "2020-09-23",
    "tags": ["movie", "musical"],
  }, {
    "title": "Brooklyn Nine-Nine",
    "link": "https://www.imdb.com/title/tt2467372/",
    "score": 8,
    "reviewed_at": "2020-09-26",
    "tags": ["show"],
  }, {
    "title": "Cube",
    "link": "https://www.imdb.com/title/tt0123755/",
    "score": 8,
    "reviewed_at": "2020-10-16",
    "tags": ["movie"],
  }, {
    "title": "Modern Family",
    "link": "https://www.imdb.com/title/tt1442437/",
    "score": 8,
    "reviewed_at": "2020-10-23",
    "tags": ["show"],
  }, {
    "title": "Stranger Things",
    "link": "https://www.imdb.com/title/tt4574334/",
    "score": 7,
    "reviewed_at": "2020-10-23",
    "tags": ["show"],
  }, {
    "title": "Galavant",
    "link": "https://www.imdb.com/title/tt3305096/",
    "score": 9.5,
    "description": "Season 3 when? >:(",
    "reviewed_at": "2020-10-23",
    "tags": ["show", "musical"],
  }, {
    "title": "Alien",
    "link": "https://www.imdb.com/title/tt0078748/",
    "score": 8.25,
    "reviewed_at": "2020-10-24",
    "tags": ["movie"],
  }, {
    "title": "Grave of the Fireflies",
    "link": "https://myanimelist.net/anime/578/Hotaru_no_Haka",
    "score": 8.75,
    "reviewed_at": "2020-10-27",
    "tags": ["movie", "anime"],
  }, {
    "title": "The Nightmare Before Christmas",
    "link": "https://www.imdb.com/title/tt0107688/",
    "score": 8.5,
    "reviewed_at": "2020-10-31",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Big Bang Theory",
    "link": "https://www.imdb.com/title/tt0898266/",
    "score": 5.75,
    "reviewed_at": "2020-12-16",
    "tags": ["show"],
  }, {
    "title": "Attaway General",
    "link": "https://www.imdb.com/title/tt11766306/",
    "score": 0.75,
    "description": "What the fuck is wrong with you",
    "reviewed_at": "2020-12-16",
    "tags": ["show"],
  }, {
    "title": "Crazy Rich Asians",
    "link": "https://www.imdb.com/title/tt3104988/",
    "score": 5.75,
    "reviewed_at": "2020-12-25",
    "tags": ["movie"],
  }, {
    "title": "The Mandalorian",
    "link": "https://www.imdb.com/title/tt8111088/",
    "score": 7.5,
    "reviewed_at": "2020-12-25",
    "tags": ["show"],
  }, {
    "title": "National Lampoon's Christmas Vacation",
    "link": "https://www.imdb.com/title/tt0097958/",
    "score": 5.75,
    "reviewed_at": "2020-12-25",
    "tags": ["movie"],
  }, {
    "title": "The Good Place",
    "link": "https://www.imdb.com/title/tt4955642/",
    "score": 7,
    "reviewed_at": "2020-12-25",
    "tags": ["show"],
  }, {
    "title": "Coraline",
    "link": "https://www.imdb.com/title/tt0327597/",
    "score": 7.5,
    "reviewed_at": "2020-12-25",
    "tags": ["movie"],
  }, {
    "title": "Zombieland",
    "link": "https://www.imdb.com/title/tt1156398/",
    "score": 7,
    "reviewed_at": "2020-12-26",
    "tags": ["movie"],
  }, {
    "title": "Zombieland: Double Tap",
    "link": "https://www.imdb.com/title/tt1560220/",
    "score": 6.75,
    "reviewed_at": "2020-12-26",
    "tags": ["movie"],
  }, {
    "title": "Peep Show",
    "link": "https://www.imdb.com/title/tt0387764/",
    "score": 8.5,
    "reviewed_at": "2020-12-30",
    "tags": ["show"],
  }, {
    "title": "Wonder Showzen",
    "link": "https://www.imdb.com/title/tt0450357/",
    "score": 8.75,
    "reviewed_at": "2021-01-02",
    "tags": ["show"],
  }, {
    "title": "Beastars",
    "link": "https://myanimelist.net/anime/39195/Beastars",
    "score": 8,
    "reviewed_at": "2021-01-26",
    "tags": ["show", "anime"],
  }, {
    "title": "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
    "link": "https://www.imdb.com/title/tt0443453/",
    "score": 7.25,
    "reviewed_at": "2021-01-30",
    "tags": ["movie"],
  }, {
    "title": "Soul",
    "link": "https://www.imdb.com/title/tt2948372/",
    "score": 8,
    "reviewed_at": "2021-02-01",
    "tags": ["movie"],
  }, {
    "title": "Time Bandits",
    "link": "https://www.imdb.com/title/tt0081633/",
    "score": 6,
    "reviewed_at": "2021-02-12",
    "tags": ["movie"],
  }, {
    "title": "Blade Runner 2049",
    "link": "https://www.imdb.com/title/tt1856101/",
    "score": 9,
    "reviewed_at": "2021-02-16",
    "tags": ["movie"],
  }, {
    "title": "X-Men 2",
    "link": "https://www.imdb.com/title/tt0290334/",
    "score": 5,
    "reviewed_at": "2021-02-20",
    "tags": ["movie"],
  }, {
    "title": "Kingsman: The Secret Service",
    "link": "https://www.imdb.com/title/tt2802144/",
    "score": 7.75,
    "reviewed_at": "2021-02-21",
    "tags": ["movie"],
  }, {
    "title": "Kingsman: The Golden Circle",
    "link": "https://www.imdb.com/title/tt4649466/",
    "score": 6,
    "reviewed_at": "2021-02-21",
    "tags": ["movie"],
  }, {
    "title": "Upstart Crow",
    "link": "https://www.imdb.com/title/tt4793190/",
    "score": 7,
    "reviewed_at": "2021-02-23",
    "tags": ["show"],
  }, {
    "title": "West Side Story",
    "link": "https://www.imdb.com/title/tt0055614/",
    "score": 8,
    "reviewed_at": "2021-02-28",
    "tags": ["movie", "musical"],
  }, {
    "title": "Enchanted",
    "link": "https://www.imdb.com/title/tt0461770/",
    "score": 6,
    "reviewed_at": "2021-02-28",
    "tags": ["movie", "musical"],
  }, {
    "title": "Nathan for You",
    "link": "https://www.imdb.com/title/tt2297757/",
    "score": 9,
    "reviewed_at": "2021-03-01",
    "tags": ["show"],
  }, {
    "title": "Drive",
    "link": "https://www.imdb.com/title/tt0780504/",
    "score": 6.5,
    "reviewed_at": "2021-03-02",
    "tags": ["movie"],
  }, {
    "title": "South Park: Bigger, Longer & Uncut",
    "link": "https://www.imdb.com/title/tt0158983/",
    "score": 8,
    "reviewed_at": "2021-03-07",
    "tags": ["movie", "musical"],
  }, {
    "title": "WandaVision",
    "link": "https://www.imdb.com/title/tt9140560/",
    "score": 7,
    "reviewed_at": "2021-03-13",
    "tags": ["show"],
  }, {
    "title": "Shazam!",
    "link": "https://www.imdb.com/title/tt0448115/",
    "score": 7,
    "reviewed_at": "2021-03-19",
    "tags": ["movie"],
  }, {
    "title": "The Italian Job",
    "link": "https://www.imdb.com/title/tt0317740/",
    "score": 6.75,
    "reviewed_at": "2021-03-20",
    "tags": ["movie"],
  }, {
    "title": "The Hitman's Bodyguard",
    "link": "https://www.imdb.com/title/tt1959563/",
    "score": 6.5,
    "reviewed_at": "2021-03-21",
    "tags": ["movie"],
  }, {
    "title": "DuckTales",
    "link": "https://www.imdb.com/title/tt5531466/",
    "score": 9,
    "reviewed_at": "2021-03-24",
    "tags": ["show"],
  }, {
    "title": "Captain Marvel",
    "link": "https://www.imdb.com/title/tt4154664/",
    "score": 5.75,
    "reviewed_at": "2021-03-24",
    "tags": ["movie"],
  }, {
    "title": "Archer",
    "link": "https://www.imdb.com/title/tt1486217/",
    "score": 8,
    "reviewed_at": "2021-03-31",
    "tags": ["show"],
  }, {
    "title": "Dead Poets Society",
    "link": "https://www.imdb.com/title/tt0097165/",
    "score": 8.5,
    "reviewed_at": "2021-04-11",
    "tags": ["movie"],
  }, {
    "title": "Hamilton",
    "link": "https://www.imdb.com/title/tt8503618/",
    "score": 9.5,
    "reviewed_at": "2021-04-19",
    "tags": ["movie", "musical"],
  }, {
    "title": "Fiddler on the Roof",
    "link": "https://www.imdb.com/title/tt0067093/",
    "score": 8.25,
    "reviewed_at": "2021-04-20",
    "tags": ["movie", "musical"],
  }, {
    "title": "La La Land",
    "link": "https://www.imdb.com/title/tt3783958/",
    "score": 7,
    "reviewed_at": "2021-04-23",
    "tags": ["movie", "musical"],
  }, {
    "title": "Dips",
    "link": "https://www.imdb.com/title/tt9499182/",
    "score": 7.75,
    "reviewed_at": "2021-04-24",
    "tags": ["show"],
  }, {
    "title": "The Goonies",
    "link": "https://www.imdb.com/title/tt0089218/",
    "score": 7.75,
    "reviewed_at": "2021-04-24",
    "tags": ["movie"],
  }, {
    "title": "Moana",
    "link": "https://www.imdb.com/title/tt3521164/",
    "score": 8.5,
    "reviewed_at": "2021-04-25",
    "tags": ["movie", "musical"],
  }, {
    "title": "American Psycho",
    "link": "https://www.imdb.com/title/tt0144084/",
    "score": 8,
    "reviewed_at": "2021-04-25",
    "tags": ["movie"],
  }, {
    "title": "The Falcon and the Winter Soldier",
    "link": "https://www.imdb.com/title/tt9208876/",
    "score": 5.5,
    "reviewed_at": "2021-04-27",
    "tags": ["show"],
  }, {
    "title": "Tenacious D in The Pick of Destiny",
    "link": "https://www.imdb.com/title/tt0365830/",
    "score": 7,
    "reviewed_at": "2021-05-02",
    "tags": ["movie"],
  }, {
    "title": "Knives Out",
    "link": "https://www.imdb.com/title/tt8946378/",
    "score": 8,
    "reviewed_at": "2021-05-05",
    "tags": ["movie"],
  }, {
    "title": "Legend",
    "link": "https://www.imdb.com/title/tt3569230/",
    "score": 7,
    "reviewed_at": "2021-05-08",
    "tags": ["movie"],
  }, {
    "title": "Invincible",
    "link": "https://www.imdb.com/title/tt6741278/",
    "score": 8,
    "reviewed_at": "2021-05-16",
    "tags": ["show"],
  }, {
    "title": "The Black Adder",
    "link": "https://www.imdb.com/title/tt0084988/",
    "score": 8.25,
    "description": `1: 7
2: 8.5
3: 8
4: 8
Christmas Carol: 8
Cavalier Years: 8
Back & Forth: 8`,
    "reviewed_at": "2021-05-24",
    "tags": ["show"],
  }, {
    "title": "The Inbetweeners",
    "link": "https://www.imdb.com/title/tt1220617/",
    "score": 8,
    "reviewed_at": "2021-05-26",
    "tags": ["show"],
  }, {
    "title": "The Inbetweeners",
    "link": "https://www.imdb.com/title/tt1716772/",
    "score": 8,
    "reviewed_at": "2021-05-26",
    "tags": ["movie"],
  }, {
    "title": "The Inbetweeners 2",
    "link": "https://www.imdb.com/title/tt3097204/",
    "score": 6,
    "reviewed_at": "2021-05-26",
    "tags": ["movie"],
  }, {
    "title": "Back",
    "link": "https://www.imdb.com/title/tt5676590/",
    "score": 8,
    "reviewed_at": "2021-05-29",
    "tags": ["show"],
  }, {
    "title": "The Secret Life of Walter Mitty",
    "link": "https://www.imdb.com/title/tt0359950/",
    "score": 9,
    "reviewed_at": "2021-05-30",
    "tags": ["movie"],
  }, {
    "title": "Falling Down",
    "link": "https://www.imdb.com/title/tt0106856/",
    "score": 7,
    "reviewed_at": "2021-06-01",
    "tags": ["movie"],
  }, {
    "title": "The Florida Project",
    "link": "https://www.imdb.com/title/tt5649144/",
    "score": 8,
    "reviewed_at": "2021-06-06",
    "tags": ["movie"],
  }, {
    "title": "Guns Akimbo",
    "link": "https://www.imdb.com/title/tt6902676/",
    "score": 6,
    "reviewed_at": "2021-06-06",
    "tags": ["movie"],
  }, {
    "title": "Napoleon Dynamite",
    "link": "https://www.imdb.com/title/tt0374900/",
    "score": 8,
    "reviewed_at": "2021-06-12",
    "tags": ["movie"],
  }, {
    "title": "In the Heights",
    "link": "https://www.imdb.com/title/tt1321510/",
    "score": 9,
    "reviewed_at": "2021-06-12",
    "tags": ["movie", "musical"],
  }, {
    "title": "Blazing Saddles",
    "link": "https://www.imdb.com/title/tt0071230/",
    "score": 7,
    "reviewed_at": "2021-06-13",
    "tags": ["movie"],
  }, {
    "title": "Bad Boys for Life",
    "link": "https://www.imdb.com/title/tt1502397/",
    "score": 6,
    "reviewed_at": "2021-06-19",
    "tags": ["movie"],
  }, {
    "title": "That Mitchell and Webb Look",
    "link": "https://www.imdb.com/title/tt0499410/",
    "score": 8,
    "reviewed_at": "2021-07-01",
    "tags": ["show"],
  }, {
    "title": "Guys and Dolls",
    "link": "https://www.imdb.com/title/tt0048140/",
    "score": 7,
    "reviewed_at": "2021-07-02",
    "tags": ["movie", "musical"],
  }, {
    "title": "It's Always Sunny in Philadelphia",
    "link": "https://www.imdb.com/title/tt0472954/",
    "score": 9.5,
    "reviewed_at": "2021-07-04",
    "tags": ["show"],
  }, {
    "title": "Mythic Quest: Raven's Banquet",
    "link": "https://www.imdb.com/title/tt8879940/",
    "score": 8.5,
    "reviewed_at": "2021-07-07",
    "tags": ["show"],
  }, {
    "title": "Highlander",
    "link": "https://www.imdb.com/title/tt0091203/",
    "score": 6.75,
    "reviewed_at": "2021-07-07",
    "tags": ["movie"],
  }, {
    "title": "Kill Me Three Times",
    "link": "https://www.imdb.com/title/tt2393845/",
    "score": 6,
    "reviewed_at": "2021-07-14",
    "tags": ["movie"],
  }, {
    "title": "Tinker Tailor Soldier Spy",
    "link": "https://www.imdb.com/title/tt1340800/",
    "score": 7,
    "reviewed_at": "2021-07-15",
    "tags": ["movie"],
  }, {
    "title": "Instant Family",
    "link": "https://www.imdb.com/title/tt7401588/",
    "score": 7.5,
    "reviewed_at": "2021-07-16",
    "tags": ["movie"],
  }, {
    "title": "Odd Taxi",
    "link": "https://myanimelist.net/anime/46102/Odd_Taxi",
    "score": 9,
    "reviewed_at": "2021-08-03",
    "tags": ["show", "anime"],
  }, {
    "title": "Bo Burnham: Inside",
    "link": "https://www.imdb.com/title/tt14544192/",
    "score": 8.75,
    "reviewed_at": "2021-08-03",
    "tags": ["movie"],
  }, {
    "title": "The Suicide Squad",
    "link": "https://www.imdb.com/title/tt6334354/",
    "score": 6.75,
    "reviewed_at": "2021-08-11",
    "tags": ["movie"],
  }, {
    "title": "Shot Caller",
    "link": "https://www.imdb.com/title/tt4633690/",
    "score": 5.5,
    "reviewed_at": "2021-10-02",
    "tags": ["movie"],
  }, {
    "title": "The Captive",
    "link": "https://www.imdb.com/title/tt2326612/",
    "score": 4,
    "reviewed_at": "2021-10-07",
    "tags": ["movie"],
  }, {
    "title": "Z for Zachariah",
    "link": "https://www.imdb.com/title/tt1598642/",
    "score": 3.5,
    "reviewed_at": "2021-10-08",
    "tags": ["movie"],
  }, {
    "title": "Squid Game",
    "link": "https://www.imdb.com/title/tt10919420/",
    "score": 8,
    "reviewed_at": "2021-10-14",
    "tags": ["show"],
  }, {
    "title": "Child 44",
    "link": "https://www.imdb.com/title/tt1014763/",
    "score": 6.5,
    "reviewed_at": "2021-10-29",
    "tags": ["movie"],
  }, {
    "title": "Motherless Brooklyn",
    "link": "https://www.imdb.com/title/tt0385887/",
    "score": 6.5,
    "reviewed_at": "2021-10-30",
    "tags": ["movie"],
  }, {
    "title": "Stargate SG-1",
    "link": "https://www.imdb.com/title/tt0118480/",
    "score": 9,
    "description": "While it definitely didn't dip in quality when Richard Dean Anderson left, I did start enjoying it less. Probably because I associate the show with the original team so closely.",
    "reviewed_at": "2021-11-24",
    "tags": ["show"],
  }, {
    "title": "Stargate: The Ark of Truth",
    "link": "https://www.imdb.com/title/tt0118480/",
    "score": 7.5,
    "description": "While it wraps up the Ori storyline well, I feel it tarnishes the last episode of the show a bit.",
    "reviewed_at": "2021-11-26",
    "tags": ["movie"],
  }, {
    "title": "Amnesia: The Dark Descent",
    "link": "https://www.gog.com/game/amnesia_the_dark_descent",
    "score": 7,
    "description": "lmao pewdiepie barrels amirite",
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Audiosurf",
    "link": "https://store.steampowered.com/app/12900/AudioSurf/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Bastion",
    "link": "https://www.gog.com/game/bastion",
    "score": 9,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Assassin's Creed II",
    "link": "https://store.steampowered.com/app/33230/Assassins_Creed_2/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Dishonored",
    "link": "https://www.gog.com/game/dishonored_definitive_edition",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Trine 2: Complete Story",
    "link": "https://www.gog.com/game/trine_2_complete_story",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Borderlands 2",
    "link": "https://store.steampowered.com/app/49520/Borderlands_2/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "The Elder Scrolls V: Skyrim",
    "link": "https://store.steampowered.com/app/72850/The_Elder_Scrolls_V_Skyrim/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "FTL",
    "link": "https://www.gog.com/game/faster_than_light",
    "score": 6,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Antichamber",
    "link": "https://store.steampowered.com/app/219890/Antichamber/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Proteus",
    "link": "https://store.steampowered.com/app/219680/Proteus/",
    "score": 8,
    "reviewed_at": "2021-12-03",
    "description": "Just incredibly relaxing.",
    "tags": ["game"],
  }, {
    "title": "Brothers: A Tale of Two Sons",
    "link": "https://www.gog.com/game/brothers_a_tale_of_two_sons",
    "score": 8,
    "reviewed_at": "2021-12-03",
    "description": "Nice use of gameplay mechanics to tell the story.",
    "tags": ["game"],
  }, {
    "title": "Fallout 4",
    "link": "https://store.steampowered.com/app/377160/Fallout_4/",
    "score": 6.5,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Wandersong",
    "link": "https://www.gog.com/game/wandersong",
    "score": 9.5,
    "description": "Nothing amazingly groundbreaking, but it does what it sets out to do, and does it well. I would personally have done the ending a bit differently (as you can see here: https://thenamlessguy.github.io/rants/my-wandersong-ending.html), but it's still one of my favorite games.",
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Stars Die",
    "link": "https://store.steampowered.com/app/1457740/Stars_Die/",
    "score": 8,
    "description": "Very much gives me the same feeling as when I read Lovecraft. Captures the cosmic horror vibes fantastically, without just jerking off Lovecraft's dead dongler.",
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Heaven's Vault",
    "link": "https://www.gog.com/game/heavens_vault",
    "score": 9,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "The Elder Scrolls III: Morrowind",
    "link": "https://www.gog.com/game/the_elder_scrolls_iii_morrowind_goty_edition",
    "score": 8.5,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "The Elder Scrolls IV: Oblivion",
    "link": "https://www.gog.com/game/elder_scrolls_iv_oblivion_game_of_the_year_edition_deluxe_the",
    "score": 9,
    "description": `The perfect balance between the depth in Morrowind and the simplicity of Skyrim.
Only thing I would really change is the leveling system, as I feel only leveling up from your major skills is kind of boring.
Instead, make it so any skill under 25 gives you a debuff for everything to do with it, have your major skills start at 25, and make it so you level up from all skills.

Maybe fix the difficulty curve as well. Did Battle of Kvatch at level 14 or something, and I just flat out couldn't beat it with my character build.`,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Inscryption",
    "link": "https://www.gog.com/game/inscryption",
    "score": 8,
    "reviewed_at": "2021-12-03",
    "description": "While I didn't follow the ARG aspect of the game, I did still immensely enjoy the game itself. Go in blind if you haven't played it.",
    "tags": ["game"],
  }]
};