const _raw_data = {
  "items": [{
    "title": "Avatar (2009)",
    "link": "https://www.imdb.com/title/tt0499549/",
    "score": 5,
    "description": "It's impressive how mediocre this was.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Mary & Max",
    "link": "https://www.imdb.com/title/tt0978762/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Scrubs",
    "link": "https://www.imdb.com/title/tt0285403/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Psych",
    "link": "https://www.imdb.com/title/tt0491738/",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Alita: Battle Angel",
    "link": "https://www.imdb.com/title/tt0437086/",
    "score": 5.5,
    "description": "I haven't seen the anime, but even just watching this I feel like I'm missing out on a lot.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Big Hero 6",
    "link": "https://www.imdb.com/title/tt2245084/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Atlantis: The Lost Empire",
    "link": "https://www.imdb.com/title/tt0230011/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Bruce Almighty",
    "link": "https://www.imdb.com/title/tt0315327/",
    "score": 6.5,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Pokémon: Detective Pikachu",
    "link": "https://www.imdb.com/title/tt5884052/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Dr. Horrible's Sing-Along Blog",
    "link": "https://www.imdb.com/title/tt1227926/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "musical"],
  }, {
    "title": "Good Morning Vietnam",
    "link": "https://www.imdb.com/title/tt0093105/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Jojo Rabbit",
    "link": "https://www.imdb.com/title/tt2584384/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Joker",
    "link": "https://www.imdb.com/title/tt7286456/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Megamind",
    "link": "https://www.imdb.com/title/tt1001526/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "The Princess Bride",
    "link": "https://www.imdb.com/title/tt0093779/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Sonic the Hedgehog",
    "link": "https://www.imdb.com/title/tt3794354/",
    "score": 5.5,
    "description": "Would probably have enjoyed it a lot more if I was around 10 when I watched it.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Spider-Man: Into the Spider-Verse",
    "link": "https://www.imdb.com/title/tt4633694/",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "Spider-Man (2002)",
    "link": "https://www.imdb.com/title/tt0145487/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Spider-Man 2 (2004)",
    "link": "https://www.imdb.com/title/tt0316654/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Spider-Man 3 (2007)",
    "link": "https://www.imdb.com/title/tt0413300/",
    "score": 6,
    "description": "A golden star in the corner for the memes.",
    "tags": ["movie"],
  }, {
    "title": "Summer Wars",
    "link": "https://myanimelist.net/anime/5681/Summer_Wars",
    "score": 5,
    "description": "It would have been a 6.5-7 if the deus ex machina at the end didn't happen.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie", "anime"],
  }, {
    "title": "The Iron Giant",
    "link": "https://www.imdb.com/title/tt0129167/",
    "score": 6,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "The Road to El Dorado",
    "link": "https://www.imdb.com/title/tt0138749/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["movie", "musical"],
  }, {
    "title": "We're Back! A Dinosaur's Story",
    "link": "https://www.imdb.com/title/tt0108526/",
    "score": 6,
    "description": "I liked it a lot as a kid, but as an adult it's not as great as I remember. The animation is fantastic though.",
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "The Colour of Magic",
    "link": "https://www.imdb.com/title/tt1079959/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Soul Music",
    "link": "https://www.imdb.com/title/tt0159914/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Hogfather",
    "link": "https://www.imdb.com/title/tt0765458/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Going Postal",
    "link": "https://www.imdb.com/title/tt1219817/",
    "score": 6.5,
    "tags": ["movie"],
  }, {
    "title": "Chicken Run",
    "link": "https://www.imdb.com/title/tt0120630/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Sorcerer's Stone",
    "link": "https://www.imdb.com/title/tt0241527/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Chamber of Secrets",
    "link": "https://www.imdb.com/title/tt0295297/",
    "score": 7.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Prisoner of Azkaban",
    "link": "https://www.imdb.com/title/tt0304141/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Goblet of Fire",
    "link": "https://www.imdb.com/title/tt0330373/",
    "score": 5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Order of the Phoenix",
    "link": "https://www.imdb.com/title/tt0373889/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Half-Blood Prince",
    "link": "https://www.imdb.com/title/tt0417741/",
    "score": 6.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Deathly Hallows: Part 1",
    "link": "https://www.imdb.com/title/tt0926084/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Harry Potter and the Deathly Hallows: Part 2",
    "link": "https://www.imdb.com/title/tt1201607/",
    "score": 6.5,
    "tags": ["movie"],
  }, {
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "link": "https://www.imdb.com/title/tt0120737/",
    "score": 9.5,
    "tags": ["movie"],
  }, {
    "title": "The Lord of the Rings: The Two Towers",
    "link": "https://www.imdb.com/title/tt0167261/",
    "score": 9,
    "tags": ["movie"],
  }, {
    "title": "The Lord of the Rings: The Return of the King",
    "link": "https://www.imdb.com/title/tt0167260/",
    "score": 9.5,
    "tags": ["movie"],
  }, {
    "title": "My Neighbor Totoro",
    "link": "https://myanimelist.net/anime/523/Tonari_no_Totoro",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["movie", "anime"],
  }, {
    "title": "Carole & Tuesday",
    "link": "https://myanimelist.net/anime/37435/Carole___Tuesday",
    "score": 6.5,
    "description": `Music is great, and is used great. Writing is awkward at times, such as in the Not-American-Idol when they:
1) Play a pop song
2) Say 'We want to show you a different side of us'
3) Play a different kind of pop song`,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Attack on Titan",
    "link": "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin",
    "score": 8.5,
    "reviewed_at": "2021-12-04",
    "tags": ["show", "anime"],
  }, {
    "title": "Death Note",
    "link": "https://myanimelist.net/anime/1535/Death_Note",
    "score": 8,
    "tags": ["show", "anime"],
  }, {
    "title": "Death Note (2017)",
    "link": "https://www.imdb.com/title/tt1241317/",
    "score": 3,
    "description": "It would be a 1.5 if it weren't for Willem Dafoe.",
    "tags": ["movie"],
  }, {
    "title": "Fullmetal Alchemist: Brotherhood",
    "link": "https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "JoJo's Bizarre Adventure",
    "link": "https://myanimelist.net/anime/14719/JoJo_no_Kimyou_na_Bouken_TV",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "description": "4 = 6 > 7 > 5 > 2 > 1 > 3. Haven't finished reading 8. 7 would be on top if it weren't for Love Train and after.",
    "tags": ["show", "anime"],
  }, {
    "title": "Hands off the Eizouken!",
    "link": "https://myanimelist.net/anime/39792/Eizouken_ni_wa_Te_wo_Dasu_na",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Neon Genesis Evangelion",
    "link": "https://myanimelist.net/anime/30/Neon_Genesis_Evangelion",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Devilman: Crybaby",
    "link": "https://myanimelist.net/anime/35120/Devilman__Crybaby",
    "score": 7.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Mob Psycho 100",
    "link": "https://myanimelist.net/anime/32182/Mob_Psycho_100",
    "score": 8.75,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "One Punch Man",
    "link": "https://myanimelist.net/anime/30276/One_Punch_Man",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Game of Thrones",
    "link": "https://www.imdb.com/title/tt0944947/",
    "score": 7,
    "description": "Starts out as a 9.5, slowly declines to a 5.5, then drops to a 3.5. About averages out to a 7.",
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Tengen Toppa Gurren Lagann",
    "link": "https://myanimelist.net/anime/2001/Tengen_Toppa_Gurren_Lagann",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show", "anime"],
  }, {
    "title": "Aqua Teen Hunger Force",
    "link": "https://www.imdb.com/title/tt0297494/",
    "score": 8.25,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Avatar: The Last Airbender",
    "link": "https://www.imdb.com/title/tt0417299/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "The Legend of Korra",
    "link": "https://www.imdb.com/title/tt0417299/",
    "score": 8,
    "description": "Book 1 > Book 3 > Book 4 > Book 2",
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Firefly",
    "link": "https://www.imdb.com/title/tt0303461/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Futurama",
    "link": "https://www.imdb.com/title/tt0149460/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Star Wars: Episode I - The Phantom Menace",
    "link": "https://www.imdb.com/title/tt0120915/",
    "score": 5.5,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode II - Attack of the Clones",
    "link": "https://www.imdb.com/title/tt0121765/",
    "score": 5,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode III - Revenge of the Sith",
    "link": "https://www.imdb.com/title/tt0121766/",
    "score": 6,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode IV - A New Hope",
    "link": "https://www.imdb.com/title/tt0076759/",
    "score": 8.5,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode V - The Empire Strikes Back",
    "link": "https://www.imdb.com/title/tt0080684/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Star Wars: Episode VI - Return of the Jedi",
    "link": "https://www.imdb.com/title/tt0086190/",
    "score": 9,
    "tags": ["movie"],
  }, {
    "title": "The Whitest Kids U'Know",
    "link": "https://www.imdb.com/title/tt0840979/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Ugly Americans",
    "link": "https://www.imdb.com/title/tt1621748/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "What We Do in the Shadows",
    "link": "https://www.imdb.com/title/tt3416742/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["movie"],
  }, {
    "title": "What We Do in the Shadows",
    "link": "https://www.imdb.com/title/tt7908628/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Xavier: Renegade Angel",
    "link": "https://www.imdb.com/title/tt1132124/",
    "score": 9,
    "reviewed_at": "2021-12-05",
    "tags": ["show"],
  }, {
    "title": "BoJack Horseman",
    "link": "https://www.imdb.com/title/tt3398228/",
    "score": 9.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Breaking Bad",
    "link": "https://www.imdb.com/title/tt0903747/",
    "score": 9,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Mr. Robot",
    "link": "https://www.imdb.com/title/tt4158110/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Red Dwarf",
    "link": "https://www.imdb.com/title/tt0094535/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Silicon Valley",
    "link": "https://www.imdb.com/title/tt2575988/",
    "score": 7,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "The Office (US)",
    "link": "https://www.imdb.com/title/tt0386676/",
    "score": 8.5,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "The Office (UK)",
    "link": "https://www.imdb.com/title/tt0290978/",
    "score": 8,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "How I Met Your Mother",
    "link": "https://www.imdb.com/title/tt0460649/",
    "score": 6.75,
    "reviewed_at": "2020-07-25",
    "tags": ["show"],
  }, {
    "title": "Coco",
    "link": "https://www.imdb.com/title/tt2380307/",
    "score": 7,
    "reviewed_at": "2020-07-30",
    "tags": ["movie"],
  }, {
    "title": "Quest for Camelot",
    "link": "https://www.imdb.com/title/tt0120800/",
    "score": 7,
    "tags": ["movie"],
  }, {
    "title": "Mrs. Doubtfire",
    "link": "https://www.imdb.com/title/tt0107614/",
    "score": 8,
    "reviewed_at": "2020-07-30",
    "tags": ["movie"],
  }, {
    "title": "Psych: The Movie",
    "link": "https://www.imdb.com/title/tt6868216/",
    "score": 8,
    "reviewed_at": "2020-08-01",
    "tags": ["movie"],
  }, {
    "title": "Psych 2: Lassie Come Home",
    "link": "https://www.imdb.com/title/tt9792884/",
    "score": 8,
    "reviewed_at": "2020-08-02",
    "tags": ["movie"],
  }, {
    "title": "Community",
    "link": "https://www.imdb.com/title/tt1439629/",
    "score": 8,
    "reviewed_at": "2020-08-24",
    "tags": ["show"],
  }, {
    "title": "Sweeney Todd: The Demon Barber of Fleet Street",
    "link": "https://www.imdb.com/title/tt0408236/",
    "score": 8,
    "reviewed_at": "2020-08-24",
    "tags": ["movie", "musical"],
  }, {
    "title": "Les Misérables",
    "link": "https://www.imdb.com/title/tt1707386/",
    "score": 9,
    "reviewed_at": "2020-08-24",
    "tags": ["movie", "musical"],
  }, {
    "title": "Mamma Mia!",
    "link": "https://www.imdb.com/title/tt0795421/",
    "score": 7,
    "reviewed_at": "2020-08-31",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Hunchback of Notre Dame",
    "link": "https://www.imdb.com/title/tt0116583/",
    "score": 8.75,
    "reviewed_at": "2020-09-01",
    "tags": ["movie", "musical"],
  }, {
    "title": "Grease",
    "link": "https://www.imdb.com/title/tt0077631/",
    "score": 7.5,
    "reviewed_at": "2020-09-02",
    "tags": ["movie", "musical"],
  }, {
    "title": "Annie (1982)",
    "link": "https://www.imdb.com/title/tt0083564/",
    "score": 8.5,
    "reviewed_at": "2020-09-02",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Rocky Horror Picture Show",
    "link": "https://www.imdb.com/title/tt0073629/",
    "score": 8,
    "reviewed_at": "2020-09-03",
    "tags": ["movie", "musical"],
  }, {
    "title": "Little Shop of Horrors",
    "link": "https://www.imdb.com/title/tt0091419/",
    "score": 8,
    "reviewed_at": "2020-09-04",
    "tags": ["movie", "musical"],
  }, {
    "title": "Rick and Morty",
    "link": "https://www.imdb.com/title/tt2861424/",
    "score": 7.5,
    "reviewed_at": "2020-09-10",
    "tags": ["show"],
  }, {
    "title": "Friends",
    "link": "https://www.imdb.com/title/tt0108778/",
    "score": 6,
    "reviewed_at": "2020-09-10",
    "tags": ["show"],
  }, {
    "title": "Arrested Development",
    "link": "https://www.imdb.com/title/tt0367279/",
    "score": 7.5,
    "reviewed_at": "2020-09-10",
    "tags": ["show"],
  }, {
    "title": "Hercules",
    "link": "https://www.imdb.com/title/tt0119282/",
    "score": 7,
    "reviewed_at": "2020-09-14",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Princess and the Frog",
    "link": "https://www.imdb.com/title/tt0780521/",
    "score": 7.5,
    "reviewed_at": "2020-09-14",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Lion King",
    "link": "https://www.imdb.com/title/tt0110357/",
    "score": 9,
    "reviewed_at": "2020-09-21",
    "tags": ["movie", "musical"],
  }, {
    "title": "Flyktingkrisen - en musikal",
    "link": "https://www.imdb.com/title/tt7593480/",
    "score": 8.5,
    "reviewed_at": "2020-09-21",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Greatest Showman",
    "link": "https://www.imdb.com/title/tt1485796/",
    "score": 9,
    "reviewed_at": "2020-09-23",
    "tags": ["movie", "musical"],
  }, {
    "title": "Brooklyn Nine-Nine",
    "link": "https://www.imdb.com/title/tt2467372/",
    "score": 8,
    "reviewed_at": "2022-10-15",
    "tags": ["show"],
  }, {
    "title": "Cube",
    "link": "https://www.imdb.com/title/tt0123755/",
    "score": 8,
    "reviewed_at": "2020-10-16",
    "tags": ["movie"],
  }, {
    "title": "Modern Family",
    "link": "https://www.imdb.com/title/tt1442437/",
    "score": 8,
    "reviewed_at": "2020-10-23",
    "tags": ["show"],
  }, {
    "title": "Stranger Things",
    "link": "https://www.imdb.com/title/tt4574334/",
    "score": 7,
    "reviewed_at": "2020-10-23",
    "tags": ["show"],
  }, {
    "title": "Galavant",
    "link": "https://www.imdb.com/title/tt3305096/",
    "score": 9.5,
    "description": "Season 3 when? >:(",
    "reviewed_at": "2020-10-23",
    "tags": ["show", "musical"],
  }, {
    "title": "Alien",
    "link": "https://www.imdb.com/title/tt0078748/",
    "score": 8.25,
    "reviewed_at": "2020-10-24",
    "tags": ["movie"],
  }, {
    "title": "Grave of the Fireflies",
    "link": "https://myanimelist.net/anime/578/Hotaru_no_Haka",
    "score": 8.75,
    "reviewed_at": "2020-10-27",
    "tags": ["movie", "anime"],
  }, {
    "title": "The Nightmare Before Christmas",
    "link": "https://www.imdb.com/title/tt0107688/",
    "score": 8.5,
    "reviewed_at": "2020-10-31",
    "tags": ["movie", "musical"],
  }, {
    "title": "The Big Bang Theory",
    "link": "https://www.imdb.com/title/tt0898266/",
    "score": 5.75,
    "reviewed_at": "2020-12-16",
    "tags": ["show"],
  }, {
    "title": "Attaway General",
    "link": "https://www.imdb.com/title/tt11766306/",
    "score": 0.75,
    "description": "What the fuck is wrong with you",
    "reviewed_at": "2020-12-16",
    "tags": ["show"],
  }, {
    "title": "Crazy Rich Asians",
    "link": "https://www.imdb.com/title/tt3104988/",
    "score": 5.75,
    "reviewed_at": "2020-12-25",
    "tags": ["movie"],
  }, {
    "title": "The Mandalorian",
    "link": "https://www.imdb.com/title/tt8111088/",
    "score": 7.5,
    "reviewed_at": "2020-12-25",
    "tags": ["show"],
  }, {
    "title": "National Lampoon's Christmas Vacation",
    "link": "https://www.imdb.com/title/tt0097958/",
    "score": 5.75,
    "reviewed_at": "2020-12-25",
    "tags": ["movie"],
  }, {
    "title": "The Good Place",
    "link": "https://www.imdb.com/title/tt4955642/",
    "score": 7,
    "reviewed_at": "2020-12-25",
    "tags": ["show"],
  }, {
    "title": "Coraline",
    "link": "https://www.imdb.com/title/tt0327597/",
    "score": 7.5,
    "reviewed_at": "2020-12-25",
    "tags": ["movie"],
  }, {
    "title": "Zombieland",
    "link": "https://www.imdb.com/title/tt1156398/",
    "score": 7,
    "reviewed_at": "2020-12-26",
    "tags": ["movie"],
  }, {
    "title": "Zombieland: Double Tap",
    "link": "https://www.imdb.com/title/tt1560220/",
    "score": 6.75,
    "reviewed_at": "2020-12-26",
    "tags": ["movie"],
  }, {
    "title": "Peep Show",
    "link": "https://www.imdb.com/title/tt0387764/",
    "score": 8.5,
    "reviewed_at": "2020-12-30",
    "tags": ["show"],
  }, {
    "title": "Wonder Showzen",
    "link": "https://www.imdb.com/title/tt0450357/",
    "score": 8.75,
    "reviewed_at": "2021-01-02",
    "tags": ["show"],
  }, {
    "title": "Beastars",
    "link": "https://myanimelist.net/anime/39195/Beastars",
    "score": 8,
    "reviewed_at": "2021-01-26",
    "tags": ["show", "anime"],
  }, {
    "title": "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
    "link": "https://www.imdb.com/title/tt0443453/",
    "score": 7.25,
    "reviewed_at": "2021-01-30",
    "tags": ["movie"],
  }, {
    "title": "Soul",
    "link": "https://www.imdb.com/title/tt2948372/",
    "score": 8,
    "reviewed_at": "2021-02-01",
    "tags": ["movie"],
  }, {
    "title": "Time Bandits",
    "link": "https://www.imdb.com/title/tt0081633/",
    "score": 6,
    "reviewed_at": "2021-02-12",
    "tags": ["movie"],
  }, {
    "title": "Blade Runner 2049",
    "link": "https://www.imdb.com/title/tt1856101/",
    "score": 9,
    "reviewed_at": "2021-02-16",
    "tags": ["movie"],
  }, {
    "title": "X-Men 2",
    "link": "https://www.imdb.com/title/tt0290334/",
    "score": 5,
    "reviewed_at": "2021-02-20",
    "tags": ["movie"],
  }, {
    "title": "Kingsman: The Secret Service",
    "link": "https://www.imdb.com/title/tt2802144/",
    "score": 7.75,
    "reviewed_at": "2021-02-21",
    "tags": ["movie"],
  }, {
    "title": "Kingsman: The Golden Circle",
    "link": "https://www.imdb.com/title/tt4649466/",
    "score": 6,
    "reviewed_at": "2021-02-21",
    "tags": ["movie"],
  }, {
    "title": "Upstart Crow",
    "link": "https://www.imdb.com/title/tt4793190/",
    "score": 7,
    "reviewed_at": "2021-02-23",
    "tags": ["show"],
  }, {
    "title": "West Side Story",
    "link": "https://www.imdb.com/title/tt0055614/",
    "score": 8,
    "reviewed_at": "2021-02-28",
    "tags": ["movie", "musical"],
  }, {
    "title": "Enchanted",
    "link": "https://www.imdb.com/title/tt0461770/",
    "score": 6.5,
    "reviewed_at": "2021-02-28",
    "tags": ["movie", "musical"],
  }, {
    "title": "Nathan for You",
    "link": "https://www.imdb.com/title/tt2297757/",
    "score": 9,
    "reviewed_at": "2021-03-01",
    "tags": ["show"],
  }, {
    "title": "Drive",
    "link": "https://www.imdb.com/title/tt0780504/",
    "score": 6.5,
    "reviewed_at": "2021-03-02",
    "tags": ["movie"],
  }, {
    "title": "South Park: Bigger, Longer & Uncut",
    "link": "https://www.imdb.com/title/tt0158983/",
    "score": 8,
    "reviewed_at": "2021-03-07",
    "tags": ["movie", "musical"],
  }, {
    "title": "WandaVision",
    "link": "https://www.imdb.com/title/tt9140560/",
    "score": 7,
    "reviewed_at": "2021-03-13",
    "tags": ["show"],
  }, {
    "title": "Shazam!",
    "link": "https://www.imdb.com/title/tt0448115/",
    "score": 7,
    "reviewed_at": "2021-03-19",
    "tags": ["movie"],
  }, {
    "title": "The Italian Job",
    "link": "https://www.imdb.com/title/tt0317740/",
    "score": 6.75,
    "reviewed_at": "2021-03-20",
    "tags": ["movie"],
  }, {
    "title": "The Hitman's Bodyguard",
    "link": "https://www.imdb.com/title/tt1959563/",
    "score": 6.5,
    "reviewed_at": "2021-03-21",
    "tags": ["movie"],
  }, {
    "title": "DuckTales",
    "link": "https://www.imdb.com/title/tt5531466/",
    "score": 9,
    "reviewed_at": "2021-03-24",
    "tags": ["show"],
  }, {
    "title": "Captain Marvel",
    "link": "https://www.imdb.com/title/tt4154664/",
    "score": 5.75,
    "reviewed_at": "2021-03-24",
    "tags": ["movie"],
  }, {
    "title": "Archer",
    "link": "https://www.imdb.com/title/tt1486217/",
    "score": 8,
    "reviewed_at": "2021-03-31",
    "tags": ["show"],
  }, {
    "title": "Dead Poets Society",
    "link": "https://www.imdb.com/title/tt0097165/",
    "score": 8.5,
    "reviewed_at": "2021-04-11",
    "tags": ["movie"],
  }, {
    "title": "Hamilton",
    "link": "https://www.imdb.com/title/tt8503618/",
    "score": 9.5,
    "reviewed_at": "2021-04-19",
    "tags": ["movie", "musical"],
  }, {
    "title": "Fiddler on the Roof",
    "link": "https://www.imdb.com/title/tt0067093/",
    "score": 8.25,
    "reviewed_at": "2021-04-20",
    "tags": ["movie", "musical"],
  }, {
    "title": "La La Land",
    "link": "https://www.imdb.com/title/tt3783958/",
    "score": 7,
    "reviewed_at": "2021-04-23",
    "tags": ["movie", "musical"],
  }, {
    "title": "Dips",
    "link": "https://www.imdb.com/title/tt9499182/",
    "score": 7.75,
    "reviewed_at": "2021-04-24",
    "tags": ["show"],
  }, {
    "title": "The Goonies",
    "link": "https://www.imdb.com/title/tt0089218/",
    "score": 7.75,
    "reviewed_at": "2021-04-24",
    "tags": ["movie"],
  }, {
    "title": "Moana",
    "link": "https://www.imdb.com/title/tt3521164/",
    "score": 8.5,
    "reviewed_at": "2021-04-25",
    "tags": ["movie", "musical"],
  }, {
    "title": "American Psycho",
    "link": "https://www.imdb.com/title/tt0144084/",
    "score": 8,
    "reviewed_at": "2021-04-25",
    "tags": ["movie"],
  }, {
    "title": "The Falcon and the Winter Soldier",
    "link": "https://www.imdb.com/title/tt9208876/",
    "score": 5.5,
    "reviewed_at": "2021-04-27",
    "tags": ["show"],
  }, {
    "title": "Tenacious D in The Pick of Destiny",
    "link": "https://www.imdb.com/title/tt0365830/",
    "score": 7,
    "reviewed_at": "2021-05-02",
    "tags": ["movie"],
  }, {
    "title": "Knives Out",
    "link": "https://www.imdb.com/title/tt8946378/",
    "score": 8,
    "reviewed_at": "2021-05-05",
    "tags": ["movie"],
  }, {
    "title": "Legend",
    "link": "https://www.imdb.com/title/tt3569230/",
    "score": 7,
    "reviewed_at": "2021-05-08",
    "tags": ["movie"],
  }, {
    "title": "Invincible",
    "link": "https://www.imdb.com/title/tt6741278/",
    "score": 8,
    "reviewed_at": "2021-05-16",
    "tags": ["show"],
  }, {
    "title": "The Black Adder",
    "link": "https://www.imdb.com/title/tt0084988/",
    "score": 8.25,
    "description": `1: 7
2: 8.5
3: 8
4: 8
Christmas Carol: 8
Cavalier Years: 8
Back & Forth: 8`,
    "reviewed_at": "2021-05-24",
    "tags": ["show"],
  }, {
    "title": "The Inbetweeners",
    "link": "https://www.imdb.com/title/tt1220617/",
    "score": 8,
    "reviewed_at": "2021-05-26",
    "tags": ["show"],
  }, {
    "title": "The Inbetweeners",
    "link": "https://www.imdb.com/title/tt1716772/",
    "score": 8,
    "reviewed_at": "2021-05-26",
    "tags": ["movie"],
  }, {
    "title": "The Inbetweeners 2",
    "link": "https://www.imdb.com/title/tt3097204/",
    "score": 6,
    "reviewed_at": "2021-05-26",
    "tags": ["movie"],
  }, {
    "title": "Back",
    "link": "https://www.imdb.com/title/tt5676590/",
    "score": 8,
    "reviewed_at": "2021-05-29",
    "tags": ["show"],
  }, {
    "title": "The Secret Life of Walter Mitty",
    "link": "https://www.imdb.com/title/tt0359950/",
    "score": 9,
    "reviewed_at": "2021-05-30",
    "tags": ["movie"],
  }, {
    "title": "Falling Down",
    "link": "https://www.imdb.com/title/tt0106856/",
    "score": 7,
    "reviewed_at": "2021-06-01",
    "tags": ["movie"],
  }, {
    "title": "The Florida Project",
    "link": "https://www.imdb.com/title/tt5649144/",
    "score": 8,
    "reviewed_at": "2021-06-06",
    "tags": ["movie"],
  }, {
    "title": "Guns Akimbo",
    "link": "https://www.imdb.com/title/tt6902676/",
    "score": 6,
    "reviewed_at": "2021-06-06",
    "tags": ["movie"],
  }, {
    "title": "Napoleon Dynamite",
    "link": "https://www.imdb.com/title/tt0374900/",
    "score": 8,
    "reviewed_at": "2021-06-12",
    "tags": ["movie"],
  }, {
    "title": "In the Heights",
    "link": "https://www.imdb.com/title/tt1321510/",
    "score": 9,
    "reviewed_at": "2021-06-12",
    "tags": ["movie", "musical"],
  }, {
    "title": "Blazing Saddles",
    "link": "https://www.imdb.com/title/tt0071230/",
    "score": 7,
    "reviewed_at": "2021-06-13",
    "tags": ["movie"],
  }, {
    "title": "Bad Boys for Life",
    "link": "https://www.imdb.com/title/tt1502397/",
    "score": 6,
    "reviewed_at": "2021-06-19",
    "tags": ["movie"],
  }, {
    "title": "That Mitchell and Webb Look",
    "link": "https://www.imdb.com/title/tt0499410/",
    "score": 8,
    "reviewed_at": "2021-07-01",
    "tags": ["show"],
  }, {
    "title": "Guys and Dolls",
    "link": "https://www.imdb.com/title/tt0048140/",
    "score": 7,
    "reviewed_at": "2021-07-02",
    "tags": ["movie", "musical"],
  }, {
    "title": "It's Always Sunny in Philadelphia",
    "link": "https://www.imdb.com/title/tt0472954/",
    "score": 9.5,
    "reviewed_at": "2021-07-04",
    "tags": ["show"],
  }, {
    "title": "Mythic Quest",
    "link": "https://www.imdb.com/title/tt8879940/",
    "score": 8,
    "reviewed_at": "2023-04-14",
    "tags": ["show"],
  }, {
    "title": "Highlander",
    "link": "https://www.imdb.com/title/tt0091203/",
    "score": 6.75,
    "reviewed_at": "2021-07-07",
    "tags": ["movie"],
  }, {
    "title": "Kill Me Three Times",
    "link": "https://www.imdb.com/title/tt2393845/",
    "score": 6,
    "reviewed_at": "2021-07-14",
    "tags": ["movie"],
  }, {
    "title": "Tinker Tailor Soldier Spy",
    "link": "https://www.imdb.com/title/tt1340800/",
    "score": 7,
    "reviewed_at": "2021-07-15",
    "tags": ["movie"],
  }, {
    "title": "Instant Family",
    "link": "https://www.imdb.com/title/tt7401588/",
    "score": 7.5,
    "reviewed_at": "2021-07-16",
    "tags": ["movie"],
  }, {
    "title": "Odd Taxi",
    "link": "https://myanimelist.net/anime/46102/Odd_Taxi",
    "score": 8.5,
    "reviewed_at": "2021-08-03",
    "tags": ["show", "anime"],
  }, {
    "title": "Bo Burnham: Inside",
    "link": "https://www.imdb.com/title/tt14544192/",
    "score": 8.75,
    "reviewed_at": "2021-08-03",
    "tags": ["movie"],
  }, {
    "title": "The Suicide Squad",
    "link": "https://www.imdb.com/title/tt6334354/",
    "score": 6.75,
    "reviewed_at": "2021-08-11",
    "tags": ["movie"],
  }, {
    "title": "Shot Caller",
    "link": "https://www.imdb.com/title/tt4633690/",
    "score": 5.5,
    "reviewed_at": "2021-10-02",
    "tags": ["movie"],
  }, {
    "title": "The Captive",
    "link": "https://www.imdb.com/title/tt2326612/",
    "score": 4,
    "reviewed_at": "2021-10-07",
    "tags": ["movie"],
  }, {
    "title": "Z for Zachariah",
    "link": "https://www.imdb.com/title/tt1598642/",
    "score": 3.5,
    "reviewed_at": "2021-10-08",
    "tags": ["movie"],
  }, {
    "title": "Squid Game",
    "link": "https://www.imdb.com/title/tt10919420/",
    "score": 8,
    "reviewed_at": "2021-10-14",
    "tags": ["show"],
  }, {
    "title": "Child 44",
    "link": "https://www.imdb.com/title/tt1014763/",
    "score": 6.5,
    "reviewed_at": "2021-10-29",
    "tags": ["movie"],
  }, {
    "title": "Motherless Brooklyn",
    "link": "https://www.imdb.com/title/tt0385887/",
    "score": 6.5,
    "reviewed_at": "2021-10-30",
    "tags": ["movie"],
  }, {
    "title": "Stargate SG-1",
    "link": "https://www.imdb.com/title/tt0118480/",
    "score": 9,
    "description": "While it definitely didn't dip in quality when Richard Dean Anderson left, I did start enjoying it less. Probably because I associate the show with the original team so closely.",
    "reviewed_at": "2021-11-24",
    "tags": ["show"],
  }, {
    "title": "Stargate: The Ark of Truth",
    "link": "https://www.imdb.com/title/tt0118480/",
    "score": 7.5,
    "description": "While it wraps up the Ori storyline well, I feel it tarnishes the last episode of the show a bit.",
    "reviewed_at": "2021-11-26",
    "tags": ["movie"],
  }, {
    "title": "Amnesia: The Dark Descent",
    "link": "https://www.gog.com/game/amnesia_the_dark_descent",
    "score": 7,
    "tags": ["game"],
  }, {
    "title": "Audiosurf",
    "link": "https://store.steampowered.com/app/12900/AudioSurf/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Bastion",
    "link": "https://www.gog.com/game/bastion",
    "score": 9,
    "tags": ["game"],
  }, {
    "title": "Assassin's Creed II",
    "link": "https://store.steampowered.com/app/33230/Assassins_Creed_2/",
    "score": 7,
    "tags": ["game"],
  }, {
    "title": "Dishonored",
    "link": "https://www.gog.com/game/dishonored_definitive_edition",
    "score": 7,
    "tags": ["game"],
  }, {
    "title": "Trine 2: Complete Story",
    "link": "https://www.gog.com/game/trine_2_complete_story",
    "score": 7,
    "tags": ["game"],
  }, {
    "title": "Borderlands 2",
    "link": "https://store.steampowered.com/app/49520/Borderlands_2/",
    "score": 7,
    "tags": ["game"],
  }, {
    "title": "The Elder Scrolls V: Skyrim",
    "link": "https://store.steampowered.com/app/72850/The_Elder_Scrolls_V_Skyrim/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "FTL",
    "link": "https://www.gog.com/game/faster_than_light",
    "score": 6,
    "tags": ["game"],
  }, {
    "title": "Antichamber",
    "link": "https://store.steampowered.com/app/219890/Antichamber/",
    "score": 7,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Proteus",
    "link": "https://store.steampowered.com/app/219680/Proteus/",
    "score": 8,
    "reviewed_at": "2021-12-03",
    "description": "Just incredibly relaxing.",
    "tags": ["game"],
  }, {
    "title": "Brothers: A Tale of Two Sons",
    "link": "https://www.gog.com/game/brothers_a_tale_of_two_sons",
    "score": 8,
    "reviewed_at": "2021-12-03",
    "description": "Nice use of gameplay mechanics to tell the story.",
    "tags": ["game"],
  }, {
    "title": "Fallout 4",
    "link": "https://store.steampowered.com/app/377160/Fallout_4/",
    "score": 6.5,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Wandersong",
    "link": "https://www.gog.com/game/wandersong",
    "score": 9.5,
    "description": "Nothing amazingly groundbreaking, but it does what it sets out to do, and does it well. I would personally have done the ending a bit differently (as you can see here: https://thenamlessguy.github.io/rants/my-wandersong-ending.html), but it's still one of my favorite games.",
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Stars Die",
    "link": "https://store.steampowered.com/app/1457740/Stars_Die/",
    "score": 8,
    "description": "Very much gives me the same feeling as when I read Lovecraft. Captures the cosmic horror vibes fantastically, without just jerking off Lovecraft's dead dongler.",
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Heaven's Vault",
    "link": "https://www.gog.com/game/heavens_vault",
    "score": 9,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "The Elder Scrolls III: Morrowind",
    "link": "https://www.gog.com/game/the_elder_scrolls_iii_morrowind_goty_edition",
    "score": 8.5,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "The Elder Scrolls IV: Oblivion",
    "link": "https://www.gog.com/game/elder_scrolls_iv_oblivion_game_of_the_year_edition_deluxe_the",
    "score": 9,
    "description": `The perfect balance between the depth in Morrowind and the simplicity of Skyrim.
Only thing I would really change is the leveling system, as I feel only leveling up from your major skills is kind of boring.
Instead, make it so any skill under 25 gives you a debuff for everything to do with it, have your major skills start at 25, and make it so you level up from all skills.

Maybe fix the difficulty curve as well. Did Battle of Kvatch at level 14 or something, and I just flat out couldn't beat it with my character build.`,
    "reviewed_at": "2021-12-03",
    "tags": ["game"],
  }, {
    "title": "Inscryption",
    "link": "https://www.gog.com/game/inscryption",
    "score": 8,
    "reviewed_at": "2021-12-03",
    "description": "While I didn't follow the ARG aspect of the game, I did still immensely enjoy the game itself. Go in blind if you haven't played it.",
    "tags": ["game"],
  }, {
    "title": "B: The Beginning",
    "link": "https://myanimelist.net/anime/32827/B__The_Beginning",
    "score": 1,
    "reviewed_at": "2021-12-04",
    "description": "13 year old edgy deviantart artist makes an anime.",
    "tags": ["show", "anime"],
  }, {
    "title": "My Hero Academia",
    "link": "https://myanimelist.net/anime/31964/Boku_no_Hero_Academia",
    "score": 6.5,
    "reviewed_at": "2021-12-04",
    "tags": ["show", "anime"],
  }, {
    "title": "FLCL",
    "link": "https://myanimelist.net/anime/227/FLCL",
    "score": 7,
    "tags": ["show", "anime"],
  }, {
    "title": "Fullmetal Alchemist",
    "link": "https://myanimelist.net/anime/121/Fullmetal_Alchemist",
    "score": 7.5,
    "tags": ["show", "anime"],
  }, {
    "title": "Katekyo Hitman Reborn!",
    "link": "https://myanimelist.net/anime/1604/Katekyo_Hitman_Reborn",
    "score": 7,
    "tags": ["show", "anime"],
  }, {
    "title": "Lucky☆Star",
    "link": "https://myanimelist.net/anime/1887/Lucky%E2%98%86Star",
    "score": 6.5,
    "tags": ["show", "anime"],
  }, {
    "title": "Welcome to the N.H.K.",
    "link": "https://myanimelist.net/anime/1210/NHK_ni_Youkoso",
    "score": 8,
    "tags": ["show", "anime"],
  }, {
    "title": "Paprika",
    "link": "https://myanimelist.net/anime/1943/Paprika",
    "score": 7,
    "tags": ["movie", "anime"],
  }, {
    "title": "Pokémon: Origins",
    "link": "https://myanimelist.net/anime/20159/Pokemon__The_Origin",
    "score": 7,
    "reviewed_at": "2021-12-04",
    "tags": ["show", "anime"],
  }, {
    "title": "Sword Art Online",
    "link": "https://myanimelist.net/anime/11757/Sword_Art_Online",
    "score": 4.75,
    "reviewed_at": "2021-12-04",
    "tags": ["show", "anime"],
  }, {
    "title": "Ouran High School Host Club",
    "link": "https://myanimelist.net/anime/853/Ouran_Koukou_Host_Club",
    "score": 6.5,
    "tags": ["show", "anime"],
  }, {
    "title": "Curb Your Enthusiasm",
    "link": "https://www.imdb.com/title/tt0264235/",
    "score": 7,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Aunty Donna's Big Ol' House of Fun",
    "link": "https://www.imdb.com/title/tt13316746/",
    "score": 8,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Space Force",
    "link": "https://www.imdb.com/title/tt9612516/",
    "score": 6.5,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Altered Carbon",
    "link": "https://www.imdb.com/title/tt2261227/",
    "score": 9,
    "reviewed_at": "2021-12-04",
    "description": "Note: Season 1 only. Season 2 just turned into a generic sci-fi action series.",
    "tags": ["show"],
  }, {
    "title": "Bob's Burgers",
    "link": "https://www.imdb.com/title/tt1561755/",
    "score": 7,
    "reviewed_at": "2023-01-19",
    "description": "Much like most other shows of this format, the characters eventually become caricatures of themselves, and the writing peaks somewhere around season 5. Not bad, just goes from 'good episodes with the occasional average' to 'average episodes with the occasional good'. Then again, running for 12 years will probably do that to any show",
    "tags": ["show"],
  }, {
    "title": "Dirk Gently's Holistic Detective Agency",
    "link": "https://www.imdb.com/title/tt4047038/",
    "score": 8,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Doom Patrol",
    "link": "https://www.imdb.com/title/tt8416494/",
    "score": 6.5,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Fawlty Towers",
    "link": "https://www.imdb.com/title/tt0072500/",
    "score": 8,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "The IT Crowd",
    "link": "https://www.imdb.com/title/tt0487831/",
    "score": 8.75,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "The Boys",
    "link": "https://www.imdb.com/title/tt1190634/",
    "score": 8,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Parks and Recreation",
    "link": "https://www.imdb.com/title/tt1266020/",
    "score": 8,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Madness Combat",
    "link": "https://www.imdb.com/title/tt2072604/",
    "score": 7,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Loki",
    "link": "https://www.imdb.com/title/tt9140554/",
    "score": 6.5,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "I Think You Should Leave with Tim Robinson",
    "link": "https://www.imdb.com/title/tt10050772/",
    "score": 7,
    "reviewed_at": "2021-12-04",
    "tags": ["show"],
  }, {
    "title": "Guardians of the Galaxy",
    "link": "https://www.imdb.com/title/tt2015381/",
    "score": 8,
    "reviewed_at": "2021-12-04",
    "description": "Pretty sure it would be a 6 or so (like the rest of the marvel movies) if it wasn't directed by James Gunn",
    "tags": ["movie"],
  }, {
    "title": "Stargate: Continuum",
    "link": "https://www.imdb.com/title/tt0929629/",
    "score": 8.5,
    "reviewed_at": "2021-12-12",
    "description": "A good sendoff to the SG1 series",
    "tags": ["movie"],
  }, {
    "title": "Office Space",
    "link": "https://www.imdb.com/title/tt0151804/",
    "score": 8.5,
    "reviewed_at": "2021-12-21",
    "tags": ["movie"],
  }, {
    "title": "En Underbar Jävla Jul",
    "link": "https://www.imdb.com/title/tt4728582/",
    "score": 7,
    "reviewed_at": "2021-12-23",
    "tags": ["movie"],
  }, {
    "title": "Wrath of Man",
    "link": "https://www.imdb.com/title/tt11083552/",
    "score": 4,
    "reviewed_at": "2021-12-22",
    "tags": ["movie"],
  }, {
    "title": "The First Tree",
    "link": "https://www.gog.com/game/the_first_tree",
    "score": 3.5,
    "reviewed_at": "2021-12-30",
    "description": `The music is great, the voice acting ranges from great to passable, and the gameplay is... severely lacking. Spoilers after this.
In the first section, I dug up the tank before anything else, which led to the story itself seeming disjoined and weird, at least for that section. There was no clear path, no clear way of telling which thing to go for first.
The open landscape itself is a major detriment to the gameplay in general, as you just blindly press W to move forward with functionally nothing to guide you in the right direction. The player is often left to wander aimlessly in order to progress, especially if you want to explore - which the game (at least vocally) encourages.
The "stand and bow on three rocks" segment took way longer than it should have, mostly because it took me until the third rock to understand that you're supposed to bow when the thing is IN the rock, not when it's floating above. Obviously, this is very counter-intutitive, as you've been collecting light orbs for 90% of the game up until this point.
The night time level I had to restart twice because I kept chasing the second deer, and kept running in that direction until I hit the edge of the map and subsequently fell off. As opposed to what the game tells you to do with the first deer, you are NOT supposed to chase them, but stand on the little island behind them and listen to the story until the next deer emerges. That is, except the last one. That one you're supposed to chase.
Personally, I also felt that the map-to-map transitions were very disjointed. During the title sequence you see the tree in the distance, so I expected to have a seamless journey to the tree, where I could always see it in the distance. Alas, instead you go from snowy mountain top to green forest in the blink of an eye.

The entire game feels disjointed and strange, but there is definite potential (if you're into walking simulators). It's apparently the creators first game, and for that I'd say it's passable. Here's a list of things I'd say needs working on if they are going to make something similar in the future:
* Weave the gameplay and the story together better
** If you're telling a linear story, make sure you guide the player so that they experience it in the correct order
** Make the players journey map at least somewhat to the story being told, outside of cutscenes. This happened once in the game: When you had to jump over that big cliff
*** It doesn't have to be a literal mapping either, it could also be something more metaphorical. The narrator starts to doubt himself, so the path forward becomes narrow and hard to navigate, or something in that sense
* Do not just have big open world spaces with nothing in it
** Introduce SOME mechanic for making traversal more interesting. A climbing mechanic? Rolling down hills? Anything that breaks up the monotony of "Hold W"`,
    "tags": ["game"],
  }, {
    "title": "Encanto",
    "link": "https://www.imdb.com/title/tt2953050/",
    "score": 9,
    "reviewed_at": "2021-12-31",
    "description": "I definitely simp for Lin-Manuel Miranda",
    "tags": ["movie"],
  }, {
    "title": "Stargate Atlantis",
    "link": "https://www.imdb.com/title/tt0374455/",
    "score": 8.25,
    "description": "While I enjoyed the world building and the things surrounding it more in SG-1, Atlantis was still a very good show in its own right.",
    "reviewed_at": "2022-01-09",
    "tags": ["show"],
  }, {
    "title": "Stargate Universe",
    "link": "https://www.imdb.com/title/tt1286039/",
    "score": 8.25,
    "description": "Very different from the other Stargate series, but it was exactly what they needed for a starship exploration series within the Stargate universe. Perhaps the most intriguing overarching plotline of the universe so far, even if it never gets resolved.",
    "reviewed_at": "2022-01-16",
    "tags": ["show"],
  }, {
    "title": "Rango",
    "link": "https://www.imdb.com/title/tt1192628/",
    "score": 7.5,
    "reviewed_at": "2022-01-23",
    "tags": ["movie"],
  }, {
    "title": "The Forgotten City",
    "link": "https://www.gog.com/game/the_forgotten_city",
    "score": 7.5,
    "reviewed_at": "2022-01-26",
    "description": "Waht a tweest. The Bethesda style zoom talk results in some stiff delivery at points (for example, the conversation you have with hood lady in the endings where you make it out), but very good for what it is.",
    "tags": ["game"],
  }, {
    "title": "Metroid Dread",
    "link": "https://www.nintendo.com/games/detail/metroid-dread-switch/",
    "score": 8,
    "reviewed_at": "2022-01-26",
    "tags": ["game"],
  }, {
    "title": "Scott Pilgrim vs. the World",
    "link": "https://www.imdb.com/title/tt0446029/",
    "score": 7.5,
    "description": "For a movie where pretty much everyone is an asshole in one form or another, it works fairly well. At least Knives walks out on the path of being a decent person at the end",
    "reviewed_at": "2022-02-04",
    "tags": ["movie"],
  }, {
    "title": "Free Guy",
    "link": "https://www.imdb.com/title/tt6264654/",
    "score": 6.5,
    "description": "'We gotta bypass the firewall so we can reverse the operating system bitstream' dialogue aside, it's a pretty decent comedy. The drama moments fall flat due to poor pacing, but at it's best it's just Ryan Reynolds being Ryan Reynolds.",
    "reviewed_at": "2022-02-06",
    "tags": ["movie"],
  }, {
    "title": "Pokemon Legends: Arceus",
    "link": "https://www.nintendo.com/games/detail/pokemon-legends-arceus-switch/",
    "score": 8,
    "description": `Despite it looking like babbys first unity project, it plays fantastically.
Combat is a bit simplified to the earlier entries, but the addition of the STRONG/AGILE style thing is neat.
Alpha thing really interesting, having Pokemon actually attack the player is as well.

Everything just works very well, for what it is. Hope they continue the Legends series, and that they expand on the gameplay further.`,
    "reviewed_at": "2022-02-07",
    "tags": ["game"],
  }, {
    "title": "Dagon",
    "link": "https://www.imdb.com/title/tt0264508/",
    "score": 7.5,
    "description": "A pretty good representation of what a Lovecraft story entails, even if the promotional material makes it look much less than",
    "reviewed_at": "2022-02-11",
    "tags": ["movie"],
  }, {
    "title": "Airplane!",
    "link": "https://www.imdb.com/title/tt0080339/",
    "score": 9,
    "description": "Classic for a reason",
    "reviewed_at": "2022-02-12",
    "tags": ["movie"],
  }, {
    "title": "Crazy Ex-Girlfriend",
    "link": "https://www.imdb.com/title/tt4094300/",
    "score": 8,
    "description": `I started watching this mostly because I needed a 40~ minute show to watch while on the treadmill. The first two seasons were, to me, just that: a romantic comedy show, something which isn't really my cup of tea usually.

Then season 3 started, and it went to places I did NOT expect the show to go, especially in the first half. Don't get me wrong, if the show had started out at the season 3 stuff, it definitely wouldn't have had the same impact. You pretty much needed the prior two seasons to set it up, to give the moments that extra oomph.
The latter half of season 3 and most of season 4 does feel like a return to formula though, but all throughout that part of the show there's this underlying feeling of something else going on, which pays off perfectly in the finale.`,
    "reviewed_at": "2022-02-14",
    "tags": ["show"],
  }, {
    "title": "AER - Memories of Old",
    "link": "https://www.gog.com/game/aer",
    "score": 7.5,
    "description": "If it had been any longer than it was, the experience would have suffered immensely. However, it is the perfect length for the gameplay they present.",
    "reviewed_at": "2022-02-19",
    "tags": ["game"],
  }, {
    "title": "Mulan (1998)",
    "link": "https://www.imdb.com/title/tt0120762/",
    "score": 9,
    "description": "Shoutout to one of the few disney pricesses (especially for her time) who actually does something",
    "reviewed_at": "2022-02-20",
    "tags": ["movie"],
  }, {
    "title": "Zoey's Extraordinary Playlist",
    "link": "https://www.imdb.com/title/tt10314462/",
    "score": 7,
    "description": "I don't usually care much for jukebox musicals, but this one can get a pass. A little bit bummed out at the generic ending of the show, but whatever",
    "reviewed_at": "2022-03-05",
    "tags": ["show", "movie"],
  }, {
    "title": "Who Framed Roger Rabbit",
    "link": "https://www.imdb.com/title/tt0096438/",
    "score": 8,
    "description": "It's genuinely surprising how well this movie holds up. The fact that we have so many different characters from so many different IP holders is just shy of amazing. If it were today, the entirety of the movie's budget would probably have gone to the Mickey Mouse cameos.",
    "reviewed_at": "2022-03-20",
    "tags": ["movie"],
  }, {
    "title": "Pooh's Grand Adventure: The Search for Christopher Robin",
    "link": "https://www.imdb.com/title/tt0119918/",
    "score": 7,
    "description": "My favorite movie as a young kid. Can't say it still holds that title, but it's very good for a kids movie",
    "reviewed_at": "2022-03-22",
    "tags": ["movie"],
  }, {
    "title": "American Dad",
    "link": "https://www.imdb.com/title/tt0397306/",
    "score": 8.5,
    "reviewed_at": "2022-04-07",
    "tags": ["show"],
  }, {
    "title": "Schmigadoon!",
    "link": "https://www.imdb.com/title/tt11808942/",
    "score": 6,
    "reviewed_at": "2022-04-08",
    "tags": ["show"],
  }, {
    "title": "Dark Matter",
    "link": "https://www.imdb.com/title/tt4159076/",
    "score": 6,
    "reviewed_at": "2022-04-14",
    "description": "The biggest issue I have with the show is mainly that the tone it presents makes it seem more serious than it is. The best example is probably the groundhog day episode, which, while enjoyable, does not fit into the darker, edgier, broodier mood that the rest of the show presents. That being said, the world building is pretty good, and sadly it ends right when it starts to get interesting",
    "tags": ["show"],
  }, {
    "title": "Dune",
    "link": "https://www.imdb.com/title/tt1160419/",
    "score": 9,
    "reviewed_at": "2022-04-22",
    "description": "I haven't read the book, but damn dude",
    "tags": ["movie"],
  }, {
    "title": "Maya and the Three",
    "link": "https://www.imdb.com/title/tt8787772/",
    "score": 7,
    "reviewed_at": "2022-05-04",
    "description": "Would have been significantly better if it were given (a lot) more than 9 episodes to build up the world, the threat, and especially the character relationships. If handled well, it could (potentially) have been as good as ATLA, but now it stands as it is.",
    "tags": ["show"],
  }, {
    "title": "Murder by Numbers",
    "link": "https://www.gog.com/game/murder_by_numbers",
    "score": 8.5,
    "description": "100%-ed it. Solid picross puzzle game. The timed parts feel extremely out of place, but once you get used to it they're not much of a hindrance (even though I wouldn't call it picross at that point anymore).",
    "reviewed_at": "2022-05-08",
    "tags": ["game"],
  }, {
    "title": "Chip 'n Dale: Rescue Rangers (2022)",
    "link": "https://www.imdb.com/title/tt3513500/",
    "score": 6.5,
    "reviewed_at": "2022-05-20",
    "tags": ["movie"],
  }, {
    "title": "Moon Knight",
    "link": "https://www.imdb.com/title/tt10234724/",
    "score": 6,
    "reviewed_at": "2022-05-23",
    "description": "It would be a 4.5-5 if it weren't for Oscar Isaac and Ethan Hawke doing a great job with what they're given",
    "tags": ["show"],
  }, {
    "title": "Stargate",
    "link": "https://www.imdb.com/title/tt0111282/",
    "score": 8.5,
    "reviewed_at": "2022-05-26",
    "description": "No wonder this spawned so many good shows",
    "tags": ["movie"],
  }, {
    "title": "Severance",
    "link": "https://www.imdb.com/title/tt11280740/",
    "score": 8.5,
    "reviewed_at": "2022-05-28",
    "tags": ["show"],
  }, {
    "title": "Spaceballs",
    "link": "https://www.imdb.com/title/tt0094012/",
    "score": 7.5,
    "reviewed_at": "2022-05-29",
    "description": "Lmao balls",
    "tags": ["movie"],
  }, {
    "title": "The Mummy",
    "link": "https://www.imdb.com/title/tt0120616/",
    "score": 8,
    "reviewed_at": "2022-06-04",
    "description": "Some of the CGI doesn't hold up, but the rest of the movie does spectacularly",
    "tags": ["movie"],
  }, {
    "title": "Sonic the Hedgehog 2",
    "link": "https://www.imdb.com/title/tt12412888/",
    "score": 7.5,
    "reviewed_at": "2022-06-10",
    "description": "A straight up improvement on the first one in every way imaginable, especially when considering the new cast (with Colleen as Tails, the one true choice).",
    "tags": ["movie"],
  }, {
    "title": "Our Flag Means Death",
    "link": "https://www.imdb.com/title/tt11000902/",
    "score": 7,
    "reviewed_at": "2022-06-17",
    "tags": ["show"],
  }, {
    "title": "South Park",
    "link": "https://www.imdb.com/title/tt0121955/",
    "score": 7,
    "reviewed_at": "2022-07-23",
    "description": "First few seasons are a definite 9, then it starts going downwards. Still a few peaks here and there, but overall worse",
    "tags": ["show"],
  }, {
    "title": "Superliminal",
    "link": "https://www.gog.com/game/superliminal",
    "score": 7.5,
    "reviewed_at": "2022-07-22",
    "tags": ["game"],
  }, {
    "title": "The Middle",
    "link": "https://www.imdb.com/title/tt1442464/",
    "score": 7.5,
    "reviewed_at": "2022-07-25",
    "description": "Not mindblowing, but does what it does very well. Didn't overstay its welcome, as it was just the right length.",
    "tags": ["show"],
  }, {
    "title": "Dishonored",
    "link": "https://www.gog.com/game/dishonored_definitive_edition",
    "score": 7,
    "reviewed_at": "2022-09-11",
    "description": "Simpler than I remembered, but still great. If I come back to it again in another 10 years, I'll probably say the same thing.",
    "tags": ["game"],
  }, {
    "title": "From",
    "link": "https://www.imdb.com/title/tt9813792/",
    "score": 7,
    "reviewed_at": "2022-09-14",
    "description": "Interesting enough to keep watching",
    "tags": ["show"],
  }, {
    "title": "Kung Fu Hustle",
    "link": "https://www.imdb.com/title/tt0373074/",
    "score": 8,
    "reviewed_at": "2022-09-26",
    "tags": ["movie"],
  }, {
    "title": "Kirby and the Forgotten Land",
    "link": "https://kirbyandtheforgottenland.nintendo.com/",
    "score": 8,
    "reviewed_at": "2022-09-30",
    "description": "Solid Kirby game, if you're into that sort of thing (I am)",
    "tags": ["game"],
  }, {
    "title": "The Sumerians - Fall of the First Cities",
    "link": "https://www.imdb.com/title/tt13015920/",
    "score": 9,
    "reviewed_at": "2022-10-04",
    "description": "Very well put together",
    "tags": ["movie", "documentary"],
  }, {
    "title": "The Book of Life",
    "link": "https://www.imdb.com/title/tt2262227/",
    "score": 7.5,
    "reviewed_at": "2022-10-13",
    "tags": ["movie"],
  }, {
    "title": "Lion King 2: Simba's Pride",
    "link": "https://www.imdb.com/title/tt0120131/",
    "score": 7,
    "reviewed_at": "2022-10-17",
    "description": "I would probably rate it higher if it didn't have such GINORMOUS shoes to fill",
    "tags": ["movie"],
  }, {
    "title": "Jurassic World",
    "link": "https://www.imdb.com/title/tt0369610/",
    "score": 6,
    "reviewed_at": "2022-10-17",
    "description": "Pretty much just Jurassic Park but worse. Not terrible, though",
    "tags": ["movie"],
  }, {
    "title": "Jurassic World - Fallen Kingdom",
    "link": "https://www.imdb.com/title/tt4881806/",
    "score": 5.5,
    "reviewed_at": "2022-10-23",
    "description": "Pretty much just The Lost World: Jurassic Park but worse. Not terrible, though",
    "tags": ["movie"],
  }, {
    "title": "Arcane",
    "link": "https://www.imdb.com/title/tt11126994/",
    "score": 8.5,
    "reviewed_at": "2022-10-23",
    "description": "Story wasn't earth-shattering in its uniqueness, but was told very well. The animation was absolutely fantastic, with extra props to the few frame animations that seemed to be purely hand drawn.",
    "tags": ["show"],
  }, {
    "title": "Spirited",
    "link": "https://www.imdb.com/title/tt10999120/",
    "score": 7.5,
    "reviewed_at": "2022-11-25",
    "description": "Did what it set out to do, and did it well. I wouldn't call it ground breaking, but definitely solid.",
    "tags": ["movie"],
  }, {
    "title": "Shadows over Loathing",
    "link": "https://store.steampowered.com/app/1939160/Shadows_Over_Loathing/",
    "score": 7.5,
    "reviewed_at": "2023-01-12",
    "tags": ["game"],
  }, {
    "title": "The Bob's Burgers Movie",
    "link": "https://www.imdb.com/title/tt7466442/",
    "score": 7,
    "reviewed_at": "2023-01-19",
    "tags": ["movie"],
  }, {
    "title": "Pokémon Violet",
    "link": "https://scarletviolet.pokemon.com/en-us/",
    "score": 8,
    "reviewed_at": "2023-01-20",
    "description": "Definitely flawed programatically, but still tons of fun. Did not expect the final story arc to take the turns that it did, but it was executed well and I respect the hell out of it.",
    "tags": ["game"],
  }, {
    "title": "A Knight's Tale",
    "link": "https://www.imdb.com/title/tt0183790/",
    "score": 8,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Brother Bear",
    "link": "https://www.imdb.com/title/tt0328880/",
    "score": 8,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Disenchanted",
    "link": "https://www.imdb.com/title/tt1596342/",
    "score": 6.5,
    "reviewed_at": "2023-01-22",
    "description": "More of the same, but that isn't necessarily a bad thing",
    "tags": ["movie", "musical"],
  }, {
    "title": "Fantastic Mr. Fox",
    "link": "https://www.imdb.com/title/tt0432283/",
    "score": 8,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "How to Train Your Dragon",
    "link": "https://www.imdb.com/title/tt0892769/",
    "score": 7,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "How to Train Your Dragon 2",
    "link": "https://www.imdb.com/title/tt1646971/",
    "score": 7,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "How to Train Your Dragon: The Hidden World",
    "link": "https://www.imdb.com/title/tt2386490/",
    "score": 7,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Made in Italy",
    "link": "https://www.imdb.com/title/tt9207700/",
    "score": 6.5,
    "reviewed_at": "2023-01-22",
    "description": "Nothing groundbreaking, does what it sets out to do well. Commercial for Tuscany",
    "tags": ["movie"],
  }, {
    "title": "Men in Black",
    "link": "https://www.imdb.com/title/tt0119654/",
    "score": 8,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Men in Black II",
    "link": "https://www.imdb.com/title/tt0120912/",
    "score": 7.5,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Men in Black 3",
    "link": "https://www.imdb.com/title/tt1409024/",
    "score": 7,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Men in Black: International",
    "link": "https://www.imdb.com/title/tt2283336/",
    "score": 7,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Ronja Rövardotter",
    "link": "https://www.imdb.com/title/tt0088015/",
    "score": 9,
    "reviewed_at": "2023-01-22",
    "description": "My favorite Astrid Lindgren story told just about perfectly",
    "tags": ["movie"],
  }, {
    "title": "Shrek",
    "link": "https://www.imdb.com/title/tt0126029/",
    "score": 9,
    "reviewed_at": "2023-01-22",
    "description": "Genuinely just good",
    "tags": ["movie"],
  }, {
    "title": "Sinbad: Legend of the Seven Seas",
    "link": "https://www.imdb.com/title/tt0165982/",
    "score": 6.5,
    "reviewed_at": "2023-01-22",
    "description": "Not the greatest Dreamworks movie from this era. The animation relies too heavily on 3D effects, most of which do not look good.",
    "tags": ["movie"],
  }, {
    "title": "Spy Kids",
    "link": "https://www.imdb.com/title/tt0227538/",
    "score": 7.5,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Spy Kids 2: Island of Lost Dreams",
    "link": "https://www.imdb.com/title/tt0287717/",
    "score": 7.5,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "Spy Kids 3: Game Over",
    "link": "https://www.imdb.com/title/tt0338459/",
    "score": 6,
    "reviewed_at": "2023-01-22",
    "description": "Really weird to watch without the 3D function, relies too heavily on it throughout the film.",
    "tags": ["movie"],
  }, {
    "title": "Stardust",
    "link": "https://www.imdb.com/title/tt0486655/",
    "score": 7.5,
    "reviewed_at": "2023-01-22",
    "description": "Good quality fantasy",
    "tags": ["movie"],
  }, {
    "title": "The Aristocats",
    "link": "https://www.imdb.com/title/tt0065421/",
    "score": 7,
    "reviewed_at": "2023-01-22",
    "tags": ["movie"],
  }, {
    "title": "The Prince of Egypt",
    "link": "https://www.imdb.com/title/tt0120794/",
    "score": 9.5,
    "reviewed_at": "2023-01-22",
    "description": "Simply fantastic",
    "tags": ["movie"],
  }, {
    "title": "Rock lee vs Gaara - Linkin park",
    "link": "https://www.youtube.com/watch?v=VgDgWzBL7s4",
    "score": 9.5,
    "reviewed_at": "2023-01-26",
    "description": "Art",
    "tags": ["music", "video", "anime"],
  }, {
    "title": "Van Helsing",
    "link": "https://www.imdb.com/title/tt0338526/",
    "score": 7.5,
    "reviewed_at": "2023-02-05",
    "tags": ["movie"],
  }, {
    "title": "The Dragon Prince",
    "link": "https://www.imdb.com/title/tt8688814/",
    "score": 7,
    "reviewed_at": "2023-02-12",
    "description": `HERE BE SPOILERS for Dragon Prince, Avatar - The Last Airbender, and Legend of Korra.

I'm probably too harsh on this show, mostly because it has to live up to the near-masterpiece that is ATLA, but there is something about it that just feels off.

I can't help but compare the two. In no particular order:
* Soren is by and large the "comic relief". While Sokka was THE comedy guy in ATLA, it feels like the other characters also had an equal amount of comic relief. In TDP, it feels like 70% of the jokes are either from Soren, or about Soren.
* I can't for the life of me care even a bit about Ezran (I had to look his name up). He feels like a mary sue and a soap box rolled into one. He has no flaws that can't be handwaved away as him being a kid. He can telepathically communicate with animals because reasons (most likely so he can talk to his bird-dad whenever that plot point gets resolved). It feels like Ezran (I had to scroll back to recheck his name) is supposed to be the new Aang, but they give him none of the complexity that made Aang an interesting character. Aang had the weight of the world on him, but he could barely handle it due to being a kid. Erzan gets an entire kingdom dumped on him, and he goes "sigh... alright sure" and then is the gigachad can't-do-anything-wrong-king who just wants peace when every one else wants war because he is the good guy and the others aren't. Yes, Aang could be preachy at times as well, but that was easily explained by his upbringing and, you know, the fact that he was the Avatar. Ultimately, Ezran (I remembered it this time) is just some kid who can talk to animals because plot.
* Speaking of soap boxing, I feel like the show does a lot of it. ATLA did this as well, but it went about it much better. In ATLA, if you wanted to say "Don't do the thing", they show the characters you (the viewer) care about doing the thing, the implications doing the thing has to their relationships with the other characters, and just in general show WHY it's bad, while at the same time showing why you might actually do the thing. In TDP, it feels very much like they just say "People who do the thing are bad" and then they fight the people who do the thing. Afterwards, the good guys win, and they say "See, doing the thing doesn't lead you anywhere". To be fair, this is a trend I feel I see more and more in general, not just with this show. Personally, I blame Twitter.
* It seems very much like the implication of the elves dialects is that all the sun elves should have the french-ish accent, but some of them just don't? Half of Rayla's hunting team didn't have the accent.
* The entire first season feels rushed. Sort of in the same way Korra Book 1 did, but at least that had the entire previous show to build on.

Not to say that TDP doesn't have its moments.
* As with ATLA, the world building is really good. Not as good as in ATLA, but that's probably because ATLA had double the amount of episodes at its disposal in order to build up the world.
* I did NOT expect that whole "Soren becomes a quadraplegic" arc, which I feel was well executed. The only downside being that the only real lasting result of that arc is that Claudia gets a white streak in her hair.
* The idea of watching Zym growing up is neat. Him being named after Ozymandias is kind of funny also, well done.
* I didn't like bait the first time I watched the first season, but now by season 4 he is one of my favorite characters. They manage to squeeze a lot of personality out of the little bit of screen time he has.
* Callum doing dark magic once and regretting it, but it still having lasting implications even after the time skip is a very well fired Chekhov's gun.
* The Aaravos mystery being set up from episode one makes it the most intriguing arc the series probably has to offer. I am just guessing at this point, but he is going to end up being either inside the magic cube, or somewhere in Katolis. Also, he's voiced by Erik Dellums, who - to me - will always be Three Dog ([insert howl here]) from Fallout 3, and that makes me happy.

Ultimately, I think a lot of the issues I have with the show probably boil down to two major things:
1) It has half the episodes per season that ATLA did. A lot of the world and characters don't get as fleshed out as they seem to be in the writers heads because of this.
2) Even if they had gotten the time required in point 1, I feel like it would have been used for more soap boxing, and less character building. Again, I blame Twitter.`,
    "tags": ["show"],
  }, {
    "title": "Ping Pong the Animation",
    "link": "https://myanimelist.net/anime/22135/Ping_Pong_the_Animation",
    "score": 9.5,
    "reviewed_at": "2023-02-14",
    "description": `What an amazing ride from start to finish.
The animation is top tier, once you get over how different it looks from everything else.
The attention to detail is amazing (how Tsukimoto's little foot dash things are sci-fi-ish in nature when he's in robot mode, while Hoshino's are the cartoony hand drawn style is just incredible).
Not to mention how it all feeds into telling the story so damn well.`,
    "tags": ["show", "anime"],
  }, {
    "title": "Puss in Boots: The Last Wish",
    "link": "https://www.imdb.com/title/tt3915174/",
    "score": 7.75,
    "reviewed_at": "2023-02-18",
    "tags": ["movie"],
  }, {
    "title": "Submarine",
    "link": "https://www.imdb.com/title/tt1440292/",
    "score": 7.5,
    "reviewed_at": "2023-02-18",
    "description": "Absurd, but in the absurdist painting sense",
    "tags": ["movie"],
  }, {
    "title": "Ghosts",
    "link": "https://www.imdb.com/title/tt8594324/",
    "score": 8,
    "reviewed_at": "2023-03-12",
    "tags": ["show"],
  }, {
    "title": "We Have a Ghost",
    "link": "https://www.imdb.com/title/tt7798604/",
    "score": 5.5,
    "reviewed_at": "2023-02-25",
    "description": "Halfway between E.T. and Ghostbusters. Watchable",
    "tags": ["movie"],
  }, {
    "title": "Color Out of Space",
    "link": "https://www.imdb.com/title/tt5073642/",
    "score": 3,
    "reviewed_at": "2022-12-26",
    "description": "??? The original story is infinitely better",
    "tags": ["movie"],
  }, {
    "title": "Warning",
    "link": "https://www.imdb.com/title/tt8956324/",
    "score": 3,
    "reviewed_at": "2022-09-16",
    "description": "Weird pacing, some of the stories added nothing to the overall plot. If it had been framed as a group of individual explorations og sci-fi concepts, it might have been better. The ending was eye-rollingly cringe",
    "tags": ["movie"],
  }, {
    "title": "Widows",
    "link": "https://www.imdb.com/title/tt4218572/",
    "score": 5,
    "reviewed_at": "2022-07-17",
    "description": "Good acting, below average story with some peaks",
    "tags": ["movie"],
  }, {
    "title": "Hello, My Name Is Doris",
    "link": "https://www.imdb.com/title/tt3766394/",
    "score": 7.5,
    "reviewed_at": "2022-07-17",
    "tags": ["movie"],
  }, {
    "title": "Infinite",
    "link": "https://www.imdb.com/title/tt6654210/",
    "score": 5.5,
    "reviewed_at": "2022-07-17",
    "description": "Bland",
    "tags": ["movie"],
  }, {
    "title": "The Immigrant",
    "link": "https://www.imdb.com/title/tt1951181/",
    "score": 6,
    "reviewed_at": "2022-07-13",
    "tags": ["movie"],
  }, {
    "title": "Son of Rambow",
    "link": "https://www.imdb.com/title/tt0845046/",
    "score": 6,
    "reviewed_at": "2022-07-13",
    "tags": ["movie"],
  }, {
    "title": "Cut Throat City",
    "link": "https://www.imdb.com/title/tt3547306/",
    "score": 6,
    "reviewed_at": "2022-01-04",
    "tags": ["movie"],
  }, {
    "title": "Conan the Barbarian",
    "link": "https://www.imdb.com/title/tt0082198/",
    "score": 6.5,
    "reviewed_at": "2023-03-19",
    "tags": ["movie"],
  }, {
    "title": "Willow",
    "link": "https://www.imdb.com/title/tt0096446/",
    "score": 7.5,
    "reviewed_at": "2023-03-19",
    "tags": ["movie"],
  }, {
    "title": "Dodgeball: A True Underdog Story",
    "link": "https://www.imdb.com/title/tt0364725/",
    "score": 6,
    "reviewed_at": "2023-03-24",
    "tags": ["movie"],
  }, {
    "title": "Glass Onion: A Knives Out Mystery",
    "link": "https://www.imdb.com/title/tt11564570/",
    "score": 7.5,
    "reviewed_at": "2023-03-24",
    "description": "Not really the same genre as Knives Out, but a fun ride nontheless",
    "tags": ["movie"],
  }, {
    "title": "Ratatouille",
    "link": "https://www.imdb.com/title/tt0382932/",
    "score": 7,
    "reviewed_at": "2023-03-31",
    "tags": ["movie"],
  }, {
    "title": "Bullet Train",
    "link": "https://www.imdb.com/title/tt12593682/",
    "score": 8,
    "reviewed_at": "2023-04-02",
    "description": "What Baccano! should have been (yes, I know it's based on a book and has nothing to do with Baccano!, but you can't say that there aren't enough parallels to justify the comparison)",
    "tags": ["movie"],
  }, {
    "title": "Baccano!",
    "link": "https://myanimelist.net/anime/2251/Baccano/",
    "score": 5,
    "description": `SPOILERS! The show had a great start, and just fumbled the ending completely, to the point where I lost basically all interest.
The entire premise of the show is based on having a set amount of characters whose storylines slowly converge. This is handled fantastically for about 80% of the plotlines.
The first plotline we ever get introduced to is an old man reading a story to a young girl. Seemingly, this plotline was just completely forgotten, as it's brought up maybe one more time, but never goes anywhere.
The plotline of the guy in the white tux gets about 75% done, then just stops.

"You need to watch the OVAs!", you say. First of all, the story already concluded. You can't just patch together a second ending because you forgot to end some plotlines. Second of all, within the first 5 minutes of the first OVA, we:
1) Are off the train (which was the entire premise of the show)
2) Introduce new characters (completely missing the point of what made the original premise so interesting)
I stopped watching halfway through the first OVA, just because it felt like a desperate attempt to either keep the money flowing, or to "fix" the misses in the actual ending.

If it had resolved the remaining plotlines within the premise of the train, and not start introducing new characters, this would easily have been an 8/10. It's honestly sad that they fumbled the ending so hard.`,
    "reviewed_at": "2023-04-02",
    "tags": ["show", "anime"],
  }, {
    "title": "Gulltransporten",
    "link": "https://www.imdb.com/title/tt18092672/",
    "score": 7,
    "reviewed_at": "2023-04-10",
    "tags": ["movie"],
  }, {
    "title": "Kung Pow: Enter the Fist",
    "link": "https://www.imdb.com/title/tt0240468/",
    "score": 7.5,
    "description": "What the fuck?",
    "reviewed_at": "2023-04-11",
    "tags": ["movie"],
  }, {
    "title": "Foundation",
    "link": "https://www.imdb.com/title/tt0804484/",
    "score": 7.5,
    "reviewed_at": "2023-04-14",
    "tags": ["show"],
  }, {
    "title": "1899",
    "link": "https://www.imdb.com/title/tt9319668/",
    "score": 7.5,
    "reviewed_at": "2023-04-14",
    "description": "Shame it got cancelled",
    "tags": ["show"],
  }, {
    "title": "Kevin Can F**k Himself",
    "link": "https://www.imdb.com/title/tt9257258/",
    "score": 8,
    "reviewed_at": "2023-04-14",
    "description": `A show about showing how messed up life would be if you lived around a sitcom main character, since they are rarely - if ever - a good person.
It does a fantastic job of this by constantly shifting between a sitcom format when the titular Kevin is around, and a seriously shot drama piece the rest of the time.
It all really highlights how much presentation can condition us into thinking something very much not funny to be funny, as long as you don't dwell too much on it.
Ran for the perfect amount of time, given the subject matter, and stuck the landing beautifully.`,
    "tags": ["show"],
  }, {
    "title": "The White Lotus",
    "link": "https://www.imdb.com/title/tt13406094/",
    "score": 7,
    "reviewed_at": "2023-04-15",
    "description": "Very well written and acted for a show that's basically just a long commercial for the travel industry with no real plot",
    "tags": ["show"],
  }, {
    "title": "The Bear",
    "link": "https://www.imdb.com/title/tt14452776/",
    "score": 8.75,
    "reviewed_at": "2023-04-16",
    "description": "Anxiety s(t)imulator, but in a good way",
    "tags": ["show"],
  }, {
    "title": "Fleishman is in Trouble",
    "link": "https://www.imdb.com/title/tt11527058/",
    "score": 7.5,
    "reviewed_at": "2023-04-18",
    "description": "It's weid that we still need to tell people, even 40-somethings apparently, that people are in fact people. Would be a solid 6 if it weren't for the excellent writing and acting",
    "tags": ["show"],
  }, {
    "title": "Mamma Mia! Here We Go Again",
    "link": "https://www.imdb.com/title/tt6911608/",
    "score": 4.5,
    "reviewed_at": "2023-05-07",
    "description": "Two hours of absolutely nothing happening, followed by a Cher and Meryl Streep cameo. All set to an ABBA soundtrack, which is why the score isn't lower",
    "tags": ["movie", "musical"],
  }, {
    "title": "Dungeons & Dragons: Honor Among Thieves",
    "link": "https://www.imdb.com/title/tt2906216/",
    "score": 6.5,
    "reviewed_at": "2023-06-17",
    "description": "The pacing in the very beginning was way off, but got better after the story actually starts. Puppetry was top tier",
    "tags": ["movie"],
  }, {
    "title": "The Super Mario Bros. Movie",
    "link": "https://www.imdb.com/title/tt6718170/",
    "score": 6,
    "reviewed_at": "2023-06-29",
    "description": "Incredibly safe. None of the celebrity actors really sounded like themselves, surprisingly... aside from the DK laughs",
    "tags": ["movie"],
  }, {
    "title": "Bram Stoker's Dracula",
    "link": "https://www.imdb.com/title/tt0103874/",
    "score": 6,
    "reviewed_at": "2023-07-01",
    "description": "Beautifully shot, incredibly disjointed. Probably mostly because the time and space skips feel like scene transitions, and not that actual movement happened",
    "tags": ["movie"],
  }, {
    "title": "The Amazing Maurice",
    "link": "https://www.imdb.com/title/tt10473036/",
    "score": 6,
    "reviewed_at": "2023-07-01",
    "description": "Haven't read the book yet, but it's an alright kids movie",
    "tags": ["movie"],
  }, {
    "title": "RRR",
    "link": "https://www.imdb.com/title/tt8178634/",
    "score": 7.5,
    "reviewed_at": "2023-07-01",
    "description": "Everything I expected and more",
    "tags": ["movie"],
  }, {
    "title": "Willy Wonka & the Chocolate Factory",
    "link": "https://www.imdb.com/title/tt0067992/",
    "score": 9,
    "reviewed_at": "2023-07-27",
    "description": "Fantastic representation of the madman Wonka is, from Wilder's acting to the set decor truly looking like someone mad went to town on an old factory. And yet, he is one of two decent adults in the entire film.",
    "tags": ["movie", "musical"],
  }, {
    "title": "Waterworld",
    "link": "https://www.imdb.com/title/tt0114898/",
    "score": 6,
    "reviewed_at": "2023-07-08",
    "tags": ["movie"],
  }, {
    "title": "King Arthur: Legend of the Sword",
    "link": "https://www.imdb.com/title/tt1972591/",
    "score": 7,
    "reviewed_at": "2023-07-09",
    "description": "I feel like this would have been better as a standalone fantasy movie, rather than trying to coopt Arthurian legend",
    "tags": ["movie"],
  }, {
    "title": "Snowpiercer",
    "link": "https://www.imdb.com/title/tt1706620/",
    "score": 6.5,
    "reviewed_at": "2023-07-30",
    "description": "Weird",
    "tags": ["movie"],
  }, {
    "title": "Pikmin 4",
    "link": "https://www.nintendo.com/store/products/pikmin-4-switch/",
    "score": 7.5,
    "reviewed_at": "2023-08-20",
    "description": "Don't care much for the hectic dandori stuff, but Pikmin is always a hoot.",
    "tags": ["game"],
  }, {
    "title": "The Legend of Zelda: Tears of the Kingdom",
    "link": "https://www.nintendo.com/store/products/the-legend-of-zelda-tears-of-the-kingdom-switch/",
    "score": 9.5,
    "reviewed_at": "2023-08-24",
    "description": "What a game",
    "tags": ["game"],
  }, {
    "title": "The Black Cauldron",
    "link": "https://www.imdb.com/title/tt0088814/",
    "score": 7,
    "reviewed_at": "2023-80-29",
    "description": "Beautiful animation",
    "tags": ["movie"],
  }, {
    "title": "Hogwarts Legacy",
    "link": "https://store.steampowered.com/app/990080/Hogwarts_Legacy/",
    "score": 6,
    "reviewed_at": "2023-08-30",
    "description": `Where do you even start? The ubisoft open world design? The characters that you're not really given a reason to care about? The fact that 90% of the game feels like a generic fantasy thing, with no relation to the franchise whatsoever? The combat at least starts out fun, but quickly devolves into tedium (although unlocking the explosive barrel thing near the end was a nice change of pace).

This is a mediocre game by most metrics. Any open world game has two tasks to fulfill:
1) Have a big, sprawling, beautiful open world - this game checks that box.
2) Make the world feel rewarding to explore (not just through sheer amount of content, but also through variety) - this is where the game (like any other ubisoft open world game) fails.

There are a lot of things I could go into and nitpick (the console-first design that cripples the PC experience, the map being SO SLOW TO OPEN PLEASE I JUST WANT TO LOOK WHERE I'M GOING, the same four-ish enemies over and over, ...), but I'll simply say this:
The focus in development was clearly the quests. Follow the developers directive, and focus on the quests as well. Ignore actually exploring the world, and just look at it as it passes by below, when you fly on your broom. If you like Harry Potter, this'll scratch that itch.

And yes, I did 100% the game.`,
    "tags": ["game"],
  }]
};