PLAYLISTS.add('', [
  {id: 'dQw4w9WgXcQ', title: 'Never Gonna Give You Up'},
  {id: '90qT9ZNy2bo', title: 'Wii Shop Channel Music and there is absolutely nothing wrong with it whatsoever'},
  {id: 'lXMskKTw3Bc', title: 'Never Gonna Hit Those Notes'},
  {id: 'ykwqXuMPsoc', title: 'Narwhals'},
  {id: 'NN75im_us4k', title: 'Never Gonna Give Your Teen Spirit Up'},
  {id: '4WgT9gy4zQA', title: 'Ultimate showdown'},
  {id: 'k85mRPqvMbE', title: 'Crazy Frog - Axel F'},
  {id: 'astISOttCQ0', title: 'The Gummy Bear Song'},
  {id: 'N_x72hA7_SY', title: 'Dragonstea Din Tei (Numa Numa)'},
  {id: 'J_DV9b0x7v4', title: 'Caramelldansen'},
  {id: 'J---aiyznGQ', title: 'Keyboard Cat (RIP)'},
  {id: 'wGlBwW7f5HA', title: '( ͡° ͜ʖ ͡°)'},
  {id: '1wnE4vF9CQ4', title: 'Ieva\'s Polka (Leek Spin)'},
  {id: 'p3G5IXn0K7A', title: 'Hamsterdance'},
  {id: 'QH2-TGUlwu4', title: 'Nyan Cat'},
  {id: 'q6EoRBvdVPQ', title: 'YEEEEEEE'},
  {id: 'Y4QGPWLY-EM', title: 'YO LISTEN UP HERE\'S THE STORY'},
  {id: 'EwTZ2xpQwpA', title: 'Chocolate Rain'},
  {id: 'iEXPkv7lJgc', title: 'We Are Number One (RIP)'},
  {id: 'Z3ZAGBL6UBA', title: 'It\'s peanut butter jelly time (sorry)'},
  {id: 'uE-1RPDqJAY', title: 'My childhood (They\'re taking the hobbits to Isengard)'},
  {id: 'qmjOd9Dlr34', title: 'Trololololololololo'},
  {id: 'aKULi72yUko', title: 'Manamanah'},
  {id: 'eDU0CTDMk2g', title: 'Do You Like Waffles?'},
  {id: 'kFF3pVOHtoA', title: 'Schfifty Five'},
  {id: 'ENnAa7rqtBM', title: 'Everyone else has had more sex than me (unrelated but it\'s also the song title)'},
  {id: 'QTqD7I3Dksw', title: 'Up butt coconut'},
  {id: 'KMYN4djSq7o', title: 'The Llama Song'},
  {id: 'UcwfEMdV-aM', title: 'MY ANUS IS BLEEDING'},
  {id: 'c71RCAyLS1M', title: 'Living in the Sunlight'},
  {id: 'HEXWRTEbj1I', title: 'Vladislav'},
  {id: '5xxQs34UMx4', title: 'The Shrek Song'},
  {id: 'y6120QOlsfU', title: 'That one song no one can ever remember the name of'},
  {id: 'y983TDjoglQ', title: 'HOW COULD THIS HAPPEN TO MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE'},
  {id: 'ZZ5LpwO-An4', title: 'The He-man song'},
  {id: 'TKfS5zVfGBc', title: 'free cheat codez for gta:sa realy easy!!'},
  {id: 'thhaf-bKWyg', title: 'The inferior version of HOW COULD THIS HAPPEN TO MEEEEEEEEEEEEEEEEEEEEEEEEEEE'},
  {id: 'Ijhhe8Q_dQs', title: 'The most inspiring song ever'},
  {id: 'ahdH8eTydWY', title: 'Ladies and gentlemen, we got \'em'},
  {id: 'UcLph-scF-0', title: 'Blue eyes white skeleton song'},
  {id: 'E9s1ltPGQOo', title: 'It\'s just the Mii Channel music'},
  {id: 'ygI-2F8ApUM', title: 'Superior LOTR'},
  {id: 'AO6ePzKVeuE', title: 'Hey wanna go shopping with Mr Skeltal?'},
  {id: '0L_kQ_wbsAM', title: 'A singular doot'},
  {id: 'Oa-ae6_okmg', title: 'For when you are surrounded by faces that are familiar'},
  {id: '4zLfCnGVeL4', title: 'Hola oscuridad, mi viejo amigo'},
  {id: 'rvrZJ5C_Nwg', title: 'Old man yells at mountain'},
  {id: 'j6KnvkEPAZg', title: 'Big Iron'},
  {id: 'feA64wXhbjo', title: 'Gunfire at the Oscars'},
  {id: '-1dSY6ZuXEY', title: 'Spooky Scary Skeletons'},
  {id: '4aneAWxzOUk', title: 'Don\'t Stop Me (from hitting those notes) Now'},
  {id: '5FjWe31S_0g', title: 'Fuck this shit I\'m out'},
  {id: 'djV11Xbc914', title: 'Take On Me (it\'s a meme if you count the WHEN YOU X WITH YOUR MATES videos)'},
  {id: '1vrEljMfXYo', title: 'Take Me Home, Country Roads'},
  {id: 'umAL-6-j1Ew', title: 'That one really annoying one'},
  {id: 'aQkPcPqTq4M', title: '𝒶 𝑒 𝓈 𝓉 𝒽 𝑒 𝓉 𝒾 𝒸'},
  {id: 'U06jlgpMtQs', title: 'For when you bleed red'},
  {id: 'aiSdTQ9DW9g', title: 'Rasputin'},
  {id: 'dP9Wp6QVbsk', title: 'Die Woodys'},
  {id: 'izGwDsrQ1eQ', title: 'Winking emoji'},
  {id: 'PGNiXGX2nLU', title: 'The Beyblade song'},
  {id: 'Hy8kmNEo1i8', title: 'The poop fetishist'},
  {id: '6W5pq4bIzIw', title: 'Boombastic'},
  {id: '6E5m_XtCX3c', title: 'Ocean Man'},
  {id: 'vTIIMJ9tUc8', title: 'Tunak Tunak Tun'},
  {id: 'SDklocLs8mU', title: 'Early 2000s emo kid anthem'},
  {id: 'K5tVbVu9Mkg', title: 'Cook by the book, bitch'},
  {id: 'fbGkxcY7YFU', title: 'What What (in the Butt)'},
  {id: 'gy1B3agGNxw', title: 'Epic Sax Guy'},
  {id: 'kfVsfOSbJY0', title: 'That one between Thursday and Saturday'},
  {id: '9bZkp7q19f0', title: 'Gangnam style'},
  {id: 'AZFuvVdIgSw', title: 'Rappin\' For Jesus'},
  {id: 'jofNR_WkoCE', title: 'They bark jesus christ they\'re basically dogs what did you expect'},
  {id: '9FISHEO3gsM', title: 'Rebecca Dylan'},
  {id: '-TTgXfO7CRI', title: 'S3RLY Astley'},
  {id: 'SQTcRxPsoMo', title: 'MTC'},
  {id: '8d44ykdKvCw', title: 'VI SITTER HÄR I VENTEN'},
  {id: 'tesr1OyymXo', title: '100 miles'},
]);