PLAYLISTS.add('memes', [
  {id: 'lrzKT-dFUjE', title: 'The Ultimate Showdown'},
  {id: 'EIyixC9NsLI', title: 'Badgers'},
  {id: 'ykwqXuMPsoc', title: 'Narwhals'},
  {id: 'GUl9_5kK9ts', title: 'Amazing Horse'},
  {id: 'xJk4ozazAQo', title: 'Hot Tamales'},
  {id: 'au3-hk-pXsM', title: 'Magical Trevor'},
  {id: 'dQw4w9WgXcQ', title: 'Totally Not Never Gonna Give You Up'},
  {id: 'k85mRPqvMbE', title: 'Crazy Frog'},
  {id: 'astISOttCQ0', title: 'The Gummy Bear Song'},
  {id: 'HPPj6viIBmU', title: 'Star Wars Kid'},
  {id: 'KmtzQCSh6xk', title: 'Numa Numa Guy'},
  {id: 'J_DV9b0x7v4', title: 'Caramelldansen'},
  {id: 'dMH0bHeiRNg', title: 'Evolution of Dance'},
  {id: '1wnE4vF9CQ4', title: 'Leek Spin (Ieva\'s Polka)'},
  {id: 'p3G5IXn0K7A', title: 'Hamsterdance'},
  {id: 'y8Kyi0WNg40', title: 'Dramatic Look'},
  {id: 'QH2-TGUlwu4', title: 'Nyan Cat'},
  {id: 'kuNixp-wvWM', title: 'Fukkireta'},
  {id: 'Y4QGPWLY-EM', title: 'YO LISTEN UP HERE\'S THE STORY'},
  {id: 'Yavx9yxTrsw', title: 'Boxxy'},
  {id: '9bKALqPuqzs', title: 'Shoop da Whoop'},
  {id: 'rNdM8cFuOXg', title: 'Everybody'},
  {id: 'SiMHTK15Pik', title: '9001'},
  {id: 'QkWS9PiXekE', title: 'This is Sparta!'},
  {id: '8fvTxv46ano', title: 'All Your Base Are Belong To Us'},
  {id: 'WEP1G6PcQO8', title: 'Crazy Frog Brothers'},
  {id: 'EwTZ2xpQwpA', title: 'Chocolate Rain'},
  {id: 'WqSTXuJeTks', title: 'Leave Britney Alone'},
  {id: 'mLyOj_QD4a4', title: 'Leeroy Jenkins'},
  {id: 'wCF3ywukQYA', title: 'Shoes'},
  {id: 'Z3ZAGBL6UBA', title: 'It\'s Peanut Butter Jelly Time'},
  {id: 'uE-1RPDqJAY', title: 'They\'re Taking the Hobbits to Isengard'},
  {id: 'kawTlZnZ294', title: 'Pingas'},
  {id: 'H91rPIq2mN4', title: 'WTF BOOM'},
  {id: 'Lefg5JxFxIs', title: 'Lotsa Spaghetti!'},
  {id: 'nEqwKNNQBwc', title: 'Fred (Sorry)'},
  {id: 'u8LPD6W0PZw', title: 'Hamoud Habibi'},
  {id: 'UD-MkihnOXg', title: 'Idk a hippo sings "The Lion Sleep Tonight" I saw it everywhere'},
  {id: 'aKULi72yUko', title: 'Manamanah'},
  {id: 'wpVTORX_ifk', title: 'Salad Fingers'},
  {id: 'av8OQLaKHKM', title: 'Happy Tree Friends'},
  {id: 'eDU0CTDMk2g', title: 'Do You Like Waffles?'},
  {id: 'kCpjgl2baLs', title: 'The End of the World (aka "But I\'m Le Tired")'},
  {id: 'JAFQFvSPhQ8', title: 'The Italian Man Who Went To Malta'},
  {id: '1py7wzaHkz4', title: 'Thwomp - The Movie'},
  {id: 'kFF3pVOHtoA', title: 'Schfifty Five'},
  {id: 'Xdwze-Wj6_4', title: 'Ignorance is Bliss'},
  {id: 'ENnAa7rqtBM', title: 'Everyone Else Has Had More Sex Than Me (unrelated but it\'s also the song title)'},
  {id: 'QTqD7I3Dksw', title: 'Up Butt Coconut'},
  {id: 'KMYN4djSq7o', title: 'The Llama Song'},
  {id: 'UcwfEMdV-aM', title: 'MY ANUS IS BLEEDING!'},
  {id: 'jmIAM-hnEjQ', title: 'Zelda CGI YTP'},
  {id: '-5x5OXfe9KY', title: 'Oogachaka Baby'},
  {id: '3rzgrP7VA_Q', title: 'What Is Love'},
  {id: '5xxQs34UMx4', title: 'The Shrek Song'},
  {id: 'y6120QOlsfU', title: 'I don\'t remember what this song is called'},
  {id: 'Jx_O6PHdWww', title: 'Hey Ya'},
  {id: 'wGlBwW7f5HA', title: '( ͡° ͜ʖ ͡°)'},
  {id: 'ymNFyxvIdaM', title: 'Freestyler'},
  {id: 'Soa3gO7tL-c', title: 'I WALK A LONELY ROAD'},
  {id: 'y983TDjoglQ', title: 'HOW COULD THIS HAPPEN TO MEEEEE'},
  {id: 'FR7wOGyAzpw', title: 'HEYYEYAAEYAAAEYAEYAA'},
  {id: 'TKfS5zVfGBc', title: 'Trance - 009 Sound System Dreamscape (aka "Helo Guise todey i will show u how to...")'},
  {id: 'thhaf-bKWyg', title: 'The inferior version of HOW COULD THIS HAPPEN TO MEEEEEEEEEEEEEEEEEEEEEEEEEEE'},
  {id: 'Ijhhe8Q_dQs', title: 'The Most Inspiring Song Ever'},
  {id: 'ZnBLyMTHDps', title: 'Baby Monkey'},
  {id: '5Cjrp23lBSM', title: 'Counter-Strike - DE_dust2'},
  {id: '-1dSY6ZuXEY', title: 'Spooky Scary Skeletons'},
  {id: 'dCrLMwDz5qE', title: 'Pika Girl (and just all S3RL songs in general)'},
  {id: '8d44ykdKvCw', title: 'VI SITTER HÄR I VENTEN'},
  {id: '4TfNpkfALqE', title: 'chili.wmv'},
  {id: 'StvcDAHF7uo', title: 'The Link Song by Totally Not System of a Down™'},
  {id: 'gy1B3agGNxw', title: 'Epic Sax Guy'},
  {id: '2fxVeAVl2I8', title: 'The Silly Adventures of Mr. Mochi'},
  {id: 'N5TWbeav7hI', title: 'DELETE THIS'},
  {id: 'WWpZC1bKfX8', title: 'You know what this is'},
  {id: 'RZ1dbHa9veo', title: 'Aragorn Kommer'},
  {id: 'an_8U-GDgwc', title: 'Ansiktsburk'},
  {id: '4OhnU5WfDdQ', title: 'Sagan om Saftkalaset'},
  {id: 'FVrZPuJzCCA', title: 'Sagan om de Bannlysta'},
  {id: 'MZnyWLnOvbU', title: 'Eat the ketchup!'},
  {id: 'SRVEvTW6_Wo', title: 'omg!(Morrowind'},
  {id: 'Not-WhwwnNo', title: 'The Don Keyote Saga'},
  {id: 'V6WP5GQ6iFo', title: 'The Light of Courage'},
  {id: 'DKliGeiNRBE', title: 'Super Mario Hyadian'},
  {id: 'OLCs8RhW6rk', title: 'Numa Numa Oblivion (I think I watched this once but it stuck in my memory for whatever reason)'},
  {id: 'lXMskKTw3Bc', title: 'Never Gonna Hit Those Notes'},
  {id: '90qT9ZNy2bo', title: 'Wii Shop Channel Music and there is absolutely nothing wrong with it whatsoever'},
  {id: 'NN75im_us4k', title: 'Never Gonna Give Your Teen Spirit Up'},
  {id: 'N_x72hA7_SY', title: 'Dragonstea Din Tei (Numa Numa)'},
  {id: 'J---aiyznGQ', title: 'Keyboard Cat (RIP)'},
  {id: 'q6EoRBvdVPQ', title: 'YEEEEEEE'},
  {id: 'iEXPkv7lJgc', title: 'We Are Number One (RIP)'},
  {id: 'qmjOd9Dlr34', title: 'Trololololololololo'},
  {id: 'ahdH8eTydWY', title: 'Ladies and gentlemen, we got \'em'},
  {id: 'UcLph-scF-0', title: 'Blue eyes white skeleton song'},
  {id: 'E9s1ltPGQOo', title: 'It\'s just the Mii Channel music'},
  {id: 'ygI-2F8ApUM', title: 'Far better hero\'s journey than whatever the fuck LOTR was'},
  {id: 'AO6ePzKVeuE', title: 'Wii Shop Channel but actually lmao gotem'},
  {id: 'WTWyosdkx44', title: 'Doot'},
  {id: 'ZUtAe5PUKtE', title: 'For when you are surrounded by faces that are familiar'},
  {id: 'l0q7MLPo-u8', title: 'Hola oscuridad, mi viejo amigo'},
  {id: 'rvrZJ5C_Nwg', title: 'Old man yells at mountain'},
  {id: 'FiDvxZdQgQs', title: 'Big Iron'},
  {id: 'feA64wXhbjo', title: 'Falling or something idk'},
  {id: '4aneAWxzOUk', title: 'Don\'t Stop Me (from hitting those notes) Now'},
  {id: '5FjWe31S_0g', title: 'Fuck this shit I\'m out'},
  {id: 'djV11Xbc914', title: 'Take On Me (it\'s a meme if you count the WHEN YOU X WITH YOUR MATES videos)'},
  {id: 'umAL-6-j1Ew', title: 'That one really annoying one'},
  {id: 'aQkPcPqTq4M', title: '𝒶 𝑒 𝓈 𝓉 𝒽 𝑒 𝓉 𝒾 𝒸'},
  {id: 'U06jlgpMtQs', title: 'For when you bleed red'},
  {id: '0wDUNz6ZuWs', title: 'Die Woodys'},
  {id: 'izGwDsrQ1eQ', title: 'Winking emoji'},
  {id: 'PGNiXGX2nLU', title: 'The Beyblade song'},
  {id: 'Hy8kmNEo1i8', title: 'The poop fetishist'},
  {id: '6W5pq4bIzIw', title: 'Boombastic'},
  {id: '6E5m_XtCX3c', title: 'Ocean Man'},
  {id: 'vTIIMJ9tUc8', title: 'Tunak Tunak Tun'},
  {id: 'SDklocLs8mU', title: 'Early 2000s emo kid anthem'},
  {id: 'K5tVbVu9Mkg', title: 'Cook by the book, bitch'},
  {id: 'fbGkxcY7YFU', title: 'What What (in the Butt)'},
  {id: 'kfVsfOSbJY0', title: 'That one between Thursday and Saturday'},
  {id: '9bZkp7q19f0', title: 'Gangnam style'},
  {id: 'AZFuvVdIgSw', title: 'Rappin\' For Jesus'},
  {id: 'jofNR_WkoCE', title: 'They bark jesus christ they\'re basically dogs what did you expect'},
  {id: '9FISHEO3gsM', title: 'Rebecca Dylan'},
  {id: 'wj-T9LC8VQU', title: 'S3RLY Astley'},
  {id: 'SQTcRxPsoMo', title: 'MTC'},
  {id: 'tesr1OyymXo', title: '100 miles'},
]);