PLAYLISTS.add('music', [
  {id: 'NOAeVINQ6Hw', title: 'Neon Trees - First Things First'},
  {id: '6FhHHmDn26E', title: 'Lyla Foy - Impossible'},
  {id: 'ZzFYmz2lfT4', title: 'Christine and The Queens - Saint Claude'},
  {id: 'Z179ZItWFRQ', title: 'Kevin Morby - Parade'},
  {id: 'bcnIhzaDTd0', title: 'Courtney Barnett - Avant Gardener'},
  {id: 'K7VZNH3t71Y', title: 'Funeral Suits - All Those Friendly People'},
  {id: 'm1jv7D85x-0', title: 'alt-J - Breezeblocks'},
  {id: 'KrA6Sbf1QQI', title: 'Ariana Kim - Steve Reich Duet for two violins and strings'},
  {id: 'puzGZnsJkDg', title: 'Penguin Cafe Orchestra - Perpetuum Mobile'},
  {id: 'dWMN-vIGPDo', title: 'Sarah Modene - Searching'},
  {id: 'ouuqJ0pkWvU', title: 'Har Mar Superstar - Lady, You Shot Me'},
  {id: 'mckYvBze9YA', title: 'The Voidz - Human Sadness'},
  {id: '24JIe0fKNHU', title: 'Daughter - Youth'},
  {id: 'dm87PN-fTlg', title: 'Bonjr - it\'s ok, you\'re ok'},
  {id: 'MSQ95DcgWYI', title: 'Brand New - Jesus Christ'},
  {id: '6nYRlNvtIkA', title: 'Crywank - It\'s Ok I Wouldn\'t Remember Me Either'},
  {id: 'jyv0J_luOIQ', title: 'Seth Corbin - The Alcohol Song'},
  {id: 'qZ_WVsP9RkE', title: 'dandelion hands - how to never stop being sad'},
  {id: 'yOqcn3iJbPo', title: 'Johnny Goth - Feels like We\'re Dying'},
  {id: 'unEcx6eT5h4', title: 'Cyberbully Mom Club - Better Than That'},
  {id: 'ceTmelPHCcg', title: 'Naps - Social Skills'},
  {id: 'ndlb4fic-eQ', title: 'Andy Shauf - Quite Like You'},
  {id: '8YiDQk6Bgik', title: 'Good Morning - Warned You'},
  {id: 'l1TYsJFkoUo', title: 'Craft Spells - Nausea'},
  {id: 'oitQ1-e9JQk', title: 'Richard Orofino - i heard you were looking like the moon'},
  {id: 'Jzs3pkM5Xx8', title: 'Concorde - Sons'},
  {id: 'WMrU3f5QQR8', title: 'Modern Baseball - How Do I Tell A Girl I Want To Kiss Her?'},
  {id: 'vNiUIBxf004', title: 'Wavves - Come Down'},
  {id: 'n1ATz2ocOsk', title: 'Wavves - Heavy Metal Detox'},
  {id: '4L3yLmCCZUo', title: 'Mars Water - Where the Sun Sets'},
  {id: '_W_GS2s7yKw', title: 'It Looks Sad - Creature'},
  {id: 'jvVXFxcCEIQ', title: 'We Were Promised Jetpacks - Quiet Little Voices'},
  {id: '_emKxC9kTJc', title: 'TOTORRO - Brocolissimo'},
  {id: 'k6Ae0GGrtr8', title: 'We Lost the Sea - Bogatyri'},
  {id: 'mnMZS0SyHgs', title: 'Paint the Sky Red - A Light For Every Shadow'},
  {id: '0SeI-VIOqO8', title: 'Clever Girl - Elm'},
  {id: '-MhYucHPYq4', title: 'Molecules To Minds - We Belong in a Movie'},
  {id: 'P99rfsrqrCU', title: 'Saint Romain - i was all you needed'},
  {id: 'f1i2H63GDHs', title: 'Oberhofer - Sea of Dreams'},
  {id: 'xeNZwHKYAmk', title: 'Beaux Arts Trio - Schubert: Adagio in E flat, Op.posth. 148 D.897 Notturno'},
  {id: 'GG4aNiGswNQ', title: 'Saint Motel - Cold Cold Man'},
  {id: 'R2ct_Gkq-HQ', title: 'Sin Shake Sin - Can\'t Go To Hell'},
  {id: 'xGw6BFQfDhQ', title: 'Tank and the Bangas - Oh Heart'},
  {id: '-Tl20WUl0_c', title: 'Jenny Owen Youngs - Wake Up'},
  {id: 'Lsb5MGJwabI', title: 'Jonquil - Lions'},
  {id: 'VHb_XIql_gU', title: 'MGMT - Kids'},
  {id: 's0kQoiKpdls', title: 'Etta - Pressure Pusher'},
  {id: 'E6z05SnCB4c', title: 'Boy Scouts - Did You See Me Cry'},
  {id: 'RBpLVXNN6i0', title: 'Tessa Violet - Interlude III'},
  {id: 'ADJiK-X1Vm4', title: 'Diane Coffee - Mayflower'},
  {id: 'f9X1C7pTu-M', title: 'Beach House - Space Song'},
  {id: '2teI5QGA9ck', title: 'Smoke Season - Good Days'},
  {id: 'UcK7vaya5Lw', title: 'Madden - Alive'},
  {id: '5wh7ylJManI', title: 'Grateful Dead - Ripple'},
  {id: 'rPsuvNEBP_Q', title: 'Virgin Magnetic Material - Make It Wit Chu'},
  {id: 'SDTZ7iX4vTQ', title: 'Foster The People - Pumped up Kicks'},
  {id: 'lYcp1bUb4lU', title: 'Hazel English - I\'m Fine'},
  {id: 'tcHTwBnIOBM', title: 'Feldberg - You & Me'},
  {id: 'OUK-_5amoow', title: 'Concorde - Just Kiss Her'},
  {id: 'UURm6TA_unI', title: 'Parks, Squares and Alleys - We\'re Not Just Friends'},
  {id: 'c7-4IZyNUtA', title: 'José González - Step Out'},
  {id: 'vqc2uOunPdA', title: 'Radical Face - Always Gold'},
  {id: '3JdWlSF195Y', title: 'They Might Be Giants - Why Does the Sun Shine?'},
  {id: 'jeo3an2M_Lo', title: 'Glass Animals - Gooey'},
  {id: 'aFbIWCr_6jM', title: 'The Kills - Future Starts Slow'},
  {id: 'yHm1F2cI0Gw', title: 'Warhaus - Machinery'},
  {id: '_VLUNA7GgvE', title: 'If Anything Happens To The Cat - Echo Park'},
  {id: 'MS9sR0klkGo', title: 'Oh the Larceny - Check It Out'},
  {id: '_pyvv-Cpr0A', title: 'Envoi - From a Cage'},
  {id: '-4VCON78Ckw', title: 'Saint PHNX - King'},
  {id: '_GipmdQMeFQ', title: 'Badflower - Animal'},
  {id: '50D-rQplEh8', title: 'Owl John - Songs About Roses'},
  {id: '828CQT7D7sI', title: 'Malcolm Middleton - Ballad Of Fuck All'},
  {id: 'gr2tweWYxUY', title: 'There Will Be Fireworks - Here Is Where'},
  {id: '_ZCu7qAGb7k', title: 'I Like Trains - Bethesda'},
  {id: 'jIV1MX88058', title: 'Ghost Atlas - Sacred Organs'},
  {id: 'lxhTU3sRw84', title: 'Tides of Man - A Faint Illusion'},
  {id: '6QUmPZmkr4I', title: 'Caro Emerald - Just One Dance'},
  {id: 'uSQzUx3QW2Y', title: 'Francisco Tárrega - Gran Vals'},
  {id: 'TMSx95iU-yQ', title: 'Blind Guardian - The Bard\'s Song'},
  {id: 'V2XyCLodDA4', title: 'AJJ - Bad Bad Things'},
  {id: 'D7RNQIMf76M', title: 'Dodie - Sick of Losing Soulmates'},
  {id: '3wLLgJ_a7Rs', title: 'Oliver Tree - Alien Boy'},
  {id: '6GGk1Gh8Dug', title: 'Wingnut Dishwashers Union - My Idea of Fun'},
  {id: 'TRS9Bz0IH54', title: 'Johnny Hobo and The Freight Trains - Love Songs for the Apocalypse'},
  {id: 'Gc4sY98Jn9I', title: 'twenty one pilots - Stressed Out'},
  {id: '1vrEljMfXYo', title: 'John Denver - Take Me Home, Country Roads'},
  {id: '0AAbY9Pvp6A', title: 'Chumbawamba - Tubthumping'},
  {id: '87PZgweY-gY', title: 'Wild Child - Crazy Bird'},
  {id: '9GAYTFWrei4', title: 'Phum Viphurit - Lover Boy'},
  {id: 'rGDcbQKxY7Q', title: 'Lily Allen - Smile'},
  {id: '-UH7dU66u4g', title: 'The Decemberists - The Mariner\'s Revenge Song'},
  {id: 'acJ-Wt3rpfc', title: 'Billy Joel - Piano Man'},
  {id: 'oWrKHWpLn0U', title: 'Gravity Rush - Douse Shinundakara'},
  {id: 'x4ByDtKnBlw', title: 'Slaves - Lies'},
  {id: 'tSv04ylc6To', title: 'KOKOROKO - ABUSEY JUNCTION'},
  {id: 'tKYjUn-SBcg', title: 'Crosby, Stills, Nash & Young - Our House'},
  {id: 'ePCiVK5Jjos', title: 'Bob Seger - Night Moves'},
  {id: '5YpEHbnY6mE', title: 'whyetc - xxx (feat. foxgluvv)'},
  {id: 'xID2YbuJ65I', title: 'The Droge and Summers Blend - Two of the Lucky Ones'},
  {id: 'dFM0pUn4dcA', title: 'Doves - Kingdom of Rust'},
  {id: 'B5QhMXV5sXo', title: 'Noah Cyrus - I\'m Stuck'},
  {id: 'xUBYzpCNQ1I', title: 'Bright Eyes - First Day of My Life'},
  {id: 'FsOjAOd7x8Y', title: 'The Record Company - Life To Fix'},
  {id: 'yPt3-lB5Lsc', title: 'Joy Division - Shadowplay'},
  {id: 'XaXoUIOwpG8', title: 'Panama - Destroyer'},
  {id: 'zeGCa40NDSY', title: 'Doc Robinson - Break My Fall'},
  {id: 'h9TlaYxoOO8', title: 'St. Vincent - Los Ageless'},
  {id: 'vkLOg252KRE', title: 'The War on Drugs - Under The Pressure'},
  {id: '3vVSBLkpO-8', title: 'Breakbot - Baby I\'m Yours'},
  {id: 'kBqWtdMpies', title: 'Fort Atlantic - Let Your Heart Hold Fast'},
  {id: 'hjCVZNm4Prs', title: 'Fern Jones - This World Is Not My Home'},
  {id: 'sy4IhE-KAEg', title: 'Pogo - Boy & Bear'},
  {id: 'Xg2kDtJZos8', title: 'KIRBY KRACKLE - Up, Up, Down, Down'},
  {id: 'fBGSJ3sbivI', title: 'Caravan Palace - Rock It For Me'},
  {id: 'gA03iyI3yEA', title: 'On the Edge - AIVA'},
  {id: 'mllzzUjMezU', title: 'Bag Raiders - Shooting Stars'},
  {id: 'G4rcIQpo0QQ', title: 'Trevor Moore - Bullies (feat. Asmeret Ghebremichael)'},
  {id: 'uQUrhYpPra0', title: 'Anna Clendening - To My Parents'},
  {id: '9OyTNVI87Ps', title: 'April Rain - The Projector'},
  {id: 'QAo_Ycocl1E', title: 'Toto - Africa'},
  {id: 'ln7Vn_WKkWU', title: 'Stealers Wheel - Stuck In The Middle With You'},
  {id: 'djAvxUw3dTM', title: 'Funky Smugglers - First Class Lounging'},
  {id: 'Y3DAj_Zu1b8', title: 'Tammany Hall NYC - Cindy'},
  {id: 'cl9ORKDDnCI', title: 'Michael Tolcher - Sooner or Later'},
  {id: 'ae7AACP1-R0', title: 'The Fray - How to Save a Life'},
  {id: 'bgSgXiehbYM', title: 'David Gray - Please Forgive Me'},
  {id: 'Fn58OF_lA-Q', title: 'Weird Al Yankovic - Albuquerque'},
  {id: 'z5OXON8vIaA', title: 'Smash Mouth - Why Can\'t We Be Friends'},
  {id: 'R6m_i3ZWkPM', title: 'The Academic - Why Can\'t We Be Friends?'},
  {id: 'np8SJ_IzkxU', title: 'Bombay - Dolly Doesn\'t Want to Face the Facts'},
  {id: '28tZ-S1LFok', title: 'Phantogram - When I\'m Small'},
  {id: 'elnu8HdJHpc', title: 'cornandbeans - Lazy Summer Days'},
  {id: 'iYBA0wC_cBU', title: 'Belanova - Tus Ojos'},
  {id: 'XGAxLYFExeY', title: 'Balthazar - Nightclub (Acoustic)'},
  {id: 'IBCRe3c4SSA', title: 'The Tallest Man on Earth - King of Spain'},
  {id: 'Rcgabv2Y8l8', title: 'The Jungle Giants - I Am What You Want Me To Be'},
  {id: 'ultX5ZR-sQE', title: 'San Cisco - Fred Astaire'},
  {id: 'zILmrAJgzSc', title: 'Q Lazzarus - Goodbye Horses'},
  {id: 'ODwZzMLv7zU', title: 'Cabaret Nocturne - Blind Trust'},
  {id: '7OopD1mdbL8', title: 'Yellow Days - A Little While'},
  {id: 'iR5RY7pnMGI', title: 'Wolfmother - Joker And The Thief'},
  {id: '9IZKcb3LndA', title: 'Men I Trust - Tailwhip'},
  {id: 'xI9NfAetZyk', title: 'Junior Senior - Move Your Feet'},
  {id: 'TZj_Ug2o5Cc', title: 'The Highwaymen - Michael, Row The Boat Ashore'},
  {id: 'slKg0G44iNQ', title: 'Kirby Krackle - Going Home'},
  {id: 'E7oMBq1vkCM', title: 'Bobby Roode - Glorious Domination'},
  {id: '5MolbomAK9A', title: 'The Fifth Dimension - Aquarius'},
  {id: '-uv-FhIOPvE', title: 'Haruomi Hosono - Sports Men'},
  {id: 'XfRYgipTTl8', title: 'Findlay - Waste My Time'},
  {id: 'oYKQGTV-rJ4', title: 'Gus Dapperton - My Favorite Fish'},
  {id: 'A_300cnCdYI', title: 'Fitz and the Tantrums - The Walker'},
  {id: '03Mum5dP3SY', title: 'Woodkid - Conquest of Spaces'},
  {id: 'eMhjB2FA61Q', title: 'The Kinks - Picture Book'},
  {id: 'wsi43H9FTtE', title: 'Tiffany - I Think We\'re Alone Now'},
  {id: '5rHRd6Cl-tQ', title: 'They Might Be Giants - Istanbul (Not Constantinople)'},
  {id: 'e3pdHwgV15M', title: 'Paloma Faith - Never Tear Us Apart'},
  {id: 'MaWmV2Y37Ek', title: 'The Yardbirds - Lost Women'},
  {id: 'yczJr9boPTQ', title: 'Nina Simone - Sinnerman'},
  {id: 'FCFirtSvhnk', title: 'Morcheeba - Blood Like Lemonade'},
  {id: 'Q7M9Swpjurc', title: 'Tom Swoon - Shingaling'},
  {id: '-jMj8O0k6xg', title: 'Blue Stahli - Anti You'},
  {id: '4thCOmIMuVM', title: 'Noel Gallagher\'s High Flying Birds - In The Heat Of The Moment'},
  {id: 'G5OV1JPqlNQ', title: 'Big Thief - Mary'},
  {id: 'T3iDFkez5iY', title: 'Fiction Factory - (Feels Like) Heaven'},
  {id: '2dphhF2h7oQ', title: 'The Incredibles - I\'ll Make It Easy'},
  {id: 'jadh_kWstcI', title: 'Don McGinnis - Memory Bound'},
  {id: '67CN8FOCc84', title: 'Toploader - Dancing in the Moonlight'},
  {id: 'X67PTINQi6w', title: 'Gin Wigmore - Kill Of The Night'},
  {id: 'MjrJmjT6lHw', title: 'Three Dog Night - One'},
  {id: 'Bf01riuiJWA', title: 'Radiohead - Exit Music (For a Film)'},
  {id: '9jDpI5-NzXI', title: 'Etta James - Stormy Weather'},
  {id: 'gn3wUB0-T9s', title: 'Karen Dalton - Something on Your Mind'},
  {id: 'pB-5XG-DbAA', title: 'Sam Smith - Stay With Me'},
  {id: '5v1CYI9ufWg', title: 'Damon - They Call Me a Fool'},
  {id: 'xVKGXgHDMvQ', title: 'Hooverphonic - Mad About You'},
  {id: 'atY7ymXAcRQ', title: 'Lesley Gore - Sunshine, Lollipops And Rainbows'},
  {id: '_KPe5L7d13I', title: 'Smith Westerns - All Die Young'},
  {id: 'VdOkQ6THDVw', title: 'Heart - Barracuda'},
  {id: 'Uli02KaYnSo', title: 'Bay City Rollers - Saturday Night'},
  {id: 'ZFCCf9Fz7iQ', title: 'Robbie Williams - Man For All Seasons'},
  {id: 'rPS1bTONSsw', title: 'Molchat Doma - Na Dne'},
  {id: 'uq-gYOrU8bA', title: 'Paul Simon - You Can Call Me Al'},
  {id: 'TKTbbf4z1PQ', title: 'Morning Teleportation - Expanding Anyway'},
  {id: 'aeXt1kI0msA', title: 'Just Nick - I Hate Everything'},
  {id: 'ApXoWvfEYVU', title: 'Post Malone, Swae Lee - Sunflower'},
  {id: 'NolTCxANxA8', title: 'Yellowcard - City of Devils'},
  {id: 'LrjdpNDfZLo', title: 'The Buggles - Video Killed The Radio Star'},
  {id: 'bfwOdpur01M', title: 'Lemaitre ft. Betty Who - Rocket Girl'},
  {id: '52Gg9CqhbP8', title: 'Stuck In the Sound - Let\'s Go'},
  {id: '6Uje4RDymuQ', title: 'Elton John - Rocket Man'},
  {id: 'QChwm0w9nxc', title: 'Tears For Fears - Everybody Wants To Rule The World'},
  {id: 'VbKpd0Ok3SE', title: 'Ninja Sex Party - Danny Don\'t You Know'},
  {id: '8pm_KoguqPM', title: 'Aaron Smith - Dancin (KRONO Remix)'},
  {id: '-zQwY7qT-bQ', title: 'Easy Life - Nightmares'},
  {id: 'AAFt9bMoKhs', title: 'McCafferty - Beachboy'},
  {id: '2ECPxsVv7UQ', title: 'Mother Mother - Oh Ana'},
  {id: '98Xju_5mepA', title: 'The Taxpayers - I Love You Like An Alcoholic'},
  {id: 'u8pVZ5hTGJQ', title: 'Supertramp - Goodbye Stranger'},
  {id: 'vkUeWTBH1Kg', title: 'Ben E. King - Stand by Me'},
  {id: 'evpGu3eO0pY', title: 'VNV Nation - Illusion'},
  {id: 'QXt723fN1ss', title: 'The Coral - Dreaming of You'},
  {id: 'SIhb-kNvL6M', title: 'Tom Petty - American Girl'},
  {id: '1k8craCGpgs', title: 'Journey - Don\'t Stop Believin\''},
  {id: 'M3C5AxR7DWg', title: 'Colin Hay - Overkill (Acoustic)'},
  {id: '9e9NSMY8QiQ', title: 'Tegan and Sara - Closer'},
  {id: '8Gopg80VXwc', title: 'The Crane Wives - Curses'},
  {id: 'xwwY0Qs79ak', title: 'Citizen Cope - Sideways'},
  {id: 'juidLK8Dec4', title: 'OK Go - Here It Goes Again'},
  {id: 'WC5FdFlUcl0', title: 'Audioslave - Be Yourself'},
  {id: 'ufQUxoidxkM', title: 'Boston - More Than a Feeling'},
  {id: '17HzPpyKjfc', title: 'The Coral - Pass It On'},
  {id: 'JmPJ63PUTDY', title: 'Say Anything - Alive With the Glory of Love'},
  {id: 'But-16YFmc4', title: 'Our Lady Peace - Innocent'},
  {id: 'Dy4HA3vUv2c', title: 'Blue Oyster Cult - (Don\'t Fear) The Reaper'},
  {id: '2X_2IdybTV0', title: 'Kansas - Carry On Wayward Son'},
  {id: 'eaOMRFgav30', title: 'Big M - Come On Home'},
  {id: 'SZQIfEN_p2A', title: 'Peter Gabriel - The Book of Love'},
  {id: 'cW0g-73AKkE', title: 'Red Dwarf - Tongue Tied'},
  {id: 'skdE0KAFCEA', title: 'Ramones - Blitzkrieg Bop'},
  {id: '3pzOeqcLltU', title: 'South of France - Comme Ça'},
  {id: 'Yf5yBXFbXK4', title: 'Fialta - High Above Chicago'},
  {id: 'UMAlQkFyV_M', title: 'James Henry Jr. - Take Me Down Easy'},
  {id: 'V2f8V-e-3hE', title: 'Paige & Nikki - Beating Hearts'},
  {id: 'SNa9gcGz4lM', title: 'okaywill - Emotional'},
  {id: 'dmcNbsLCpBQ', title: 'Beach Boys - Wouldn\'t It Be Nice'},
  {id: 'I-v3sVWT8pA', title: 'Crystal Castles - Empathy'},
  {id: '8SJmWSWQgdM', title: 'The Maccabees - Toothpaste Kisses'},
  {id: 'ELjqmFRdIpo', title: 'Thieves Like Us - Shyness'},
  {id: 'zWvHXQqJirY', title: 'Cage the Elephant - Ain\'t No Rest for the Wicked'},
  {id: 'U_K4fF-PMAI', title: 'Alicia Bridges - I Love The Nightlife'},
  {id: '8IuntgwjHmo', title: 'Casiopea - Take Me'},
  {id: '76sNmqMzUuI', title: 'chelmico - Easy Breezy'},
  {id: '-qmqFzR8bR4', title: 'Robbie Robb - In Time'},
  {id: 'd-diB65scQU', title: 'Bobby McFerrin - Don\'t Worry Be Happy'},
  {id: 'KvaxYUfGHnk', title: 'cavetown - Devil Town'},
  {id: '8ZcqaolcjUI', title: 'The Orion Experience - The Cult of Dionysus'},
  {id: 'rbxL5BVEkRs', title: 'Lemon Demon - Touch-Tone Telephone'},
  {id: '6e3qnMmeApE', title: 'Peach Pit - Alrighty Aphrodite'},
  {id: 'TH1IcpDbybQ', title: 'Poppy - Lowlife'},
  {id: 'y_uvv1UKMQ0', title: 'half alive - still feel'},
  {id: 'Q3B17TmEvoY', title: 'Autoheart - Stalker\'s Tango'},
  {id: 'Y4bTKD6flSE', title: 'The Scary Jokes - Catabolic Seed'},
  {id: 'PZqUprA6bKE', title: 'Dan Deacon - When I Was Done Dying'},
  {id: 'rGZVZcMYdmA', title: 'Tennis - Need Your Love'},
  {id: 'J_TL02vGQaM', title: 'Himalayas - Thank God I\'m Not You'},
  {id: 'MMrgCxYsmiw', title: 'Miniature Tigers - Cannibal Queen'},
  {id: 'ZVQDHFgfssM', title: 'Joy Again - Looking Out For You'},
  {id: 'x8t9SRkQYK8', title: 'Sir Chloe - Too Close'},
  {id: 'RaNnztBVD7w', title: 'Current Joys - New Flesh'},
  {id: 'djTc29pC1nQ', title: 'Catherine Feeny - Mr Blue'},
  {id: 'T3gLgZt4DPs', title: 'ssshhhiiittt! - вoceмь'},
  {id: 'HzdD8kbDzZA', title: 'a-ha - Take on Me'},
  {id: 'qVdPh2cBTN0', title: 'flora cash - You\'re Somebody Else'},
  {id: 'tzv1wMeeYoM', title: 'Younger Hunger - FANGS'},
  {id: 'z-V4NNqq5Ak', title: 'Kississippi - Cut Yr Teeth'},
  {id: 'VF3qzEsiXfw', title: 'Irish Stew of Sindidun - I Will Never (Be Your Friend)'},
  {id: 'GoC8OBjs7Iw', title: 'Aviators - Godhunter'},
  {id: 'zH_RlepY3GQ', title: 'Ken Ashcorp - On The Rocks'},
  {id: 'kzeeV_Dl9gw', title: 'Yogscast - MoonQuest'},
  {id: 'Iu-t_v5h5Bw', title: 'Black Pistol Fire - Pick Your Poison'},
  {id: 'bRpN4hjXUuE', title: 'The Blue Stones - Shakin\' Off The Rust'},
  {id: 'xvegS6xDmKE', title: 'Vundabar - Alien Blues'},
  {id: 'A3q0Lhab-sY', title: 'CRX - Give It Up'},
  {id: 'IdzI3tmvrCc', title: 'SHOKK - You Reposted in the Wrong Neighborhood'},
  {id: 'QHgh77iE6qc', title: 'Declan McKenna - Brazil'},
  {id: 'FDX-LLNoZEY', title: 'The Dukes of Stratosphear - Vanishing Girl'},
  {id: '0NlGcFj0NZU', title: 'Negative XP - Scott Pilgrim vs. the World Ruined a Whole Generation of Women'},
  {id: '0hG-2tQtdlE', title: 'Randy Newman - You\'ve Got a Friend in Me'},
  {id: 'E4OzdyxbOuU', title: 'Dolly Parton - 9 to 5'},
  {id: 'lqIbQPrXT64', title: 'Day Wave - PDA'},
  {id: 'c_hBCc9_yhI', title: 'Black Lips - Family Tree'},
  {id: 'T3f8UJlwf2o', title: 'Skinshape - Don\'t Call My Name'},
  {id: 'CL_3mlOPnGI', title: 'Howard Shore - Concerning Hobbits'},
  {id: 's-8lUvdmnlQ', title: 'The Marías - Ruthless'},
  {id: 'IJrKlSkxRHA', title: 'Unknown Mortal Orchestra - Hunnybee'},
  {id: 'hXzPxBhhmY8', title: 'I DONT KNOW HOW BUT THEY FOUND ME - Do It All The Time'},
  {id: 'ABS-mlep5rY', title: 'The Correspondents - Fear & Delight'},
  {id: 'gQWY-JOhF2I', title: 'Steam Powered Giraffe - Automatonic Electronic Harmonics'},
  {id: '62RvnXZgHwQ', title: 'Cosmo Sheldrake - The Moss'},
  {id: 'rrwT3bhRz8M', title: 'The Real Tuesday Weld - Me and Mr Wolf'},
  {id: 'U2WDdccgaDY', title: 'Rainbow Kitten Surprise - It\'s Called: Freefall'},
  {id: '973ibay5504', title: 'Dan Croll - From Nowhere'},
  {id: 'hh1WeQxfCX0', title: 'Dayglow - Can I Call You Tonight?'},
  {id: 'qJhb43oLbDs', title: '100 gecs - hand crushed by a mallet'},
  {id: 'jV4ASCadZ4s', title: 'Kuular - Numb (Thoat singing cover)'},
  {id: 'DjcCQsRCHUs', title: 'Duran Duran - Hungry Like the Wolf'},
  {id: 'RkbL5nxYblc', title: 'Tijuana Panthers - Redheaded Girl'},
  {id: '2r29naqFST4', title: 'Mike Krol - Fifteen Minutes'},
  {id: 'eFTLKWw542g', title: 'Billy Joel - We Didn\'t Start the Fire'},
  {id: 'OFpTa2IfXts', title: 'cavetown - You\'ve Got a Friend In Me'},
  {id: 'TbngYdFIxTc', title: 'Destroy Boys - I Threw Glass at My Friend\'s Eyes and Now I\'m on Probation'},
  {id: 'p6PJmDVqnjg', title: 'Bill Farmer - Nobody Else But You'},
  {id: 'DXAidGQUuns', title: 'The Raconteurs - Steady As She Goes'},
  {id: 'MyYTRhJwEgc', title: 'Lawrence Arabia - Apple Pie Bed'},
  {id: 'ZNjs3nBrB8A', title: 'Bishop Allen - Rain'},
  {id: 'QsWFbMc5t84', title: 'The Moldy Peaches - Anyone Else But You'},
  {id: 'jVPzI-D7p_M', title: 'The Boy Least Likely To - Be Gentle With Me'},
  {id: 'P7myrg90guc', title: 'Oh No Oh My - Walk In The Park'},
  {id: 'G8cRr9tX-Sc', title: 'Ben Folds Five - Do It Anyway'},
  {id: 'j1Aha3JjELY', title: 'Andrew Bird - A Nervous Tic Motion of the Head to the Left'},
  {id: 'FePBV9F9vwI', title: 'Bad Books - Forest Whitaker'},
  {id: 'gpyXaICxTuI', title: 'Bloc Party - This Modern Love'},
  {id: 'NF45jk0_SJc', title: 'Crystal Fighters - At Home'},
  {id: 'NLLvocsmnNU', title: 'The Head and the Heart - Cats and Dogs'},
  {id: 'L4yztAtUtzk', title: 'Hungry Kids Of Hungary - Scattered Diamonds'},
  {id: 'QeKSt5ZTy-A', title: 'Good Old War - Coney Island'},
  {id: 'cORuDz1Hwus', title: 'Cajun Dance Party - Amylase'},
  {id: 'bkIEQgl_V6s', title: 'Passenger - Night Vision Binoculars'},
  {id: 'CifqGQYDPuU', title: 'Faded Paper Figures - North by North'},
  {id: 'S-vyKkOZ_JY', title: 'young scrolls - THE FINE'},
  {id: 'QbR4aNW0nCk', title: 'Gregory Alan Isakov - Dandelion Wine'},
  {id: 'igj2YUOsbk4', title: 'The Sugarplastic - Radio Jejune'},
  {id: 'R67kW6mAZOI', title: 'The Mommyheads - Science and Reason'},
  {id: '2CdkUVoYxIg', title: 'Lazlo Bane - Superman'},
  {id: 'YkLLcIKhJ64', title: 'ABBA - Dancing Queen'},
  {id: 'BKT_y-3NF4k', title: 'Big Little Lions - Happy Home'},
  {id: 'bJ8Sz8CJY5g', title: 'ELO - Mr. Blue Sky'},
  {id: 'ACLkNNBwBAY', title: 'David Bowie - Space Oddity'},
  {id: '8OyBtMPqpNY', title: 'REM - It\'s The End Of The World As We Know It (And I Feel Fine)'},
  {id: 'XN7iEFVLf5c', title: 'The Clash - London Calling'},
  {id: '1FeD16vu_qQ', title: 'Neutral Milk Hotel - In the Aeroplane Over the Sea'},
  {id: '8K0EAc3abq8', title: 'The Blanks - Hey Ya!'},
  {id: 'H6FXWiW4Jhg', title: 'Funeral for a Friend - Into Oblivion'},
  {id: 'PTmYR_bqUVc', title: 'Thank You Scientist - Mr. Invisible'},
  {id: 'OFK4ZSoXpPs', title: 'Turnover - Take My Head'},
  {id: '6TbAn5t5u0k', title: 'The Dear Hunter - Whisper'},
  {id: 'MSEQZ8reJA4', title: 'Porcupine Tree - Anesthetize'},
  {id: '62vYyjnY95k', title: 'Crumb - Ghostride'},
  {id: 'Z47pGUpMy-E', title: 'EDEN - Wake Up'},
  {id: 'BNyYiTdqzAY', title: 'Ne Obliviscaris - And Plague Flowers the Kaleidoscope'},
  {id: 'fNlxKH9Jtmc', title: 'The Civil Wars - Poison & Wine'},
  {id: 'bQJrVkUiaOY', title: 'Beirut - Postcards from Italy'},
  {id: 'OxEQJJSSWNM', title: 'Mt. Joy - Silver Lining'},
  {id: '-w2m-TeLi6I', title: 'Eluveitie - The Call Of The Mountains'},
  {id: 'jRHQPG1xd9o', title: 'Vulfpeck - 1612'},
  {id: 'zkoyRsRJgwc', title: 'Trampled by Turtles - Wait so Long'},
  {id: '5oOk8j0SfoA', title: 'Future Islands - North Star'},
  {id: 'Vm-NW1RwPY8', title: 'The Mountain Goats - No Children'},
  {id: '7qMXBUjm8tM', title: 'fun. - Be Calm'},
  {id: '5yiyNUqxn_Y', title: 'Nothing But Thieves - Sorry'},
  {id: 'cdHdPu4JqSE', title: 'Porter Robinson - Goodbye To A World'},
  {id: '3FX-0Z9pdgw', title: 'Nai Br.XX & Celeina Ann - Kiss Me'},
  {id: 'ZHsu99Wzi4s', title: '??? (Carole & Tuesday) - Galactic Mermaid '},
  {id: 'VT6LFOIofRE', title: 'Tarantula & Kasahara Yuri - Libera Me from Hell'},
  {id: 'p9IyO88o-og', title: 'Rolling Blackouts Coastal Fever - Falling Thunder'},
  {id: 'gqnFa2MWbMw', title: 'Animal Fiction - Hold On'},
  {id: 'm0AscA_ORjU', title: 'Act II - Notes About Freedom'},
  {id: 'HQt6jIKNwgU', title: 'Savage Garden - I Want You'},
  {id: 'qlaRFRA4qFU', title: 'THE DU - CRAZY NOISY BIZARRE TOWN'},
  {id: 'UztXN2rKQNc', title: 'Karen Aoki - Great Days'},
  {id: 'aFPGhSkx7eA', title: 'MOB CHOIR - 99'},
  {id: 'QImBolnTVH8', title: 'JAM Project - THE HERO'},
  {id: '4-43lLKaqBQ', title: 'The Animals - House of the Rising Sun'},
  {id: 'jRFpmA4IIAo', title: 'SALES - Pope Is a Rockstar'},
  {id: '0rn21V7nnSI', title: 'Show Me The Body - Arcanum'},
  {id: 'cy5ExEoVBhQ', title: 'Pangea - River'},
  {id: 'LYlRmiCWhJ0', title: 'together PANGEA - River'},
  {id: '45Ycl2QSFao', title: 'Surf Curse - I\'m Not Making Out With You'},
  {id: 'BQKvtWcojik', title: 'The Orwells - Mallrats (La La La)'},
  {id: 'lP077RitNAc', title: 'Hollywood Undead - Bullet'},
  {id: 'V0lB-kIooOg', title: 'Low Hum - I Don\'t Know Me Like You Do'},
  {id: 'yMcTdi1PJ-4', title: 'Abney Park - I Am Stretched On Your Grave'},
  {id: '6kgZHAptphs', title: 'Arcade Fire - Put Your Money on Me'},
  {id: '4Q4Gy2Z7xZ0', title: 'Amy Winehouse - Back To Black'},
  {id: 'zqw6y61p328', title: 'Cory Wong & Cody Fry - Golden'},
  {id: 'z3c1EN3ZXn4', title: 'Kashiwa Daisuke - My Favorite Things'},
  {id: 'zi1f8O98C2w', title: 'Mindthings - Rebirth'},
  {id: 'SdhAfMor9BM', title: 'Doris Day - Que Sera, Sera'},
  {id: 'xiiq-jZgbQ4', title: 'The Dead South - In Hell I\'ll Be in Good Company'},
  {id: 'gmRy-JW5aps', title: 'The Interrupters - Bad Guy'},
  {id: 'Ggkaj2lRPuM', title: 'Peter Schilling - Major Tom (Coming Home)'},
  {id: 'zRrYN1c9mFg', title: 'Dragonforce - Through The Fire And Flames'},
  {id: '98jbAIJtr3A', title: 'Týr - Take Your Tyrant'},
  {id: 'pcpsrVzpYk0', title: 'Korpiklaani - Spring Dance'},
  {id: '5INnSvBmaBQ', title: 'Baio - Sister of Pearl'},
  {id: 'LMdOhFwuUFc', title: 'Generation X - Dancing with Myself'},
  {id: 'e425i81YVLc', title: 'Gerard Way & Judith Hill - Here Comes The End'},
  {id: 'JMrxwCHp-ug', title: 'Parra for Cuva & Anna Naklab - Wicked Games'},
  {id: 'pK6wz2eDWpI', title: 'Jenny Wilson - Let My Shoes Lead Me Forward'},
  {id: 'DHEOF_rcND8', title: 'Edward Sharpe & The Magnetic Zeros - Home'},
  {id: 'KyYsew_2dRc', title: 'Kate Nash - Merry Happy'},
  {id: '7ijMDQgvW0o', title: 'Tatsuro Yamashita - Sparkle'},
  {id: 'RO1BvdmJYBY', title: 'Hiromi Iwasaki - Street Dancer'},
  {id: 'b1s05pi2yDs', title: 'The Living Tombstone - Love I Need'},
  {id: '8tmzjaN2DWc', title: 'Jonathan Coulton - Re: Your Brains'},
  {id: '2w608EMt9mU', title: 'Metric - Black Sheep'},
  {id: 'jhbwiUsZ8QY', title: 'Lord Huron - Emerald Star'},
  {id: '1cS_i-zDdxg', title: 'Palace - Heaven Up There'},
  {id: '3zx1ZtxUbGE', title: 'Powerwolf - Armata Strigoi'},
  {id: 'VEizKmZlUAw', title: 'Wardruna - Lyfjaberg'},
  {id: 'tOeV-efObZY', title: 'The Killers - Dying Breed'},
  {id: 'U5u9glfqDsc', title: 'Antti Martikainen - Lords of Iron'},
  {id: 'vlB_8TYnt88', title: 'Jónsi - Kolniður'},
  {id: 'GukNjYQZW8s', title: 'Rammstein - Haifisch'},
  {id: 'C9vN6nZawvU', title: 'Ensiferum - Twilight Tavern'},
  {id: 'SEuEha3ulKU', title: 'Timo Räisänen - Fear no Darkness, Promised Child'},
  {id: '7Yiq4ocwQJs', title: 'Church of the Cosmic Skull - Cold Sweat'},
  {id: '8AHCfZTRGiI', title: 'Johnny Cash - Hurt'},
  {id: 'SuRVD1Hl5FY', title: 'Poets of the Fall - Lift'},
  {id: 'QydzTeVCeAA', title: 'The Chalkeaters & Natalia Natchan - Doom Crossing: Eternal Horizons'},
  {id: 'AVBCxnKudhs', title: 'Basil Poledouris - Hymn To Red October'},
  {id: 'bkP02PQkXwc', title: 'The Pogues - Young Ned of the Hill'},
  {id: 'izdc1DUk2_Y', title: 'Kamelot - Where The Wild Roses Grow'},
  {id: 'LfxK9dJzLLU', title: 'Gershon Kingsley - Popcorn'},
  {id: 'VnULE-d14TA', title: 'Scatman John - Scatman'},
  {id: 'LirCuUvdjoI', title: 'The Nightmare Before Christmas - This is Halloween'},
  {id: 'cBubWrVg9bk', title: 'Bobby Pickettt - Monster Mash'},
  {id: '-1dSY6ZuXEY', title: '?? - Spooky Scary Skeletons'},
  {id: '5Yz2t1QeIHQ', title: 'Chelou - Out Of Sight'},
  {id: '1OijD72t4XY', title: 'The Big Moon - Your Light'},
  {id: 'JhC8Ptp191E', title: 'The Murlocs - Rolling On'},
  {id: 'ADj2jDqT4uY', title: 'King Gizzard & The Lizard Wizard - Honey'},
  {id: 'FbFoX8SvaKI', title: 'Skating Polly - Camelot'},
  {id: 'RUCerUZuu6Y', title: 'The Regrettes - Hey Now'},
  {id: 'W2-ymATxJi8', title: 'Los Bitchos - The Link Is About To Die'},
  {id: 'EQdAohoxxms', title: 'Pancake Mountain - Dirty Dog (feat. Kelli Mayo & Scott Stuckey)'},
  {id: '8XBXvVC6sh4', title: 'Warpaint - Disco//very'},
  {id: 'gZDK-ND-nZA', title: 'Trapdoor Social - Sunshine'},
  {id: 'uLyYQFsiPa8', title: 'Blonde Tongues - Hey Good Lookin\''},
  {id: 'WCSuv56YwQQ', title: 'No Vacation - Yam Yam'},
  {id: 'ECgFc52FouU', title: 'boy pablo - hey girl'},
  {id: 'YXwYJyrKK5A', title: 'Two Door Cinema Club - What You Know'},
  {id: '-kbtWBWCJaI', title: 'Snail Mail - Heat Wave'},
  {id: 'zoae8_0HG1Y', title: 'MyKey - Was It Something I Said'},
  {id: '8WyGaus8ax0', title: 'Twin Cabins - Swing Lynn'},
  {id: 'OzOdVZEU0ic', title: 'potsu - Reaching For a Star'},
  {id: 'q6MHYzqGbrg', title: 'Forrest. - Never Had'},
  {id: 'LHsVtH0CS7I', title: 'Vansire - Metamodernity'},
  {id: 'GZvqfvLyX9Q', title: 'Fake Laugh - Watching'},
  {id: 'sniVezVELSM', title: 'Coyote Theory - This Side of Paradise'},
  {id: 'h2SZyditwBY', title: 'Mega Shinnosuke - Cutie Girl'},
  {id: 'DsHuqWhcjEs', title: 'Mild High Club - Homage'},
  {id: 'qyBFNoqMqRs', title: 'No Buses - Number Four or Five'},
  {id: 'NM-VWHP-cWk', title: 'Vacations - Young'},
  {id: 'S1KNYqEpI2w', title: 'Bedroom - In My Head'},
  {id: '0rXdQRiN4-4', title: 'Last Dinosaurs - Sense'},
  {id: 'XIki4MvjAbU', title: 'The Turtles - Happy Together'},
  {id: 'jnFNdDKkWcI', title: 'Billy Paul - Your Song'},
  {id: 'bflBjZqsLT0', title: 'Richard Cheese - People Equal Shit'},
  {id: 'Nioflv9Xn5I', title: 'Globus - Take me Away'},
  {id: 'wyMwEYxwx-0', title: 'LÖV - Strangers or Lovers'},
  {id: 'NuEghDO_j0o', title: 'Michael Kiwanuka - Cold Little Heart'},
  {id: 'sVAb2kbx1gI', title: 'wilco - How to Fight Loneliness'},
  {id: 'eU4NgvQJV7w', title: 'JJ - Let Go'},
  {id: 'GVpNkadPsho', title: 'Freedom Call - Sail Away'},
  {id: 'racmy7Y9P4M', title: 'Bring Me The Horizon - Parasite Eve'},
  {id: 'TTz4xNd-WQ0', title: 'Anna Leone - If You Only'},
  {id: 'bIrPCtChtgs', title: 'Tommy Nilsson - Where Did She Go'},
  {id: '222mASo-wio', title: 'Elin Ruth Sigvardsson - If I'},
  {id: '6au8u8-ZJhc', title: 'Dogs Die in Hot Cars - Celebrity Sanctum'},
  {id: 'dQC1aEylH08', title: 'The Strike - Nothing New'},
  {id: 'KhgeSNRLaoE', title: 'Beast in Black - Die by the Blade'},
  {id: 'MbrhAmKylBI', title: 'Bahamas - Don\'t You Want Me'},
  {id: '0uzh7NqdTWs', title: 'Futurecop! - 1988 Girls'},
  {id: 'tY_VAniQfLI', title: 'Jerry Williams - Did I Tell You'},
  {id: 'EN0_OhC2Nag', title: 'Dodgy - Good Enough'},
  {id: 'YNNRyktMf4A', title: 'The Midnight - Vampires'},
  {id: 'FjCUw4Vtfm4', title: 'Timecop1983 - Cruise'},
  {id: '1UyPrfpVzh8', title: 'Lifelike - So Electric'},
  {id: 'C9W9d29qQqM', title: 'Kalax - Dream'},
  {id: 'kSsOUY_cnZc', title: 'House of Heroes - If'},
  {id: 'qIghfvrXt6Q', title: 'Sub Focus - Don\'t You Feel It'},
  {id: 'WTNN-Ec6hAE', title: 'Gary Moore - Wild Frontier'},
  {id: 'kjt7AdLYT2w', title: 'XTC - Senses Working Overtime'},
  {id: 'SuqMJZfwxo4', title: 'Night Runner - Invaders'},
  {id: '63pRs3FikOE', title: 'Magic Sword - Lady of Light'},
  {id: 'nBfcuerhYog', title: 'Dolly Style - Cherry Gum (Nightcore)'},
  {id: '17nXsv7o64k', title: 'Louis Armstrong - When the Saints Go Marching In'},
  {id: 'hUKe6gihtx0', title: 'Alex G - Sarah'},
  {id: 'QWu-f7HFFJE', title: 'The Band - The Weight'},
  {id: '7Zb35-ZRMUE', title: 'Aliotta Haynes Jeremiah - Lake Shore Drive'},
  {id: 'TKvzHBdcAdM', title: 'Alex Turner - Stuck on the puzzle'},
  {id: 'sxLSAGAFPLI', title: 'Annapantsu - Fine & Dandy'},
  {id: 'P_wMWX0HbAQ', title: 'Bslick - I Can\'t Say Why'},
  {id: 'UNVFEt5vkWc', title: 'The Longest Johns - Wellerman'},
  {id: 'WVkD4lgXTEU', title: 'The Longest Johns - Bones in the Ocean'},
  {id: 'TVY8LoM47xI', title: 'Stan Rogers - Northwest Passage'},
  {id: 'VEH-TccaffY', title: 'Celtic Connection - The Last Shanty'},
  {id: '5LYdkDh2QQI', title: 'Blackbird Raum - Valkyrie Horsewhip Reel'},
  {id: '3Z3oCJfnHO8', title: 'The Real McKenzies - Barrett\'s Privateers'},
  {id: '3-FqDoK9aQk', title: 'Jerry Bryant and Starboard Mess - Spanish Ladies'},
  {id: 'RwtHJW9EO04', title: 'Sons of Maxwell - Those Were The Days'},
  {id: 'gAtMan8mNzM', title: 'The Dreadnoughts - Eliza Lee'},
  {id: 'vsTzy_MWLB4', title: 'ALI - Wild Side'},
  {id: 'zrdezG6c6HM', title: 'Sol Seppy - Enter One'},
  {id: 'h-v_APbgFM0', title: 'Swingfly, Teddybears - Hey Boy'},
  {id: 'tOcYdHwc1Zo', title: 'Avenue Q - If You Were Gay'},
  {id: 'KZWsB9_-Izg', title: 'Caroline Konstnar - The Worlds Dumbest Puppet Show'},
  {id: 'PIVeo2ViPXs', title: 'machinegum - Knots'},
  {id: 'eGZ2Y46uWQg', title: 'Rey Pila - Casting a Shadow'},
  {id: 'JV95aX5kCfo', title: 'The Virgins - Travel Express (From Me)'},
  {id: 'vFTdTf1rM8s', title: 'Shout Out Louds - The Comeback'},
  {id: 'kLp_Hh6DKWc', title: 'Edvard Grieg - In the Hall of the Mountain King'},
  {id: '74bllwl2kL4', title: 'Chopin - Op.28 No 15 Raindrop (by Pollini)'},
  {id: 'F-Vp98VxX1U', title: 'Buxtehude - BuxWV 155 - Toccata in D Minor'},
  {id: 'JkP7slIc9aM', title: 'Vivaldi - Winter, 1st Movement'},
  {id: 'rvfTaxEAQPc', title: 'Tchaikovsky - The Nutcracker Op. 71 Act 2 No. 14 - Pas De Deux'},
  {id: 'Hcon59QUQKo', title: 'Wilhelm Stenhammar - Symphony No.1'},
  {id: '-1eZnwQRmlM', title: 'Couperin - Benedictus Chromhorne en Taille'},
  {id: 'MQ_LX7Y4jMM', title: 'Gustav Holst - The Planets Op.32 No 4 - Jupiter, The Bringer Of Jollity'},
  {id: 'J-sWkmBoU3Q', title: 'Erik Satie - Trois Gymnopédies: Première Gymnopédie'},
  {id: 'gelwwYuYGn0', title: 'Grover Washington Jr. - Just the Two of Us'},
  {id: 'fqq7D3FimJ8', title: 'limbo - airplane mode'},
  {id: '7nK67ydPrB0', title: 'Planet X - Alien Hip Hop'},
  {id: '1kPGPSiNmys', title: 'Will Wood - Dr. Sunshine Is Dead'},
  {id: 'e2qG5uwDCW4', title: 'Jack Stauber - Buttercup'},
  {id: 'dc2dd-fhPTY', title: 'Wintergatan - Sommarfågel'},
  {id: 'Y-h98hFYusc', title: 'Hot Hot Heat - Goodnight'},
  {id: 'gi4W3PBRk90', title: 'Mio Honda & Crush 40 (Ft. Gun) - Step! x I Am... All Of Me (Mashup)'},
  {id: 'G9MiWEWBR2U', title: 'Nano - Inside My Core'},
  {id: 'dbGTtvQBYhY', title: 'Selamo, Moon - Sexy Smile'},
  {id: 'o11DxwXj2FU', title: 'Big Wild - Venice Venture'},
  {id: 'WBkLFDezvk0', title: 'Balmorhea - Baleen Morning'},
  {id: 'jvipPYFebWc', title: 'Roundtable Rival - Lindsey Stirling'},
  {id: 'DwVEjb2LSWE', title: 'Loving Caliber, Jonathan Kanat - What If I Said I Am Sorry'},
  {id: 'r0kvTBbBbbY', title: 'Monty Python - Look On The Bright Side Of Life (All Things Dull And Ugly)'},
  {id: 'iMznpUsdH54', title: 'Skáld - Seven Nation Army'},
  {id: '49zga3j91i8', title: 'Fools Garden - Lemon Tree'},
  {id: 'c-I9ujIySkc', title: 'Particle House - Sometimes Hearts Collide (feat. Christine Smit)'},
  {id: '2aXzOfGQdMQ', title: 'LunchMoney Lewis - Bills'},
  {id: 'otvVdzNjEvg', title: 'Astrid S - Leave It Beautiful'},
  {id: '5QGdHkV3vB8', title: 'Leroy - Gonna Get Together'},
  {id: '2-NJMRHY0Kc', title: 'Weezer - All My Favorite Songs'},
  {id: 'GkgvkKgZI5s', title: 'Jellyfish - New Mistake'},
  {id: 'EgSXjAIkO-g', title: 'Plastic Bertrand - Ça Plane Pour Moi'},
  {id: 'ILAzIY89pug', title: 'Metrik - Fatso (VIP)'},
  {id: 'XqspbP-3at4', title: 'Cossbysweater - Everything\'s Coming Up Milhouse'},
  {id: 'mCYwONZYiUc', title: 'Sigala, Ella Eyre, Meghan Trainor - Just Got Paid (feat. French Montana)'},
  {id: 'pqLqag3WI5o', title: 'Ofenbach & Quarterhead - Head Shoulders Knees & Toes (feat. Norma Jean Martine)'},
  {id: 'DwPWGUhEtP0', title: 'Yes - Roundabout'},
  {id: 'fzamt-yKb4A', title: 'SOAK - Knock Me Off My Feet'},
  {id: 'Ryi1L1huEeY', title: 'LPX - Might Not Make It Home'},
  {id: 'vCudXuFCqRU', title: 'Rayana Jay - Do Betta'},
  {id: '6u0DGIh3wLA', title: 'BIRDY + RHODES - Let It All Go'},
  {id: '_zYvmCqlCAk', title: 'Battle Tapes - Alive'},
  {id: 'iNl4iAX7aBo', title: 'LG Team Genius - My Type'},
  {id: 'PPSMTrOw100', title: 'K.Flay - I Like Myself'},
  {id: 'bL-hRknymbI', title: 'The Hives - Hate To Say I Told You So'},
  {id: 'PPDqlkiB3aE', title: 'Lance & Linton - Sunshine'},
  {id: 'dy90tA3TT1c', title: 'YOASOBI - Monster'},
  {id: '6CHs4x2uqcQ', title: 'Kanye West - Good Morning'},
  {id: 'Azsk21MpbUk', title: 'Anders Enger Jensen - MCA DiscoVision'},
  {id: 'UXiwRmlCZ7E', title: 'Engelwood - Crystal Dolphin'},
  {id: '-7XnDlYY9qw', title: 'Outkast - Hey Ya!'},
  {id: '9Gj47G2e1Jc', title: 'Mariya Takeuchi - Plastic Love'},
  {id: 'CLINCFmaGtc', title: 'Toshiki Kadomatsu - Love Junky'},
  {id: 'UR--Emdc79I', title: 'Anri - Bring Me To The Dancenaigh/Gone With The Sadness'},
  {id: 'yEIdVYRCJbc', title: 'Hiromi Iwasaki - Sentimental'},
  {id: '8qQFtgdJi4w', title: 'Sakiko Ito - 木枯らしの二人'},
  {id: 'pAGpz0EuMOU', title: 'Amaranthe - On The Rocks'},
  {id: '-38yJGUvBD8', title: 'Jamiroquai - Canned Heat'},
  {id: '6GCNUeTFSbA', title: 'Michael Sembello - Maniac'},
  {id: 'mMHbMMqWiVw', title: 'Flipper\'s Guitar - Camera! Camera! Camera!'},
  {id: 'TfZnig_FHME', title: 'Yellow Magic Orchestra - Tong Poo'},
  {id: 'V-976KwsQYQ', title: 'Shkoon - Napauken (Jpattersson Remix)'},
  {id: '_iORvy9A4hY', title: 'Julita - 24/7'},
  {id: '1-W6whvn8Bs', title: 'The Strokes - Selfless'},
  {id: 'X-tfYbRK2OA', title: 'Yellowman - Zungguzungguguzungguzeng'},
  {id: 'cEsSO4smnr0', title: 'Nightwish - The Phantom of The Opera'},
  {id: '-N4jf6rtyuw', title: 'Gnarls Barkley - Crazy'},
  {id: 'zpUr_QeyCLA', title: 'Terrordactyls - Fall'},
  {id: 'ZbZSe6N_BXs', title: 'Pharrell Williams - Happy'},
  {id: 'T302BhpyVNQ', title: 'Upstate - Weekend'},
  {id: 'voQgpmUUT8U', title: 'Surkin - Next of Kin'},
  {id: 'Ylu0ybj7DIg', title: 'Simian Mobile Disco - Audacity of Huge'},
  {id: '7xzU9Qqdqww', title: 'Kid Cudi - Pursuit of Happiness (feat. MGMT)'},
  {id: 'I86LB79qorM', title: 'The Tough Alliance - Koka-Kola Veins'},
  {id: 'aKM8txMizdI', title: 'Yelle - A Cause Des Garçons'},
  {id: 'QHRuTYtSbJQ', title: 'Mick Gordon - BFG Division'},
  {id: 'i1BDGqIfm8U', title: 'Feed Me - One Click Headshot'},
  {id: 't-Dx-xFbGWg', title: 'Kenji Kawai - Utai IV: Reawakening (Steve Aoki Remix)'},
  {id: '57F88zhofsY', title: 'The Simpsons - Baby on Board'},
  {id: 'LB4GTkDBvI0', title: 'Krister and Dalbani - Heartache Tonight'},
  {id: 'dcVs2c4RWfA', title: 'Eternal Trip - The Joker'},
  {id: 'Qo_N9_ZFBhs', title: 'Ringmasters - Notre Dame Medley'},
  {id: 'iWaq1ZvhH0M', title: 'The Newfangled Four - All Star'},
  {id: 'BQ3VtEDdM5k', title: 'The Buzztones - Stand By Me'},
  {id: 'l0ZUbtjorSY', title: 'Chris Bandy, etc - The Longest Time'},
  {id: 'N5_X-95YaWU', title: 'Proper Sound - Mr Sandman'},
  {id: 'BEJBKoSoot8', title: 'Masterpiece - Tennessee Waltz'},
  {id: 'iPEY2SE1vXk', title: 'Main Street - Smile'},
  {id: 'uxlNi1jM-1A', title: 'Acoustix - It\'s a Grand Night for Singing'},
  {id: 'KAdoXZkxGHM', title: 'GQ - Samson'},
  {id: '4dp75ZF0854', title: 'Crossroads - That Lucky Old Sun (Just Rolls Around Heaven All Day)'},
  {id: 'LKMw0hBDBUw', title: 'Skirt - ODDTAXI (feat. PUNPEE)'},
  {id: 'xJ5XK4k5vtA', title: 'Matt Bomer - People Like Us (feat. Alan Mingo Jr.)'},
  {id: 'SJLwXbsXWjM', title: 'Tribe Friday - forward is the way out'},
  {id: '3MXovHX3YNg', title: 'Geoff Castelluci - Sixteen Tons'},
  {id: 'bs4ZJpWJh_Q', title: 'VoicePlay - My Mother Told Me (feat. Jose Rosario Jr)'},
  {id: '-5QACZjFDWs', title: 'Acquire A Cappella - Turret Opera'},
  {id: 'PLOwPxkZ6Pc', title: 'Cory Wong - Hästråtta'},
  {id: '8x-_xHDsRuE', title: 'Field Medic - talkin johnny & june (your arms around me)'},
  {id: 'oXrfNDK9pK8', title: 'Annika Norlin - Hydra'},
  {id: 'F5EUPV8MhoE', title: 'anton. - cortado, Pt. 2anton.'},
  {id: 'WA0t6ErCtus', title: 'Wildstylez - Year of Summer (feat. Niels Geusebroek)'},
  {id: 'Y6nBB_fxZZw', title: 'Gladenfold - Starborn'},
  {id: 'iUCbQ1rKOUg', title: 'Lord of the Lost - The Gospel of Judas'},
  {id: 'bnQBqinwlwQ', title: 'Dagny - Love You Like That'},
  {id: 'te4L-fpqdBs', title: 'LOVA - You Me and The Silence'},
  {id: '4ieLyjuoGck', title: 'TORN - Groove'},
  {id: 'rj8MGKshSuQ', title: 'Unlike Pluto - Sweet (feat. Mister Blonde)'},
  {id: 'i6nJJ2z1Jdw', title: 'mtbrd - Damn Fine Coffee'},
  {id: 'rJjQl_IpT6Q', title: 'Sweep Beats - don\'t let it stress'},
  {id: 'qDAoJIJ2ljU', title: 'Stan Bush - The Touch'},
  {id: 'vGFAjwtjlPc', title: 'John Farnham - Thunder in Your Heart'},
  {id: '64PQZwjrF2E', title: 'Blind Guardian - Battlefield'},
  {id: 'OoHGZFyMCHU', title: 'Shinedown - Enemies'},
  {id: 'R5q2oPUweF0', title: 'Disturbed - Never Again'},
  {id: 'Jad1-vxh1vQ', title: 'Alexi Murdoch - Breathe'},
  {id: 'f-Msede1guE', title: 'Deb Talan - Comfort'},
  {id: 'XluslIGClRA', title: 'Flogging Molly - The Worst Day Since Yesterday'},
  {id: '_CYrdu6hiRo', title: 'BABYBEARD - 「ニッポンからコンニチハ」'},
  {id: 'jdYJf_ybyVo', title: 'John Butler - OCEAN'},
  {id: '0iz3YD8FN6w', title: 'Jeff Danna - The Blood Of Cu Chulainn'},
  {id: 'x-64CaD8GXw', title: 'Dropkick Murphys - I\'m Shipping Up To Boston'},
  {id: 'sxm2aMq-3Zk', title: 'Timothy Fleet, Wayne Murray - SoS'},
  {id: '0BlZVFqUoJ4', title: 'Born Ruffians - Needle'},
  {id: 'KSlA7x98Yfw', title: 'Maps and Atlases - Solid Ground'},
  {id: 'NVjSycDJatc', title: 'Cardiacs - Tarred And Feathered'},
  {id: 'jICYWL0ZApU', title: 'Someone Still Loves You Boris Yeltsin - Young Presidents'},
  {id: 'emjOUMLgKgs', title: 'Samira Manners - I Want to Be Loved'},
  {id: 'zakpDTDELRc', title: 'heiakim - Hotto Dogu'},
  {id: 'sY9Cr0a5dCs', title: 'Maxium The Hormone - Chu Chu Lovely Muni Muni Mura Mura Purin Purin Boron Nururu Rero Rero'},
  {id: 'BciS5krYL80', title: 'Eagles - Hotel California'},
  {id: '-aKJE1lanQk', title: 'Backstreet Boys - I Want It That Way'},
  {id: 'aJ9usrpAPao', title: 'The Proclaimers - I\'m Gonna Be (500 Miles)'},
  {id: '7q0UTFq-o-o', title: 'Björn Skifs - Hooked On A Feeling'},
  {id: 'UiznIkHQ9sQ', title: 'Carl Douglas - Kung Fu Fighting'},
  {id: 'DP5qPb_zDUc', title: 'Village People - YMCA'},
  {id: 'NNiTxUEnmKI', title: 'Europe - The Final Countdown'},
  {id: 'NtM3jjLP7AE', title: 'Starship - We Built This City'},
  {id: 'c5DGcQoBC9k', title: 'Wham! - Wake Me Up Before You Go-Go'},
  {id: '3KFvoDDs0XM', title: 'Roy Orbison - Oh, Pretty Woman'},
  {id: 'l0q7MLPo-u8', title: 'Simon and Garfunkel - The Sounds of Silence'},
  {id: '2dzf4T3RbEc', title: 'Whitney Houston - I Wanna Dance with Somebody'},
  {id: 'bjQ9vTsMQ4I', title: 'Kenny Loggins - Footloose'},
  {id: '3KdBCFclSC0', title: 'Cyndi Lauper - Time After Time'},
  {id: 'VU32_LtpDdU', title: 'Meat Loaf - I\'d Do Anything For Love (But I Won\'t Do That)'},
  {id: '9SKFwtgUJHs', title: 'Bon Jovi - It\'s My Life'},
  {id: '5NV6Rdv1a3I', title: 'Daft Punk - Get Lucky'},
  {id: 'iX_TFkut1PM', title: 'Don McLean - American Pie'},
  {id: '4B6E0mijV5A', title: 'Wax Fang - Majestic'},
  {id: '2SUwOgmvzK4', title: 'Tame Impala - The Less I Know the Better'},
  {id: 'qpHvj5pvvhg', title: 'SiM - The Rumbling'},
  {id: '6a6dctE-ZLU', title: 'Delta Spirit - California'},
  {id: 'kGn13Apz8Tg', title: 'Royal & the Serpent - Overwhelmed'},
  {id: 'I2rV8oKWSdM', title: 'Penpals - Tell Me Why'},
  {id: 'eJgr39GhLLw', title: 'The Pillows - Little Busters'},
  {id: 'INugjPMaOWs', title: 'The Lion King - I Just Can\'t Wait to Be King'},
  {id: 'TVcLIfSC4OE', title: 'Mulan - I\'ll Make a Man Out of You'},
  {id: 'wYleCKxV_WA', title: 'The Hunchback of Notre Dame - Heaven\'s Light/Hellfire'},
  {id: 'QRqGryij6tE', title: 'Encanto - Surface Pressure'},
  {id: 'ulsLI029rH0', title: 'Hamilton - Wait for It'},
  {id: 'Jtvc8DXNO4Q', title: 'Aladdin - One Jump Ahead'},
  {id: 'woO9FidFa6o', title: 'Hercules - Zero to Hero'},
  {id: 'mlGZX0PDdFU', title: 'Galavant - Will My Day Ever Come'},
  {id: 'iW2FUY3N-n0', title: 'The Greatest Showman - From Now On'},
  {id: 'VENistGBPsg', title: 'Les Misérables - Do You Hear The People Sing?'},
  {id: 'vXzdukak6MA', title: 'Oliver & Company - Why Should I Worry?'},
  {id: 'rkLiImA3KlU', title: 'Winnie the Pooh - Wherever You Are'},
  {id: 'nDJockBnjYs', title: 'The Aristocats - Ev\'rybody Wants to Be a Cat'},
  {id: '41ill-Bq5UI', title: 'Monsters, Inc. - If I Didn\'t Have You'},
  {id: '2sBtUBR-cYA', title: 'Tarzan - Son of Man'},
  {id: 'MUZwblurraA', title: 'Treasure Planet - I\'m Still Here'},
  {id: 'npJa14mxCVY', title: 'Beauty and the Beast - Be Our Guest'},
  {id: 'kVFHKUMHJ3Y', title: 'The Road to El Dorado - The Trail We Blaze'},
  {id: '26u-vhBo6hY', title: 'The Fox & The Hound - Best of Friends'},
  {id: 'ubZrAmRxy_M', title: 'Moana - We Know The Way'},
  {id: 'uX2mopyE5Z0', title: 'The Jungle Book - I Wanna Be Like You'},
  {id: 'lw-hIRubQ0w', title: 'Pocahontas - Savages'},
  {id: 's5kKqgw5CtU', title: 'The Princess and the Frog - Dig a Little Deeper'},
  {id: 'RuHa14HByd0', title: 'Coco - Proud Corazón'},
  {id: 'ChNJ_FMtSnk', title: 'The Little Mermaid - Under the Sea'}, // Unda da Sea
  {id: 'AapdN2UFEbU', title: 'The Sound of Music - My Favorite Things'},
  {id: 'LH6MstVxehQ', title: 'Annie (1982) - It\'s The Hard Knock Life'},
  {id: 'dlONS745QPo', title: 'Dr. Horrible\'s Song-Along Blog - My Freeze Ray'},
  {id: 'j5fCqKbSC7M', title: 'Fiddler on the Roof - If I Were a Rich Man'},
  {id: 'e__Pp4FxsjU', title: 'Grease - You\'re The One That I Want'},
  {id: 'mAVdcPBj16Q', title: 'In the Heights - Benny\'s Dispatch'},
  {id: 'nSyv1IVBmFM', title: 'Little Shop of Horrors - Mean Green Mother From Outerspace'},
  {id: 'xKvdlSLbrCo', title: 'South Park: Bigger, Longer & Uncut - La Resistance'},
  {id: 'S91wQbYYX3Q', title: 'The Rocky Horror Picture Show - The Time Warp'},
  {id: '_Tihl3pzWRc', title: 'West Side Story - America'},
]);