// TODO: Merge this into music at some point
Playlist.addPredesignedPlaylist('bideobames', [
  {source: 'youtube', src: 'cCYZQZ2OQqo', title: 'A Shell in the Pit, Wandersong - The Bard'},
  {source: 'youtube', src: 'djAvxUw3dTM', title: 'Piotr Musial, Funky Smugglers - First Class Lounging'},
  {source: 'youtube', src: 'iYANYGCgRz4', title: 'Souleye, VVVVVV - Pushing Onwards'},
  {source: 'youtube', src: 'gtJyq0STBu0', title: 'Alexander Brandon, Jazz Jackrabbit 2 - Medieval Jam'},
  {source: 'youtube', src: '_ZduC-OCXB8', title: 'Darren Korb, Bastion - Build That Wall | Mother, I\'m Here | Setting Sail, Coming Home'},
  {source: 'youtube', src: 'uXDGT1JixPk', title: 'Takeharu Ishimoto, TWEWY - Twister'},
  {source: 'youtube', src: 'wlF0-Qs2xkI', title: 'Koji Kondo, TLoZ:WW - Molgera Battle Theme'},
  {source: 'youtube', src: 'nxP9GsDxaAA', title: 'Danny Baranowsky, Crypt of the NecroDancer - March of the Profane (3-2 Hot)'},
  {source: 'youtube', src: 'nBPK_oXeJgA', title: 'Alexander Brandon, Deus Ex - UNATCO'},
  {source: 'youtube', src: 'BSsfjHCFosw', title: 'Bobby Prince, Doom - E1M1 - At Doom\'s Gate'},
  {source: 'youtube', src: 'EwbMkIROOGU', title: 'Plasma3Music, DuckTales Remastered - Moon Theme Orchestra Remix'},
  {source: 'youtube', src: '4WgDqGrcblA', title: 'Plasma3Music, EarthBound - Eight Melodies (Orchestra Remix)'},
  {source: 'youtube', src: 'Q_53DhqXCks', title: 'Frederic Resurrection of Music - Time For Africa'},
  {source: 'youtube', src: '84q83skr_tk', title: 'Hotline Miami - Hydrogen'},
  {source: 'youtube', src: 'Y6ljFaKRTrI', title: 'Portal - Still Alive'},
  {source: 'youtube', src: 'dVVZaZ8yO6o', title: 'Portal 2 - Want You Gone'},
  {source: 'youtube', src: 'pDGaqUskBRM', title: 'Shovel Knight - La Danse Macabre (Lich Yard)'},
  {source: 'youtube', src: 'bHTsU3iqNQ0', title: 'Before The Echo - Derty'},
  {source: 'youtube', src: 'IJiHDmyhE1A', title: 'Christopher Tin - Baba Yetu'},
  {source: 'youtube', src: 'aBkTkxKDduc', title: 'C418, Minecraft - Sweden'},
  {source: 'youtube', src: 'nJD-Ufi1jGk', title: 'Jeremy Soule, TES3:Morrowind - Theme Song'},
  {source: 'youtube', src: 'DvNSbKmUZZw', title: 'West of Loathing - Main Theme'},
  {source: 'youtube', src: 'im6tbN9SZXs', title: 'Pokémon Ruby, Sapphire, Emerald - Littleroot Town'},
  {source: 'youtube', src: 'vvDGFREXTPE', title: 'Super Smash Bros. Brawl - Gourmet Race'},
  {source: 'youtube', src: '5OUP_Z3iZPs', title: 'Deadly Premonition - Whistle Theme'},
  {source: 'youtube', src: 'XhG6Qaij7VE', title: 'Endless Legend - Auriga\'s Song'},
  {source: 'youtube', src: 't6vWDz5NzOY', title: 'Ori and the Blind Forest - Light of Nibel'},
  {source: 'youtube', src: 'MJDn70jh1V0', title: 'Hollow Knight - City of Tears'},
  {source: 'youtube', src: 'AB6sOhQan9Y', title: 'Dark Souls - Gwyn, Lord of Cinder'},
  {source: 'youtube', src: '0jXTBAGv9ZQ', title: 'Halo - Theme Song'},
  {source: 'youtube', src: 'Jw6KRkx0vNg', title: 'Sonic Heroes - Theme Song'},
  {source: 'youtube', src: '2unSXEPyYKQ', title: 'Play! A Video Game Symphony, TES4:Oblivion - Oblivion Medley'},
  {source: 'youtube', src: 'iabhM-i43XI', title: 'Pokémon X, Y - Snowbelle City'},
  {source: 'youtube', src: '_jFzDqmt5YY', title: 'Pokémon Trading Card Game - Club Master Duel'},
  {source: 'youtube', src: 'NjjYdIm7Fp8', title: 'The 8-Bit Big Band, Earthbound - Fourside'},
  {source: 'youtube', src: 'MTxMh6qu6Mw', title: 'Qumu, Super Mario Odyssey - Jump Up, Super Star! (Remix)'},
  {source: 'youtube', src: 'xIIYt5lcq3A', title: 'Devil May Cry 4 - Shall Never Surrender'},
  {source: 'youtube', src: '22vbhTi1ieI', title: 'The 8-Bit Big Band, Portal - Still Alive'},
  {source: 'youtube', src: 'UpUq3zi9-sw', title: 'EnrightBeats, The Greater Good - The Grand Adventure'},
  {source: 'youtube', src: 'Ec4YbVP9R-A', title: 'Persona 5 - Last Surprise'},
  {source: 'youtube', src: 'j5NwJpo9Gng', title: 'Art Sqool - Art Sqool'},
  {source: 'youtube', src: 'z3ZiVn5L9vM', title: 'Tetris - Music A'},
  {source: 'youtube', src: 'DTpksvCC-hg', title: 'Yoshi\'s Island - Flower Garden'},
  {source: 'youtube', src: 'l6TPyffyceY', title: 'David Ari Leon, Contre Jour - Les Monstres'},
  {source: 'youtube', src: 'EVKFrMvDWww', title: 'Krater - Tutorial'},
  {source: 'youtube', src: 'HL8oQw0nm0M', title: 'RuneScape - Scape Main'},
  {source: 'youtube', src: 'QWhhMxrX-Us', title: 'Super Mario Galaxy - Gusty Garden Galaxy'},
  {source: 'youtube', src: 'iMH49ieL4es', title: 'Katamari Damacy - Katamari on the Rocks'},
  {source: 'youtube', src: 'ZT9DST_M_g8', title: 'Mega Man 2 - Theme'},
  {source: 'youtube', src: '0hEYvdMoF2g', title: 'TLoZ:OoT - Gerudo Valley'},
  {source: 'youtube', src: '2WEevxtnj-A', title: 'Robin Blend, DOOM, Undertale - E1M1/MEGALOVANIA'},
  {source: 'youtube', src: 'o6tKCjFYXDM', title: 'Mario Kart 8 - Hyrule Circuit'},
  {source: 'youtube', src: 'M6PGZhKxWes', title: 'The Noble Demon, Castlevania - Vampire Killer Arrangement'},
  {source: 'youtube', src: 'DSFJP2lwCW8', title: 'NieR:Automata - Pascal'},
  {source: 'youtube', src: 'byxTuIO6XT0', title: 'Divinity: Original Sin II - Rivellon'},
  {source: 'youtube', src: 'G_Yrgk-cjQo', title: 'Phoenix Wright: Trials and Tribulations - Cornered'},
  {source: 'youtube', src: 'X9geXVAOFDg', title: 'Jesper Kyd, Assassin\'s Creed 2 - Venice Rooftops'},
  {source: 'youtube', src: 'ciEHtGpSviE', title: 'Pokémon XD - Miror B Battle'},
  {source: 'youtube', src: 'EiPKkDjDRk8', title: 'Crab Champions - Intro'},
  {source: 'youtube', src: '38udbIqG0LQ', title: 'Papo & Yo - Liberation'},
  {source: 'youtube', src: 'BcvzPG0o7bc', title: 'Hellblade: Senua\'s Sacrifice - Surtr (Fight Stage 2)'},
  {source: 'youtube', src: '2tUcE10yZ9I', title: 'Grum, Saints Row the 3rd - Heartbeats'},
  {source: 'youtube', src: 'D5sQErWBtrY', title: 'TLoZ:LA (2019) - Title'},
  {source: 'youtube', src: 'O_yyu-kqfBs', title: 'Alec Holowka, Night in the Woods - Die Anywhere Else'},
  {source: 'youtube', src: 'xoeipOhjw6U', title: 'Laurence Chapman, Heaven\'s Vault - Before the Fall'},
  {source: 'youtube', src: 'DZiw6ogiDAI', title: 'RPG Maker XP BGM - Battle02'},
  {source: 'youtube', src: '4rFmI0hK4d4', title: 'The Sims - Mall Rat'},
  {source: 'youtube', src: '7u65WiPxZKc', title: 'The Simpsons Hit & Run - Homer\'s Day'},
  {source: 'youtube', src: 'neEuc0CGfNs', title: 'Asterix (SNES) - Title'},
  {source: 'youtube', src: 'Mji9b1XFcbc', title: 'Super Mario All-Stars - Title Screen'},
  {source: 'youtube', src: 'D0j9AOEhzO8', title: 'Pokémon Gold, Silver, Crystal - New Bark Town'},
  {source: 'youtube', src: 'WhASqC2-OdM', title: 'Kirby: Nightmare in Dream Land - Green Greens'},
  {source: 'youtube', src: '-uYal3oMipc', title: 'Beyblade V-Force: Ultimate Blader Jam - Beyblade Theme Song'},
  {source: 'youtube', src: 'QgLAjh-fT_U', title: 'LEGO Racers - Menu'},
  {source: 'youtube', src: '9_odKbUhsQY', title: 'Flygande Start: Andra Klass - Substantiv'},
  {source: 'youtube', src: '4sJijxXt_d4', title: 'Super Mario Galaxy 2 - Puzzle Plank Galaxy'},
  {source: 'youtube', src: 'e757WWZabeI', title: 'K.K. Slider - Bloody Stream'},
  {source: 'youtube', src: '6l8PLKI9oqs', title: 'Persona 5, Phoenix Wright - Life Will Change/Cornered Mashup'},
  {source: 'youtube', src: 'iNJlMg6L3Bo', title: 'TLoZ:MC - Hyrule Town'},
  {source: 'youtube', src: 'HVhtTlOxR_Y', title: 'LISA: The RPG - Burning Sunset'},
  {source: 'youtube', src: 'vBWf9MyqA5I', title: 'LISA: The RPG - Cassette Blues'}, // Don't make me choose
  {source: 'youtube', src: 'hTj3dV77oe4', title: 'Beat Cop - Corpus Delicti'},
  {source: 'youtube', src: '3qw5dkq4W5E', title: 'The First Tree - Transformation'},
]);