var displayText = {
	1: {owner: "TheNamlessGuy", title: "1 man 2 cuphead giveaways", img: "days/1.jpg", text: "PM me 'I C U P' haha get it"},
	2: {owner: "Tristana", title: "Home Alone movienight", img: "days/2.png", text: "He (or someone) will make an announcement when it starts, will be around 10 pm GMT"},
	3: {title: "Christmas themed role colors", text: "Red and green colors available, ask staff for more info"},
	4: {},
	5: {owner: "TheNamlessGuy"},
	6: {},
	7: {},
	8: {owner: "Kamikaze_Karl"},
	9: {},
	10: {},
	11: {},
	12: {owner: "GladiaCelt"},
	13: {},
	14: {},
	15: {},
	16: {},
	17: {},
	18: {},
	19: {},
	20: {},
	21: {},
	22: {},
	23: {owner: "GladiaCelt"},
	24: {},
	25: {},
	26: {},
	27: {},
	28: {},
	29: {owner: "Kamikaze_Karl"},
	30: {},
	31: {owner: "TheNamlessGuy"}
};
